# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Arpad Biro <biro_arpad@yahoo.com>, 2006-2007
# Dimitris Glezos <glezos@indifex.com>, 2011
# Nikolas Slivka <snicore@gmail.com>, 2010
# Peter Borsa <peter.borsa@gmail.com>, 2013
# Ferenc Teknős <teknos.ferenc@gmail.com>, 2013
# Zoltan Hoppár <hopparz@gmail.com>, 2012-2013
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-11-22 12:19+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2017-09-01 08:30-0400\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Hungarian (http://www.transifex.com/projects/p/fedora/"
"language/hu/)\n"
"Language: hu\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Zanata 3.9.6\n"

#: ../setroubleshoot.desktop.in.h:1
msgid "SELinux Troubleshooter"
msgstr "SELinux hibakezelő"

#: ../setroubleshoot.desktop.in.h:2
msgid "Troubleshoot SELinux access denials"
msgstr "SELinux hozzáférés elutasítások kezelése"

#: ../setroubleshoot.desktop.in.h:3
msgid "policy;security;selinux;avc;permission;mac;alert;sealert;"
msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"

#: ../src/setroubleshoot/audit_data.py:914
#, python-format
msgid "port %s"
msgstr "port %s"

#: ../src/setroubleshoot/audit_data.py:916 ../src/setroubleshoot/browser.py:765
#: ../src/setroubleshoot/browser.py:840 ../src/setroubleshoot/rpc.py:531
#: ../src/setroubleshoot/util.py:262
msgid "Unknown"
msgstr "Ismeretlen"

#: ../src/setroubleshoot/audit_data.py:1006
#, python-format
msgid "%s \n"
"**** Invalid AVC allowed in current policy ***\n"
msgstr "%s \n"
"**** Hibás AVC engedélyezett a jelenglegi szabályzatban ***\n"

#: ../src/setroubleshoot/audit_data.py:1008
#, python-format
msgid ""
"%s \n"
"**** Invalid AVC dontaudited in current policy.  'semodule -B' will turn on "
"dontaudit rules. ***\n"
msgstr ""
"%s \n"
"**** Hibás AVC dontaudit-os a jelenlegi szabályzatban.  Az 'semodule -B' "
"opció bekapcsolja a dontaudit szabályzatot. ***\n"

#: ../src/setroubleshoot/audit_data.py:1010
msgid "Must call policy_init first"
msgstr "A policy_init-et kell elsőként hívni"

#: ../src/setroubleshoot/audit_data.py:1012
#, python-format
msgid "%s \n"
"**** Invalid AVC bad target context. ***\n"
msgstr "%s \n"
"**** Hibás AVC rossz cél kontextus. ***\n"

#: ../src/setroubleshoot/audit_data.py:1014
#, python-format
msgid "%s \n"
"**** Invalid AVC bad source context. ***\n"
msgstr "%s \n"
"**** Hibás AVC rossz forrás kontextus. ***\n"

#: ../src/setroubleshoot/audit_data.py:1016
#, python-format
msgid "%s \n"
"**** Invalid AVC bad type class ***\n"
msgstr "%s \n"
"**** Hibás AVC rossz típusosztály ***\n"

#: ../src/setroubleshoot/audit_data.py:1018
#, python-format
msgid "%s \n"
"**** Invalid AVC bad permission ***\n"
msgstr "%s \n"
"**** Hibás AVC hibás engedéllyel ***\n"

#: ../src/setroubleshoot/audit_data.py:1020
msgid "Error during access vector computation"
msgstr "Hiba a hozzáférési vektor kiszámításánál"

#: ../src/setroubleshoot/browser.py:197 ../gui/browser.glade.h:14
msgid "SELinux Alert Browser"
msgstr "SElinux riasztási böngésző"

#: ../src/setroubleshoot/browser.py:201 ../gui/browser.glade.h:21
msgid "The source process:"
msgstr "A forrás folyamat:"

#: ../src/setroubleshoot/browser.py:206 ../gui/browser.glade.h:17
msgid "Yes"
msgstr "Igen"

#: ../src/setroubleshoot/browser.py:208 ../gui/browser.glade.h:19
msgid "No"
msgstr "Nem"

#: ../src/setroubleshoot/browser.py:213 ../gui/browser.glade.h:22
msgid "Attempted this access:"
msgstr "Ez a hozzáférést próbálta:"

#: ../src/setroubleshoot/browser.py:227 ../gui/browser.glade.h:12
msgid "SETroubleshoot Details Window"
msgstr "SETroubleshoot részletező ablak"

#: ../src/setroubleshoot/browser.py:230 ../gui/browser.glade.h:16
msgid "Would you like to receive alerts?"
msgstr "Szeretne kapni riasztási üzeneteket?"

#: ../src/setroubleshoot/browser.py:234 ../gui/browser.glade.h:26
msgid "Notify Admin"
msgstr "Admin értesítése"

#: ../src/setroubleshoot/browser.py:237 ../src/setroubleshoot/browser.py:243
#: ../gui/browser.glade.h:8
msgid "Troubleshoot"
msgstr "Hibaelhárítás"

#: ../src/setroubleshoot/browser.py:240 ../gui/browser.glade.h:28
msgid "Details"
msgstr "Részletek"

#: ../src/setroubleshoot/browser.py:247 ../gui/browser.glade.h:7
msgid "SETroubleshoot Alert List"
msgstr "SETroubleshoot riasztási lista"

#: ../src/setroubleshoot/browser.py:249 ../gui/browser.glade.h:37
msgid "List All Alerts"
msgstr "Listázd az összes riasztást"

#: ../src/setroubleshoot/browser.py:296
msgid "#"
msgstr "#"

#: ../src/setroubleshoot/browser.py:296
msgid "Source Process"
msgstr "Forrás folyamat"

#: ../src/setroubleshoot/browser.py:296
msgid "Attempted Access"
msgstr "Hozzáférési próbálkozás"

#: ../src/setroubleshoot/browser.py:296
msgid "On this"
msgstr "Ezen"

#: ../src/setroubleshoot/browser.py:296
msgid "Occurred"
msgstr "Történt"

#: ../src/setroubleshoot/browser.py:296 ../src/run_cmd.py:409
msgid "Status"
msgstr "Állapot"

#: ../src/setroubleshoot/browser.py:370 ../src/setroubleshoot/browser.py:804
#: ../src/setroubleshoot/browser.py:848
msgid "Notify"
msgstr "Észrevétel"

#: ../src/setroubleshoot/browser.py:371
msgid "Notify alert in the future."
msgstr "Riasszon a jövőben  is."

#: ../src/setroubleshoot/browser.py:374 ../src/setroubleshoot/browser.py:806
#: ../src/setroubleshoot/browser.py:846 ../gui/browser.glade.h:29
msgid "Ignore"
msgstr "Hagyja ki"

#: ../src/setroubleshoot/browser.py:375 ../gui/browser.glade.h:30
msgid "Ignore alert in the future."
msgstr "Riaszás figyelmen kívül hagyása a jövőben."

#: ../src/setroubleshoot/browser.py:412
msgid "<b>If you were trying to...</b>"
msgstr "<b>Ha szeretné...</b>"

#: ../src/setroubleshoot/browser.py:421
msgid "<b>Then this is the solution.</b>"
msgstr "<b>Akkor ez a megoldás.</b>"

#: ../src/setroubleshoot/browser.py:518
msgid "Plugin\n"
"Details"
msgstr "Plugin\n"
"részletei"

#: ../src/setroubleshoot/browser.py:533
msgid "Report\n"
"Bug"
msgstr "Jelentés\n"
"Hiba"

#: ../src/setroubleshoot/browser.py:562
#, python-format
msgid "Plugin: %s "
msgstr "Plugin: %s "

#: ../src/setroubleshoot/browser.py:629
msgid "Unable to grant access."
msgstr "Nem sikerült engedélyezni a hozzáférést."

#: ../src/setroubleshoot/browser.py:660 ../src/setroubleshoot/browser.py:802
#, python-format
msgid "Alert %d of %d"
msgstr "Riasztás %d / %d"

#: ../src/setroubleshoot/browser.py:785
#, python-format
msgid "On this %s:"
msgstr "Ezen %s"

#: ../src/setroubleshoot/browser.py:833 ../src/setroubleshoot/browser.py:839
#: ../src/setroubleshoot/signature.py:412
msgid "N/A"
msgstr "N/A"

#: ../src/setroubleshoot/browser.py:880 ../src/setroubleshoot/browser.py:881
#: ../gui/browser.glade.h:34
msgid "No Alerts"
msgstr "Nincs riasztás"

#: ../src/setroubleshoot/browser.py:899
msgid "SELinux has detected a problem."
msgstr "Az SElinux hibát észlelt."

#: ../src/setroubleshoot/browser.py:1008
msgid "Sealert Error"
msgstr "Sealert hiba"

#: ../src/setroubleshoot/browser.py:1019
msgid "Sealert Message"
msgstr "Sealert üzenet"

#. -----------------------------------------------------------------------------
#: ../src/setroubleshoot/errcode.py:80
msgid "signature not found"
msgstr "nincs aláírás"

#: ../src/setroubleshoot/errcode.py:81
msgid "multiple signatures matched"
msgstr "több aláírás egyezik"

#: ../src/setroubleshoot/errcode.py:82
msgid "id not found"
msgstr "azonosító nem található"

#: ../src/setroubleshoot/errcode.py:83
msgid "database not found"
msgstr "adatbázis nem található"

#: ../src/setroubleshoot/errcode.py:84
msgid "item is not a member"
msgstr "az elem nem tag"

#: ../src/setroubleshoot/errcode.py:85
msgid "illegal to change user"
msgstr "nem változtathat felhasználót"

#: ../src/setroubleshoot/errcode.py:86
msgid "method not found"
msgstr "eljárás nem található"

#: ../src/setroubleshoot/errcode.py:87
msgid "cannot create GUI"
msgstr "GUI indítása sikertelen"

#: ../src/setroubleshoot/errcode.py:88
msgid "value unknown"
msgstr "ismeretlen érték"

#: ../src/setroubleshoot/errcode.py:89
msgid "cannot open file"
msgstr "fájl nem megnyitható "

#: ../src/setroubleshoot/errcode.py:90
msgid "invalid email address"
msgstr "Érvénytelen email cím"

#. gobject IO Errors
#: ../src/setroubleshoot/errcode.py:93
msgid "socket error"
msgstr "socket hiba"

#: ../src/setroubleshoot/errcode.py:94
msgid "connection has been broken"
msgstr "kapcsolat megszakadt"

#: ../src/setroubleshoot/errcode.py:95
msgid "Invalid request. The file descriptor is not open"
msgstr "Érvénytelen kérés. A fájl leíró nincs nyitva"

#: ../src/setroubleshoot/errcode.py:97
msgid "insufficient permission to modify user"
msgstr "elégtelen jogosultság a felhasználó megváltoztatására"

#: ../src/setroubleshoot/errcode.py:98
msgid "authentication failed"
msgstr "hitelesítés sikertelen"

#: ../src/setroubleshoot/errcode.py:99
msgid "user prohibited"
msgstr "felhasználó letiltva"

#: ../src/setroubleshoot/errcode.py:100
msgid "not authenticated"
msgstr "nincs azonosítva"

#: ../src/setroubleshoot/errcode.py:101
msgid "user lookup failed"
msgstr "felhasználó keresés eredménytelen"

#: ../src/setroubleshoot/gui_utils.py:55 ../src/sealert:542
#, c-format, python-format
msgid "Opps, %s hit an error!"
msgstr "Upsz, %s hibaüzenetet kapott!"

#: ../src/setroubleshoot/gui_utils.py:57 ../gui/fail_dialog.glade.h:1
msgid "Error"
msgstr "Hiba"

#: ../src/setroubleshoot/Plugin.py:90
msgid ""
"If you want to allow $SOURCE_BASE_PATH to have $ACCESS access on the "
"$TARGET_BASE_PATH $TARGET_CLASS"
msgstr ""

#: ../src/run_cmd.py:175
msgid "Input: "
msgstr "Bemenet:"

#: ../src/run_cmd.py:258
msgid "Enter Password"
msgstr "Adja meg jelszavát"

#: ../src/run_cmd.py:271
msgid "Password: "
msgstr "Jelszó:"

#: ../src/run_cmd.py:370
msgid "SELinux Fix"
msgstr "SELinux Fix"

#: ../src/run_cmd.py:381
msgid "Command"
msgstr "Parancs"

#: ../src/run_cmd.py:391
msgid "Run Command"
msgstr "Parancs végrehajtása"

#: ../src/run_cmd.py:394
msgid "Stop Command"
msgstr "Parancs leállítása"

#: ../src/run_cmd.py:416
msgid "Warning: You are responsible for verifying this command is correct"
msgstr ""
"Figyelem: Az Ön felelőssége, hogy a kiadott parancs pontos és helyes legyen"

#: ../src/run_cmd.py:458
msgid "Not Run Yet"
msgstr "Még nem futott"

#: ../src/run_cmd.py:469
msgid "Running..."
msgstr "Működésben…"

#: ../src/run_cmd.py:484
#, python-format
msgid "Interrupted, exit on signal %d"
msgstr "Megszakítva, kilépett %d jelzéssel"

#: ../src/run_cmd.py:486
msgid "Success"
msgstr "Siker"

#: ../src/run_cmd.py:488
#, python-format
msgid "Failed, exit status = %d"
msgstr "Hiba, hibakód = %d"

#: ../src/run_cmd.py:490
msgid "Done: "
msgstr "Kész:"

#: ../src/setroubleshoot/server.py:212
#, python-format
msgid " For complete SELinux messages run: sealert -l %s"
msgstr ""

#: ../src/setroubleshoot/server.py:399
#, python-format
msgid "The user (%s) cannot modify data for (%s)"
msgstr "A (%s) felhasználó nem módosíthatja (%s) adatait"

#: ../src/setroubleshoot/server.py:469 ../src/sealert:302
msgid "Started"
msgstr "Elindítva"

#: ../src/setroubleshoot/server.py:668
msgid "AVC"
msgstr "AVC"

#: ../src/setroubleshoot/server.py:731
msgid "Audit Listener"
msgstr "Audit figyelő"

#: ../src/setroubleshoot/signature.py:88
msgid "Never Ignore"
msgstr "Soha ne mellőzze"

#: ../src/setroubleshoot/signature.py:89
msgid "Ignore Always"
msgstr "Mindig mellőzze"

#: ../src/setroubleshoot/signature.py:90
msgid "Ignore After First Alert"
msgstr "Mellőzze az első riasztás után"

#: ../src/setroubleshoot/signature.py:207
msgid "directory"
msgstr "könyvtár"

#: ../src/setroubleshoot/signature.py:208
msgid "semaphore"
msgstr "szemafor"

#: ../src/setroubleshoot/signature.py:209
msgid "shared memory"
msgstr "osztott memória"

#: ../src/setroubleshoot/signature.py:210
msgid "message queue"
msgstr "üzenetsor"

#: ../src/setroubleshoot/signature.py:211
msgid "message"
msgstr "üzenet"

#: ../src/setroubleshoot/signature.py:212
msgid "file"
msgstr "fájl"

#: ../src/setroubleshoot/signature.py:213
msgid "socket"
msgstr "port"

#: ../src/setroubleshoot/signature.py:214
msgid "process"
msgstr "folyamat"

#: ../src/setroubleshoot/signature.py:215
msgid "process2"
msgstr ""

#: ../src/setroubleshoot/signature.py:216
msgid "filesystem"
msgstr "fájlrendszer"

#: ../src/setroubleshoot/signature.py:217
msgid "node"
msgstr "csomópont"

#: ../src/setroubleshoot/signature.py:218
msgid "capability"
msgstr "funkció"

#: ../src/setroubleshoot/signature.py:219
msgid "capability2"
msgstr ""

#: ../src/setroubleshoot/signature.py:396
#, python-format
msgid "%s has a permissive type (%s). This access was not denied."
msgstr ""
"%s egy engedélyező típussal rendelkezik (%s). Ez a hozzáférés nem volt "
"megtagadva."

#: ../src/setroubleshoot/signature.py:399
msgid "SELinux is in permissive mode. This access was not denied."
msgstr "SElinux átengedő módban van. Ez a hozzáférés nem volt blokkolva."

#: ../src/setroubleshoot/signature.py:453
#, python-format
msgid "SELinux is preventing %s from using the %s access on a process."
msgstr ""
"SELinux megakadályozta %s számára %s elérhető hozzáférést a folyamaton."

#: ../src/setroubleshoot/signature.py:453
#, python-format
msgid "SELinux is preventing %s from using the '%s' accesses on a process."
msgstr ""
"SELinux megakadályozta %s számára %s elérhető hozzáféréseket a folyamaton."

#: ../src/setroubleshoot/signature.py:456
#, python-format
msgid "SELinux is preventing %s from using the %s capability."
msgstr "SELinux megakadályozta %s számára %s funkció használatát."

#: ../src/setroubleshoot/signature.py:456
#, python-format
msgid "SELinux is preventing %s from using the '%s' capabilities."
msgstr "SELinux megakadályozta %s számára '%s' funkciók használatát."

#: ../src/setroubleshoot/signature.py:458
#, python-format
msgid "SELinux is preventing %s from %s access on the %s labeled %s."
msgstr ""
"SELinux megakadályozta %s alkalmazás %s hozzáférését %s erőforrás %s "
"címkézett elemén."

#: ../src/setroubleshoot/signature.py:458
#, python-format
msgid "SELinux is preventing %s from '%s' accesses on the %s labeled %s."
msgstr ""
"SElinux megakadályozta %s számára '%s' hozzáféréseit %s címkével ezen: %s"

#: ../src/setroubleshoot/signature.py:459
#, python-format
msgid "SELinux is preventing %s from %s access on the %s %s."
msgstr "SELinux megakadályozta %s számára %s hozzáférését itt: %s %s."

#: ../src/setroubleshoot/signature.py:459
#, python-format
msgid "SELinux is preventing %s from '%s' accesses on the %s %s."
msgstr "SELinux megakadályozta %s számára '%s' hozzáféréseit itt: %s %s."

#: ../src/setroubleshoot/signature.py:504
msgid "Additional Information:\n"
msgstr "További információ:\n"

#: ../src/setroubleshoot/signature.py:505
msgid "Source Context"
msgstr "Forrás kontextus"

#: ../src/setroubleshoot/signature.py:506
msgid "Target Context"
msgstr "Cél kontextus"

#: ../src/setroubleshoot/signature.py:507
msgid "Target Objects"
msgstr "Cél objektumok"

#: ../src/setroubleshoot/signature.py:508
msgid "Source"
msgstr "Forrás"

#: ../src/setroubleshoot/signature.py:509
msgid "Source Path"
msgstr "Forrás elérési útja"

#: ../src/setroubleshoot/signature.py:510
msgid "Port"
msgstr "Port"

#: ../src/setroubleshoot/signature.py:512
#: ../src/setroubleshoot/signature.py:514
msgid "Host"
msgstr "Kiszolgáló"

#: ../src/setroubleshoot/signature.py:515
msgid "Source RPM Packages"
msgstr "Forrás RPM csomagok"

#: ../src/setroubleshoot/signature.py:516
msgid "Target RPM Packages"
msgstr "Cél RPM csomagok"

#: ../src/setroubleshoot/signature.py:517
msgid "Policy RPM"
msgstr "Szabályzat RPM"

#: ../src/setroubleshoot/signature.py:518
msgid "Selinux Enabled"
msgstr "SELinux bekapcsolva"

#: ../src/setroubleshoot/signature.py:519
msgid "Policy Type"
msgstr "Szabályzat típus"

#: ../src/setroubleshoot/signature.py:520
msgid "Enforcing Mode"
msgstr "Kényszerítő mód"

#: ../src/setroubleshoot/signature.py:522
#: ../src/setroubleshoot/signature.py:524
msgid "Host Name"
msgstr "Kiszolgáló neve"

#: ../src/setroubleshoot/signature.py:529
#: ../src/setroubleshoot/signature.py:531
msgid "Platform"
msgstr "Platform"

#: ../src/setroubleshoot/signature.py:532
msgid "Alert Count"
msgstr "Riasztás mennyisége"

#: ../src/setroubleshoot/signature.py:534
msgid "First Seen"
msgstr "Először megjelent"

#: ../src/setroubleshoot/signature.py:535
msgid "Last Seen"
msgstr "Utoljára megjelent"

#: ../src/setroubleshoot/signature.py:536
msgid "Local ID"
msgstr "Helyi azonosító"

#: ../src/setroubleshoot/signature.py:538
msgid "Raw Audit Messages"
msgstr "Nyers auditálási üzenetek"

#: ../src/setroubleshoot/signature.py:592
#, python-format
msgid "\n"
"\n"
"*****  Plugin %s (%.4s confidence) suggests   "
msgstr "\n"
"\n"
"*****  Plugin %s (%.4s bizonyossággal) javasolja a következőt   "

#: ../src/setroubleshoot/signature.py:595
msgid "*"
msgstr "*"

#: ../src/setroubleshoot/signature.py:596
#: ../src/setroubleshoot/signature.py:598
msgid "\n"
msgstr "\n"

#: ../src/setroubleshoot/signature.py:600
msgid "\n"
"Then "
msgstr "\n"
"Akkor "

#: ../src/setroubleshoot/signature.py:603
msgid "\n"
"Do\n"
msgstr "\n"
"Tedd\n"

#: ../src/setroubleshoot/signature.py:605
msgid "\n"
"\n"
msgstr "\n"
"\n"

#: ../src/updater.py:18
#, python-format
msgid "current: %s "
msgstr "jelenlegi: %s "

#: ../src/updater.py:27
#, python-format
msgid "newer: %s "
msgstr "újabb: %s"

#: ../src/seapplet.c:189
msgid "New SELinux security alert"
msgstr "Új SELinux biztonsági riasztás"

#: ../src/seapplet.c:189
msgid "AVC denial, click icon to view"
msgstr "AVC tiltás. Kattintson az ikonra, hogy megtekinthesse"

#: ../src/seapplet.c:195 ../src/seapplet.c:246
msgid "Dismiss"
msgstr "Eldobás"

#: ../src/seapplet.c:205 ../src/seapplet.c:256
msgid "Show"
msgstr "Megjelenítés"

#. set tooltip
#: ../src/seapplet.c:440 ../src/sealert:70
msgid "SELinux AVC denial, click to view"
msgstr "SELinux AVC megtagadás. Kattintson, hogy megtekinthesse"

#: ../src/sealert:112
msgid "SELinux not enabled, sealert will not run on non SELinux systems"
msgstr ""
"SElinux nincs engedélyezve, sealert nem fog működni nem SElinux rendszereken"

#: ../src/sealert:159
msgid "Not fixable."
msgstr "Nem javítható."

#: ../src/sealert:166
#, c-format
msgid "Successfully ran %s"
msgstr "%s sikeresen lefutott"

#: ../src/sealert:173
#, c-format
msgid "Plugin %s not valid for %s id"
msgstr "Plugin %s nem érvényes a %s ID-hez"

#: ../src/setroubleshootd:78
msgid "SELinux not enabled, setroubleshootd exiting..."
msgstr "SELinux nincs engedélyezve, setroubleshootd kilép..."

#: ../src/setroubleshootd:110
#, c-format
msgid "fork #1 failed: %d (%s)"
msgstr "fork #1 sikertelen: %d (%s)"

#: ../gui/browser.glade.h:1
msgid ""
"Copyright (c) 2010\n"
"Thomas Liu <tliu@redhat.com>\n"
"Máirín Duffy <duffy@redhat.com>\n"
"Daniel Walsh <dwalsh@redhat.com>\n"
"John Dennis <jdennis@redhat.com>\n"
msgstr ""

#: ../gui/browser.glade.h:9
msgid "Troubleshoot selected alert"
msgstr "Hibaelhárítás a kiválasztott riasztáson"

#: ../gui/browser.glade.h:10
msgid "Delete"
msgstr ""

#: ../gui/browser.glade.h:11
msgid "Delete Selected Alerts"
msgstr "Kijelölt riasztások törlése"

#: ../gui/browser.glade.h:13
msgid "Close"
msgstr ""

#: ../gui/browser.glade.h:15
msgid "<b>SELinux has detected a problem.</b>"
msgstr "<b>SELinux hibát érzékelt.</b>"

#: ../gui/browser.glade.h:18
msgid "Turn on alert pop-ups."
msgstr "Felugró riasztási üzenetek bekapcsolása."

#: ../gui/browser.glade.h:20
msgid "Turn off alert pop-ups."
msgstr "Felugró riasztási üzenetek kikapcsolása."

#: ../gui/browser.glade.h:23
msgid "On this file:"
msgstr "Ezen a fájlon:"

#: ../gui/browser.glade.h:24
msgid "label"
msgstr "cimke"

#: ../gui/browser.glade.h:25
msgid ""
"Read alert troubleshoot information.  May require administrative privileges "
"to remedy."
msgstr ""
"Olvassa el a riasztási problémamegoldó információkat.  Lehet hogy "
"adminisztrációs jogokra lesz szüksége a megoldáshoz."

#: ../gui/browser.glade.h:27
msgid "Email alert to system administrator."
msgstr "Email risztás a rendszer adminisztátorának"

#: ../gui/browser.glade.h:31
msgid "Delete current alert from the database."
msgstr "Jelenlegi riasztás törlése az adatbázisból"

#: ../gui/browser.glade.h:32
msgid "Previous"
msgstr ""

#: ../gui/browser.glade.h:33
msgid "Show previous alert."
msgstr "Előző riasztás"

#: ../gui/browser.glade.h:35
msgid "Next"
msgstr ""

#: ../gui/browser.glade.h:36
msgid "Show next alert."
msgstr "Következő riasztás"

#: ../gui/browser.glade.h:38
msgid "List all alerts in the database."
msgstr "Az összes riasztás listázása az azdatbázisból."

#: ../gui/bug_report.glade.h:1
msgid "Review and Submit Bug Report"
msgstr "Felülvizsgálja és beküldi a hibajelentést"

#: ../gui/bug_report.glade.h:2
msgid "<span size='large' weight='bold'>Review and Submit Bug Report</span>"
msgstr ""
"<span size='large' weight='bold'>Felülvizsgálja és beküldi a hiba jelentést</"
"span>"

#: ../gui/bug_report.glade.h:3
msgid ""
"You may wish to review the error output that will be included in this bug "
"report and modify it to exclude any sensitive data below."
msgstr ""
"Előfordulhat, hogy szeretné felülvizsgálni a hiba kimenetét amit a "
"hibajelentésbe fogunk foglalni, és változtatni kíván rajta, azzal, hogy "
"eltávolít érzékeny adatokat. Alább ezt megteheti."

#: ../gui/bug_report.glade.h:4
msgid "Included error output:"
msgstr "Benne foglalt hiba kimenet:"

#: ../gui/bug_report.glade.h:5
msgid "Submit Report"
msgstr "Jelentés beküldése"

#: ../gui/fail_dialog.glade.h:2 ../gui/success_dialog.glade.h:2
msgid ""
"This operation was completed.  The quick brown fox jumped over the lazy dog."
msgstr ""
"Ez a művelet befejeződött.  A fürge vörösesbarna róka átugrotta a lusta "
"kutyát."

#: ../gui/success_dialog.glade.h:1
msgid "Success!"
msgstr "Sikerült!"

#: ../gui/success_dialog.glade.h:3
msgid "button"
msgstr "gomb"
