# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Arpad Biro <biro_arpad@yahoo.com>, 2006, 2007
# Nikolas Slivka <snicore@gmail.com>, 2010
# Oszkár Ocsenás <ocsenaso@gmail.com>, 2009
# Sulyok Péter <peti@fedoraproject.org>, 200, 2010
# Ferenc Teknős <teknos.ferenc@gmail.com>, 2013
# Zoltan Hoppár <hopparz@gmail.com>, 2012-2013
# Norbert Makula <iamreallynotapokemon@gmail.com>, 2017. #zanata
# Vit Mojzis <vmojzis@redhat.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-10-31 20:57+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2017-09-01 08:32-0400\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Hungarian (http://www.transifex.com/projects/p/fedora/"
"language/hu/)\n"
"Language: hu\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Zanata 3.9.6\n"

#: ../src/allow_anon_write.py:27
msgid ""
"\n"
"    SELinux policy is preventing an httpd script from writing to a public\n"
"    directory.\n"
"    "
msgstr ""
"\n"
"    SELinux-szabályzat megakadályozta, hogy egy HTTP-szkript egy\n"
"    nyilvános könyvtárba írjon.\n"
"    "

#: ../src/allow_anon_write.py:32
msgid ""
"\n"
"    SELinux policy is preventing an httpd script from writing to a public\n"
"    directory.  If httpd is not setup to write to public directories, this\n"
"    could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    A SELinux szabályzat megakadályozta, hogy egy httpd alkalmazás írjon\n"
"    egy nyilvános mappába. Ha a httpd beállítása nem engedi meg az\n"
"    írást nyilvános mappákba, akkor ez behatolási kísérletet jelezhet.\n"
"    "

#: ../src/allow_anon_write.py:38
msgid ""
"\n"
"    If httpd scripts should be allowed to write to public directories you "
"need to turn on the $BOOLEAN boolean and change the file context of the "
"public directory to public_content_rw_t.  Read the httpd_selinux\n"
"    man page for further information:\n"
"    \"setsebool -P $BOOLEAN=1; chcon -t public_content_rw_t <path>\"\n"
"    You must also change the default file context labeling files on the "
"system in order to preserve public directory labeling even on a full relabel."
"  \"semanage fcontext -a -t public_content_rw_t <path>\"\n"
"    "
msgstr ""
"\n"
"Ha szükséges engedélyezni, hogy a \"httpd\"-szkriptek írhassanak a\n"
"    nyilvános könyvtárakba, akkor be kell kapcsolnia a(z) $BOOLEAN\n"
"    logikai értéket, valamint módosítania kell a nyilvános könyvtár\n"
"    fájl beállítását erre: public_content_rw_t. \n"
"További információk  találhatók a \"httpd_selinux\" kézikönyvlapon (man). \n"
"A fenti tevékenységeket elvégző parancs: \"setsebool -P $BOOLEAN=1;\n"
"    chcon -t public_content_rw_t < elérési útvonal>\".\n"
"\n"
"    Az alap beállítás fájlokat is meg kell változtatnia, hogy az előbbi \n"
"    maradandó legyen teljes újracímkézés esetén is. \n"
"    „semanage fcontext -a -t public_content_rw_t <elérési útvonal>”"

#: ../src/allow_anon_write.py:44
msgid ""
"If you want to allow $SOURCE_PATH to be able to write to shared public "
"content"
msgstr ""

#: ../src/allow_anon_write.py:45
msgid ""
"you need to change the label on $TARGET_PATH to public_content_rw_t, and "
"potentially turn on the allow_httpd_sys_script_anon_write boolean."
msgstr ""
"meg kell változtatnia a cimkét a $TARGET_PATH számára public_content_rw_t "
"cimkére, és potenciálisan be kell kapcsolni a "
"allow_httpd_sys_script_anon_write boolean-t."

#: ../src/allow_execheap.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from changing the access\n"
"    protection of memory on the heap.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza, hogy $SOURCE_PATH megváltoztassa a heap \n"
"    memória hozzáférés védelmét.\n"
"    "

#: ../src/allow_execheap.py:32
msgid ""
"\n"
"    The $SOURCE application attempted to change the access protection of "
"memory on\n"
"    the heap (e.g., allocated using malloc).  This is a potential security\n"
"    problem.  Applications should not be doing this. Applications are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  If $SOURCE does not "
"work and\n"
"    you need it to work, you can configure SELinux temporarily to allow\n"
"    this access until the application is fixed. Please file a bug\n"
"    report against this package.\n"
"    "
msgstr ""
"\n"
"    $SOURCE alkalmazás megkísérelt változtatni a heap (pl. a malloc \n"
"    függvénnyel lefoglalt) memória hozzáférés védelmén.\n"
"    Ez lehet biztonsági probléma. Alkalmazásoknak ezt tenniük.\n"
"    Néha hibás alkalmazások kérnek ilyen engedélyt.  A\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    weblap elmagyarázza, hogyan kell megszüntetni ezt az igényt.  Ha \n"
"    $SOURCE nem működik, de szükség van rá, akkor ideiglenesen\n"
"    beállíthatja, hogy SELinux megengedje ezt a\n"
"    hozzáférést, amíg az alkalmazást ki nem javítják. Tegyen hibabejelentést\n"
"    erre a csomagra.\n"
"    "

#: ../src/allow_execheap.py:44
msgid ""
"\n"
"    If you want $SOURCE to continue, you must turn on the\n"
"    $BOOLEAN boolean.  Note: This boolean will affect all applications\n"
"    on the system.\n"
"    "
msgstr ""
"\n"
"    Ha szeretné, hogy $SOURCE folytatódjon, akkor be kell\n"
"    kapcsolni $BOOLEAN logikai értéket.  Megjegyzés: ez a\n"
"    logikai érték a rendszer minden alkalmazására kihat.\n"
"    "

#: ../src/allow_execheap.py:50
msgid ""
"If you do not think $SOURCE_PATH should need to map heap memory that is both "
"writable and executable."
msgstr ""

#: ../src/allow_execheap.py:51
msgid "you need to report a bug. This is a potentially dangerous access."
msgstr ""
"jelentse a hibát. Ez egy potenciálisan veszélyes hozzáférési lehetőség."

#: ../src/allow_execheap.py:52 ../src/allow_execstack.py:91
#: ../src/kernel_modules.py:46 ../src/mmap_zero.py:48
#: ../src/selinuxpolicy.py:46 ../src/setenforce.py:29 ../src/setenforce.py:50
#: ../src/sys_module.py:30 ../src/sys_module.py:48
msgid "Contact your security administrator and report this issue."
msgstr "Lépjen kapcsolatba a biztonsági adminnal és jelentse ezt a problémát."

#: ../src/allow_execmod.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from loading $TARGET_PATH which "
"requires text relocation.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza, hogy $SOURCE_PATH betöltsön $TARGET_PATH elérési "
"útról,\n"
"    amihez szöveg áthelyezés szükséges.\n"
"    "

#: ../src/allow_execmod.py:33
msgid ""
"\n"
"    The $SOURCE application attempted to load $TARGET_PATH which\n"
"    requires text relocation.  This is a potential security problem.\n"
"    Most libraries do not need this permission. Libraries are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  You can configure\n"
"    SELinux temporarily to allow $TARGET_PATH to use relocation as a\n"
"    workaround, until the library is fixed. Please file a\n"
"bug report.\n"
"    "
msgstr ""

#: ../src/allow_execmod.py:45
msgid ""
"\n"
"    The $SOURCE application attempted to load $TARGET_PATH which\n"
"    requires text relocation.  This is a potential security problem.\n"
"    Most libraries should not need this permission.   The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">\n"
"    SELinux Memory Protection Tests</a>\n"
"    web page explains this check.  This tool examined the library and it "
"looks\n"
"    like it was built correctly. So setroubleshoot can not determine if this\n"
"    application is compromised or not.  This could be a serious issue. Your\n"
"    system may very well be compromised.\n"
"\n"
"    Contact your security administrator and report this issue.\n"
"\n"
"    "
msgstr ""

#: ../src/allow_execmod.py:62
msgid ""
"\n"
"    If you trust $TARGET_PATH to run correctly, you can change the\n"
"    file context to textrel_shlib_t. \"chcon -t textrel_shlib_t\n"
"    '$TARGET_PATH'\"\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"textrel_shlib_t '$FIX_TARGET_PATH'\"\n"
"\n"
"    "
msgstr ""
"\n"
"    Ha bíznak abban, hogy $TARGET_PATH helyesen működik, akkor\n"
"    módosíthatják a fájl beállítást textrel_shlib_t típusra:\n"
"    „chcon -t textrel_shlib_t '$TARGET_PATH'”\n"
"    Az alap fájl beállítás fájlokat szintén meg kell változtatni, hogy a "
"változások megmaradjanak még teljes újracímkézés esetén is:\n"
"    „semanage fcontext -a -t textrel_shlib_t '$FIX_TARGET_PATH'”\n"
"\n"
"    "

#: ../src/allow_execstack.py:60
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from making the program stack "
"executable.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza, hogy $SOURCE_PATH végrehajthatóvá tegye\n"
"    a verem memóriát (stack).\n"
"    "

#: ../src/allow_execstack.py:64
msgid ""
"\n"
"    The $SOURCE application attempted to make its stack\n"
"    executable.  This is a potential security problem.  This should\n"
"    never ever be necessary. Stack memory is not executable on most\n"
"    OSes these days and this will not change. Executable stack memory\n"
"    is one of the biggest security problems. An execstack error might\n"
"    in fact be most likely raised by malicious code. Applications are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  If $SOURCE does not\n"
"    work and you need it to work, you can configure SELinux\n"
"    temporarily to allow this access until the application is fixed. Please\n"
"file a bug report.\n"
"    "
msgstr ""
"\n"
"    $SOURCE alkalmazás megkísérelte végrehajthatóvá tenni a\n"
"    vermét (stack). Ez biztonsági problémát jelenthet.  Ez sohasem\n"
"    szükséges. A verem memória a legtöbb operációs\n"
"    rendszerben nem végrehajtható – ez a jövőben sem fog változni. A\n"
"    végrehajtható verem memória az egyik legnagyobb biztonsági probléma.\n"
"    A végrehajtható veremmel kapcsolatos hiba gyakran rosszindulatú\n"
"    programra utal. Bizonyos alkalmazások viszont hibásra sikerültek,\n"
"    és igénylik ezt az engedélyt. Az\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    weblap elmagyarázza, hogyan kell megszüntetni ezt az igényt. Ha $SOURCE \n"
"    nem működik, de szükség van rá, akkor ideiglenesen beállíthatja,\n"
"    hogy SELinux engedélyezze ezt a hozzáférést, amíg az alkalmazást\n"
"    ki nem javítják. Kérem tegyen hibabejelentést.\n"
"    "

#: ../src/allow_execstack.py:79
msgid ""
"\n"
"    Sometimes a library is accidentally marked with the execstack flag,\n"
"    if you find a library with this flag you can clear it with the\n"
"    execstack -c LIBRARY_PATH.  Then retry your application.  If the\n"
"    app continues to not work, you can turn the flag back on with\n"
"    execstack -s LIBRARY_PATH.\n"
"    "
msgstr ""
"\n"
"Néha a kódkönyvtár véletlen folytán megjelölődhet execstack flag-el, \n"
"ha talál ilyen kódkönyvtárat ezzel a flag-el, törölheti a\n"
" execstack -c LIBRARY_PATH utasítással. Utána megpróbálhatja újra az "
"alkalmazást. Ha a program\n"
" továbbra sem működik a flag-et visszakapcsolhatja\n"
"execstack -s LIBRARY_PATH utasítással."

#: ../src/allow_execstack.py:89
msgid ""
"If you do not think $SOURCE_PATH should need to map stack memory that is "
"both writable and executable."
msgstr ""

#: ../src/allow_execstack.py:90
msgid "you need to report a bug. \n"
"This is a potentially dangerous access."
msgstr ""
"jelentenie kell egy hibát.\n"
"Ez egy potenciálisan veszélyes, kockázatos hozzáférés."

#: ../src/allow_execstack.py:99
#, python-format
msgid "If you believe that \n"
"%s\n"
"should not require execstack"
msgstr ""

#: ../src/allow_execstack.py:108
#, python-format
msgid ""
"you should clear the execstack flag and see if $SOURCE_PATH works correctly.\n"
"Report this as a bug on %s.\n"
"You can clear the exestack flag by executing:"
msgstr ""
"ki kell törölnie az execstack jelzést és ellenőrizze, hogy a $SOURCE_PATH "
"jól működik, vagy sem.\n"
"Jelentse ezt, mint hibát erre a csomagra: %s. \n"
"Magát az execstack jelzést, pedig törölheti ezzel a parancssal:"

#: ../src/allow_execstack.py:118
#, python-format
msgid "execstack -c %s"
msgstr "execstack -c %s"

#: ../src/allow_ftpd_use_cifs.py:29
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a CIFS "
"filesystem.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta ftpd szolgáltatás $ACCESS hozzáférését CIFS-"
"fájlrendszeren tárolt fájlokhoz.\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:33
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a CIFS "
"filesystem.\n"
"    CIFS (Comment Internet File System) is a network filesystem similar to\n"
"    SMB (<a href=\"http://www.microsoft.com/mind/1196/cifs.asp\">http://www."
"microsoft.com/mind/1196/cifs.asp</a>)\n"
"    The ftp daemon attempted to read one or more files or directories from\n"
"    a mounted filesystem of this type.  As CIFS filesystems do not support\n"
"    fine-grained SELinux labeling, all files and directories in the\n"
"    filesystem will have the same security context.\n"
"\n"
"    If you have not configured the ftp daemon to read files from a CIFS "
"filesystem\n"
"    this access attempt could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta ftpd szolgáltatás $ACCESS hozzáférését\n"
"    CIFS fájlrendszerben tárolt fájlokhoz.\n"
"    A CIFS (Common Internet File System) az SMB-hez\n"
"    hasonló hálózati fájlrendszer\n"
"    (<a href=\"http://www.microsoft.com/mind/1196/cifs.asp\">http://www."
"microsoft.com/mind/1196/cifs.asp</a>).\n"
"    Az ftpd szolgáltatás megkísérelt olvasni egy vagy több olyan\n"
"    fájlt illetve mappát, amely ilyen típusú csatolt fájlrendszeren\n"
"    van. A CIFS fájlrendszerek nem támogatják a kifinomult\n"
"    SELinux címkézést, ezért a fájlrendszerben levő összes fájl és\n"
"    mappa ugyanazon biztonsági beállítással rendelkezik.\n"
"\n"
"    Ha nem állították be ftpd szolgáltatást \n"
"    fájlok olvasására valamely CIFS fájlrendszerből, akkor ez\n"
"    behatolás próbálkozást jelezhet.\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:46
msgid ""
"\n"
"    Changing the \"$BOOLEAN\" boolean to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1.\"\n"
"    "
msgstr ""
"\n"
"    „$BOOLEAN” logikai érték igazra állításával megengedheti e hozzáférést:\n"
"    „setsebool -P $BOOLEAN=1”.\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:53
msgid ""
" Changing the \"$BOOLEAN\" and\n"
"    \"$WRITE_BOOLEAN\" booleans to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1 $WRITE_BOOLEAN=1\".\n"
"    warning: setting the \"$WRITE_BOOLEAN\" boolean to true will\n"
"    allow the ftp daemon to write to all public content (files and\n"
"    directories with type public_content_t) in addition to writing to\n"
"    files and directories on CIFS filesystems.  "
msgstr ""
" „$BOOLEAN” és a(z) „$WRITE_BOOLEAN” logikai érték igazra állítása\n"
"    engedélyezi e hozzáférést: „setsebool -P $BOOLEAN=1 $WRITE_BOOLEAN=1”\n"
"    Figyelmeztetés: „$WRITE_BOOLEAN” logikai\n"
"    érték igazra állítása engedélyezi az ftpd szolgáltatásnak\n"
"    az összes nyilvános tartalom (a public_content_t típusú fájlok\n"
"    és könyvtárak) írását is azon felül, hogy írhatja a\n"
"    CIFS-fájlrendszereken levő fájlokat és könyvtárakat.\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:62
msgid "If you want to allow ftpd to write to cifs file systems"
msgstr ""

#: ../src/allow_ftpd_use_cifs.py:63 ../src/allow_ftpd_use_nfs.py:65
msgid "you must tell SELinux about this"
msgstr "el kell mondania SELinuxról ezt"

#: ../src/allow_ftpd_use_nfs.py:29
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a NFS "
"filesystem.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta az ftp daemon számára, hogy hozzáféren az NFS "
"fájlrendszerben  az $ACCESS fájlokhoz.\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:33
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a NFS "
"filesystem.\n"
"    NFS (Network Filesystem) is a network filesystem commonly used on Unix / "
"Linux\n"
"    systems.\n"
"\n"
"    The ftp daemon attempted to read one or more files or directories from\n"
"    a mounted filesystem of this type.  As NFS filesystems do not support\n"
"    fine-grained SELinux labeling, all files and directories in the\n"
"    filesystem will have the same security context.\n"
"\n"
"    If you have not configured the ftp daemon to read files from a NFS "
"filesystem\n"
"    this access attempt could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta, hogy az \"ftp\" szolgáltatás a következő\n"
"    módon hozzáférjen egy NFS-fájlrendszeren tárolt fájlokhoz:\n"
"    \"$ACCESS\". Az NFS (Network Filesystem, azaz hálózati fájlrendszer)\n"
"    egy olyan hálózati fájlrendszer, amely Unix- illetve\n"
"    Linux-rendszereken gyakran használatos.\n"
"\n"
"    Az \"ftp\" szolgáltatás megkísérelt olvasni egy vagy több olyan\n"
"    fájlt illetve mappát, amely ilyen típusú csatolt fájlrendszeren\n"
"    van. Az NFS-fájlrendszerek nem támogatják a nagy részletességű\n"
"    SELinux-címkézést, ezért a fájlrendszerben levő összes fájl és\n"
"    könyvtár ugyanazon biztonsági beállítás rendelkezik.\n"
"\n"
"    Ha Ön nem állította be az \"ftp\" szolgáltatást arra, hogy az\n"
"    fájlokat olvasson valamely NFS-fájlrendszerről, akkor ez a\n"
"    hozzáférési kísérlet behatolási próbálkozást is jelezhet.\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:47
msgid ""
"\n"
"    Changing the \"allow_ftpd_use_nfs\" boolean to true will allow this "
"access:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1.\"\n"
"    "
msgstr ""
"\n"
"    Az \"allow_ftpd_use_nfs\" logikai érték igazra való módosítása\n"
"    engedélyezi ezt a hozzáférést: \"setsebool -P allow_ftpd_use_nfs=1\".\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:54
msgid ""
" Changing the \"allow_ftpd_use_nfs\" and\n"
"    \"$WRITE_BOOLEAN\" booleans to true will allow this access:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1 $WRITE_BOOLEAN=1\".\n"
"    warning: setting the \"$WRITE_BOOLEAN\" boolean to true will\n"
"    allow the ftp daemon to write to all public content (files and\n"
"    directories with type public_content_t) in addition to writing to\n"
"    files and directories on NFS filesystems.  "
msgstr ""
"Az \"allow_ftpd_use_nfs\" és a(z) \"$WRITE_BOOLEAN\" logikai érték igazra\n"
"    való módosítása (\"setsebool -P allow_ftpd_use_nfs=1 $WRITE_BOOLEAN=1\")\n"
"    engedélyezi ezt a hozzáférést. Figyelmeztetés: a(z) \"$WRITE_BOOLEAN\"\n"
"    logikai érték igazra való módosítása engedélyezi az \"ftp\"\n"
"    szolgáltatás számára az összes nyilvános tartalom (a public_content_t\n"
"    típusú fájlok és könyvtárak) írását is azon felül, hogy írhatja az\n"
"    NFS-fájlrendszereken levő fájlokat és könyvtárakat.\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:64
msgid "If you want to allow ftpd to write to nfs file systems"
msgstr ""

#: ../src/associate.py:32 ../src/openvpn.py:31 ../src/public_content.py:27
#: ../src/qemu_blk_image.py:27 ../src/qemu_file_image.py:27
#: ../src/restorecon.py:51 ../src/restorecon_source.py:33
#: ../src/rsync_data.py:27 ../src/sshd_root.py:32
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access to $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza $SOURCE_PATH „$ACCESS” hozzáférését ehhez: "
"$TARGET_PATH.\n"
"    "

#: ../src/associate.py:37
#, python-format
msgid ""
"\n"
"You tried to place a type on a %s that is not a file type.  This is not "
"allowed, you must assigne a file type.  You can list all file types using "
"the seinfo command.\n"
"\n"
"seinfo -afile_type -x\n"
"\n"
"    "
msgstr ""
"\n"
"Megpróbált elhelyezni egy típust ezen: %s, ami nem egy fájltípus. Ez nem "
"megengedett, hozzá kell rendelnie a fájltípust. Ezt kilistázhatha a seinfo "
"parancs segítségével.\n"
"\n"
"execstack -s LIBRARY_PATH. "

#: ../src/associate.py:44
#, python-format
msgid ""
"If you want to change the label of $TARGET_PATH to %s, you are not allowed "
"to since it is not a valid file type."
msgstr ""

#: ../src/associate.py:49
msgid "you must pick a valid file label."
msgstr "választania kell egy érvényes fájl cimkét."

#: ../src/automount_exec_config.py:27
msgid ""
"\n"
"    SELinux is preventing the $SOURCE_PATH from executing potentially "
"mislabeled files $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta, hogy $SOURCE_PATH végrehajtsa $TARGET_PATH "
"elérési úzon lévő elcímkézett fájlokat.\n"
"    "

#: ../src/automount_exec_config.py:31
msgid ""
"\n"
"    SELinux has denied the $SOURCE_PATH from executing potentially\n"
"    mislabeled files $TARGET_PATH.  Automounter can be setup to execute\n"
"    configuration files. If $TARGET_PATH is an automount executable\n"
"    configuration file it needs to have a file label of bin_t.\n"
"    If automounter is trying to execute something that it is not supposed "
"to, this could indicate an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta, hogy $SOURCE_PATH elérési útról végrehajtsa\n"
"    $TARGET_PATH útban lévő elcímkézett fájlokat.  Az automounter\n"
"    beállítható úgy, hogy végrehajtson beállítási fájlokat.\n"
"    Ha $TARGET_PATH célon lévő alkalmazás egy automount program, akkor\n"
"    azt bin_t típusúnak kell címkézni. Ha az automounter megpróbál "
"végrehajtani valamit, amit nem\n"
"    volna szabad, akkor ez behatolás kísérletet jelezhet.\n"
"    "

#: ../src/automount_exec_config.py:39
msgid ""
"\n"
"    If you want to change the file context of $TARGET_PATH so that the "
"automounter can execute it you can execute \"chcon -t bin_t $TARGET_PATH\".  "
"If you want this to survive a relabel, you need to permanently change the "
"file context: execute  \"semanage fcontext -a -t bin_t '$FIX_TARGET_PATH'\".\n"
"    "
msgstr ""
"\n"
"    Ha szeretné úgy módosítani $TARGET_PATH fájl beállítását, hogy az "
"önműködő csatoló végrehajthassa azt, akkor használhatja a következő "
"parancsot: „chcon -t bin_t.$TARGET_PATH„”. Ha szeretné, hogy ez túléljen egy "
"újracímkézést, akkor maradandóan kell módosítania a fájl beállítását: hajtsa "
"végre a „semanage fcontext -a -t bin_t $TARGET_PATH” parancsot.\n"
"    "

#: ../src/bind_ports.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from binding to port $PORT_NUMBER.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta, hogy $SOURCE_PATH elfoglalja $PORT_NUMBER portot."
"\n"
"    "

#: ../src/bind_ports.py:31
#, python-format
msgid ""
"\n"
"    SELinux has denied the $SOURCE from binding to a network port "
"$PORT_NUMBER which does not have an SELinux type associated with it.\n"
"    If $SOURCE should be allowed to listen on $PORT_NUMBER, use the "
"<i>semanage</i> command to assign $PORT_NUMBER to a port type that "
"$SOURCE_TYPE can bind to (%s).\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to bind to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/bind_ports.py:38
#, python-format
msgid ""
"\n"
"    If you want to allow $SOURCE to bind to port $PORT_NUMBER, you can "
"execute \n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    \n"
"where PORT_TYPE is one of the following: %s.\n"
"\n"
"    \n"
"\n"
"If this system is running as an NIS Client, turning on the allow_ypbind "
"boolean may fix the problem.  setsebool -P allow_ypbind=1.\n"
"    "
msgstr ""
"\n"
"    Ha meg akarja engedni, hogy $SOURCE a $PORT_NUMBER. portot elfoglalja, "
"adja ki a <br>\n"
"    <b># semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER</b>\n"
"    <br>parancsot, ahol a PORT_TYPE egyike a következőknek: %s.\n"
"\n"
"    <br><br>Ha pedig ez a rendszer NIS ügyfél, az allow_ypbind igazra "
"állítása megjavíthatja a problémát:  setsebool -P allow_ypbind=1.\n"
"    "

#: ../src/bind_ports.py:47
msgid "If you want to allow $SOURCE_PATH to bind to network port $PORT_NUMBER"
msgstr ""

#: ../src/bind_ports.py:53 ../src/connect_ports.py:51
#, python-format
msgid ""
"# semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    where PORT_TYPE is one of the following: %s."
msgstr ""
"# semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    ahol a PORT_TYPE az egyik a következőkből: %s."

#: ../src/bind_ports.py:56 ../src/connect_ports.py:54
#, python-format
msgid "# semanage port -a -t %s -p %s $PORT_NUMBER"
msgstr "# semanage port -a -t %s -p %s $PORT_NUMBER"

#: ../src/catchall_boolean.py:32
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access on $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza $SOURCE_PATH „$ACCESS” hozzáférését $TARGET_PATH "
"helyre.\n"
"    "

#: ../src/catchall_boolean.py:36
msgid ""
"\n"
"\n"
"    SELinux denied access requested by $SOURCE. The current boolean\n"
"    settings do not allow this access.  If you have not setup $SOURCE to\n"
"    require this access this may signal an intrusion attempt. If you do "
"intend\n"
"    this access you need to change the booleans on this system to allow\n"
"    the access.\n"
"    "
msgstr ""

#: ../src/catchall_boolean.py:45
msgid ""
"\n"
"    Confined processes can be configured to run requiring different access, "
"SELinux provides booleans to allow you to turn on/off\n"
"    access as needed.\n"
"\n"
"    "
msgstr ""

#: ../src/catchall_boolean.py:62
#, python-format
msgid "If you want to %s"
msgstr ""

#: ../src/catchall_boolean.py:65
#, python-format
msgid "setsebool -P %s %s"
msgstr "setsebool -P %s %s"

#: ../src/catchall_boolean.py:68
#, python-format
msgid "You must tell SELinux about this by enabling the '%s' boolean.\n"
msgstr ""
"Adja meg az SELinux számára erről, azzal hogy engedélyezi a '%s' boolean-t."
"\n"

#: ../src/catchall_boolean.py:71
#, python-format
msgid "You can read '%s' man page for more details."
msgstr "Elolvashatja '%s' man oldalt a további részletekért."

#: ../src/catchall_labels.py:28
#, python-format
msgid ""
"\n"
"    SELinux has denied the $SOURCE access to potentially\n"
"    mislabeled files $TARGET_PATH.  This means that SELinux will not\n"
"    allow httpd to use these files. If httpd should be allowed this access "
"to these files you should change the file context to one of the following "
"types, %s.\n"
"    Many third party apps install html files\n"
"    in directories that SELinux policy cannot predict.  These directories\n"
"    have to be labeled with a file context which httpd can access.\n"
"    "
msgstr ""
"\n"
"    SELinux elutasította, hogy $SOURCE hozzáférjen $TARGET_PATH úton lévő "
"elcímkézett fájlokhoz. Ez azt jelenti, hogy SELinux nem fogja\n"
"    megengedni httpd-nek ezeknek a fájloknak a használatát. Ha httpd-nek el "
"kell\n"
"    érnie ezeket a fájlokat, akkor változatassa meg a fájlok beállítását a \n"
"    következő típusok egyikére: %s.\n"
"    Sok idegen alkalmazás telepít html fájlokat olyan mappákba,\n"
"    amiket az SELinux szabályzat nem tud előre jelezni. Ezeket a mappákat\n"
"    olyan beállítással kell felcímkézni, amihez a httpd hozzáférhet.\n"
"    "

#: ../src/catchall_labels.py:37
msgid "You need to change the label on $FIX_TARGET_PATH"
msgstr "Meg kell hogy változtassa a cimkét itt: $FIX_TARGET_PATH"

#: ../src/catchall_labels.py:40
#, python-format
msgid ""
"# semanage fcontext -a -t FILE_TYPE '$FIX_TARGET_PATH'\n"
"where FILE_TYPE is one of the following: %s.\n"
"Then execute:\n"
"restorecon -v '$FIX_TARGET_PATH'\n"
msgstr ""

#: ../src/catchall.py:29 ../src/chrome.py:29 ../src/mozplugger.py:29
#: ../src/mozplugger_remove.py:29
msgid "SELinux is preventing $SOURCE_PATH \"$ACCESS\" access."
msgstr "SELinux megakadályozta a $SOURCE_PATH \"$ACCESS\" hozzáférését."

#: ../src/catchall.py:31
msgid ""
"\n"
"\n"
"    SELinux denied access requested by $SOURCE. It is not\n"
"    expected that this access is required by $SOURCE and this access\n"
"    may signal an intrusion attempt. It is also possible that the specific\n"
"    version or configuration of the application is causing it to require\n"
"    additional access.\n"
"\n"
"    "
msgstr ""
"\n"
"\n"
"    SELinux elutasította a(z) $SOURCE által igényelt\n"
"    hozzáférést. Normál esetben a(z) $SOURCE nem igényli\n"
"    ezt a hozzáférést, ezért ez a hozzáférés egy behatolási próbálkozást\n"
"    is jelezhet. Az is elképzelhető, hogy az alkalmazás verziója vagy\n"
"    beállítása miatt van szükség további hozzáférésre.\n"
"\n"
"    "

#: ../src/catchall.py:41
msgid ""
"\n"
"    You can generate a local policy module to allow this\n"
"    access - see <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"\n"
"    Please file a bug report.\n"
"    "
msgstr ""
"\n"
"    Készíthet helyi szabályzat modult a hozzáférés engedélyezésére\n"
"    – lásd <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>.\n"
"\n"
"    Kérjük tegyen hibabejelentést.\n"
"    "

#: ../src/catchall.py:50
msgid ""
"If you believe that $SOURCE_BASE_PATH should be allowed $ACCESS access on "
"processes labeled $TARGET_TYPE by default."
msgstr ""

#: ../src/catchall.py:52
msgid ""
"If you believe that $SOURCE_BASE_PATH should have the $ACCESS capability by "
"default."
msgstr ""

#: ../src/catchall.py:53
msgid ""
"If you believe that $SOURCE_BASE_PATH should be allowed $ACCESS access on "
"the $TARGET_BASE_PATH $TARGET_CLASS by default."
msgstr ""

#: ../src/catchall.py:55
msgid ""
"You should report this as a bug.\n"
"You can generate a local policy module to allow this access."
msgstr ""
"Ezt jelentenie kell, mint hibát.\n"
"Hogy engedélyezze ezt a hozzáférést előállíthat egy helyi szabálymodult."

#: ../src/catchall.py:56
msgid ""
"Allow this access for now by executing:\n"
"# ausearch -c '$SOURCE' --raw | audit2allow -M my-$MODULE_NAME\n"
"# semodule -i my-$MODULE_NAME.pp"
msgstr ""

#: ../src/connect_ports.py:27 ../src/sandbox_connect.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from connecting to port $PORT_NUMBER.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza, hogy $SOURCE_PATH kapcsolódjon $PORT_NUMBER. "
"kapura.\n"
"    "

#: ../src/connect_ports.py:31
#, python-format
msgid ""
"\n"
"    SELinux has denied $SOURCE from connecting to a network port "
"$PORT_NUMBER which does not have an SELinux type associated with it.\n"
"    If $SOURCE should be allowed to connect on $PORT_NUMBER, use the "
"<i>semanage</i> command to assign $PORT_NUMBER to a port type that "
"$SOURCE_TYPE can connect to (%s).\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to connect to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/connect_ports.py:38
#, python-format
msgid ""
"\n"
"    If you want to allow $SOURCE to connect to $PORT_NUMBER, you can execute "
"\n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"\n"
"    where PORT_TYPE is one of the following: %s.\n"
"    "
msgstr ""
"\n"
"   Ha engedélyezni szeretné $SOURCE hogy kapcsolódhasson $PORT_NUMBER, "
"hajtsa végre a következőt: \n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"\n"
"    ahol PORT_TYPE az egyik a felsoroltak közül: %s.\n"
"    "

#: ../src/connect_ports.py:45 ../src/sandbox_connect.py:47
msgid ""
"If you want to allow $SOURCE_PATH to connect to network port $PORT_NUMBER"
msgstr ""

#: ../src/chrome.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not expected that this "
"access is required by $SOURCE and this access may signal an intrusion "
"attempt. It is also possible that the specific version or configuration of "
"the application is causing it to require additional access.  spice-xpi run "
"applications within mozilla-plugins that require access to the desktop, that "
"the mozilla_plugin lockdown will not allow, so either you need to turn off "
"the mozilla_plugin lockdown or not use these packages.\n"
"    "
msgstr ""

#: ../src/chrome.py:35
msgid ""
"\n"
"Either remove the mozplugger or spice-xpi package by executing 'yum remove "
"mozplugger spice-xpi', or turn off enforcement of SELinux over the Chrome "
"plugins. setsebool -P unconfined_chrome_sandbox_transition 0\n"
"    "
msgstr ""

#: ../src/chrome.py:38 ../src/mozplugger.py:38
#, python-format
msgid "If you want to use the %s package"
msgstr ""

#: ../src/chrome.py:43
msgid "you must turn off SELinux controls on the Chrome plugins."
msgstr "ki kell kapcsolnia az SELinux vezérléseit a Chrome pluginjaira."

#: ../src/cvs_data.py:27
msgid ""
"\n"
"    SELinux is preventing cvs ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza cvs ($SOURCE_PATH) „$ACCESS” hozzáférését "
"$TARGET_PATH helyre\n"
"    "

#: ../src/cvs_data.py:31
msgid ""
"\n"
"    SELinux denied cvs access to $TARGET_PATH.\n"
"    If this is a CVS repository it needs to have a file context label of\n"
"    cvs_data_t. If you did not intend to use $TARGET_PATH as a CVS "
"repository\n"
"    it could indicate either a bug or it could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux megtagadta cvs hozzáférését ehhez: $TARGET_PATH.\n"
"    Ha ez CVS tároló, akkor cvs_data_t beállítású címkét igényel.\n"
"    Ha nincs szándékában $TARGET_PATH helyet CVS tárolónak használni,\n"
"    akkor ez hibát vagy behatolási kísérletet jelezhet.\n"
"    "

#: ../src/cvs_data.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t cvs_data_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"cvs_data_t '$FIX_TARGET_PATH'\"\n"
"    \n"
"    "
msgstr ""
"\n"
"    Megváltoztathatja a fájl beállítást a chcon -R -t cvs_data_t "
"'$TARGET_PATH' parancs végrehajtásával.\n"
"    Az alapértelmezett fájl beállítást szintén változtassa meg, hogy a "
"változás maradandó legyen még teljes újracímkézés után is.  „semanage "
"fcontext -a -t cvs_data_t '$FIX_TARGET_PATH'”\n"
"    \n"
"    "

#: ../src/cvs_data.py:44
msgid "If $TARGET_BASE_PATH should be shared via the cvs daemon"
msgstr ""

#: ../src/cvs_data.py:45 ../src/qemu_file_image.py:49
msgid "You need to change the label on $TARGET_BASE_PATH'"
msgstr "Meg kell változtatnia a cimkét itt: $TARGET_BASE_PATH'"

#: ../src/dac_override.py:28
msgid "\n"
"    SELinux is preventing $SOURCE_PATH the \"$ACCESS\" capability.\n"
"    "
msgstr ""

#: ../src/dac_override.py:32
msgid ""
"\n"
"\tdac_override and dac_read_search capabilities usually indicates that the "
"root process does not have access to a file based on the permission flags.  "
"This usually mean you have some file with the wrong ownership/permissions on "
"it.\n"
"    "
msgstr ""
"\n"
"\tdac_override és dac_read_search képességek általában azt jelzik, hogy a "
"root folyamatnak nincs hozzáférése ahhoz a más engedélyekkel rendelkező "
"fájlhoz. Ez azt jelenti, hogy valami probléma van annak a fájlnak a rosszul "
"beállított tulajdonosi/engedélyeivel.  "

#: ../src/dac_override.py:38
msgid ""
"If you want to help identify if domain needs this access or you have a file "
"with the wrong permissions on your system"
msgstr ""

#: ../src/dac_override.py:39
msgid ""
"turn on full auditing to get path information about the offending file and "
"generate the error again."
msgstr ""
"kapcsolja be a teljes auditálást hogy a teljes elérési utat megkapja a "
"zavaró fájl kapcsán és készítsen másik hibaüzenetet újra."

#: ../src/dac_override.py:40
msgid ""
"\n"
"Turn on full auditing\n"
"# auditctl -w /etc/shadow -p w\n"
"Try to recreate AVC. Then execute\n"
"# ausearch -m avc -ts recent\n"
"If you see PATH record check ownership/permissions on file, and fix it,\n"
"otherwise report as a bugzilla."
msgstr ""

#: ../src/device.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access to device "
"$TARGET_PATH.\n"
"    "
msgstr ""

#: ../src/device.py:33
msgid ""
"\n"
"\n"
"    SELinux has denied $SOURCE \"$ACCESS\" access to device $TARGET_PATH.\n"
"    $TARGET_PATH is mislabeled, this device has the default label of the /"
"dev directory, which should not\n"
"    happen.  All Character and/or Block Devices should have a label.\n"
"\n"
"    You can attempt to change the label of the file using\n"
"\n"
"    restorecon -v '$TARGET_PATH'.\n"
"\n"
"    If this device remains labeled device_t, then this is a bug in SELinux "
"policy.\n"
"\n"
"    Please file a bg report.\n"
"\n"
"    If you look at the other similar devices labels, ls -lZ /dev/SIMILAR, "
"and find a type that would work for $TARGET_PATH,\n"
"    you can use chcon -t SIMILAR_TYPE '$TARGET_PATH', If this fixes the "
"problem, you can make this permanent by executing\n"
"    semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"\n"
"    If the restorecon changes the context, this indicates that the "
"application that created the device, created it without\n"
"    using SELinux APIs.  If you can figure out which application created the "
"device, please file a bug report against this application.\n"
"\n"
"    "
msgstr ""

#: ../src/device.py:56
msgid ""
"\n"
"    Attempt restorecon -v '$TARGET_PATH' or chcon -t SIMILAR_TYPE "
"'$TARGET_PATH'\n"
"    "
msgstr ""
"\n"
"    Próbálja meg a restorecon -v '$TARGET_PATH' vagy a chcon -t "
"HASONLÓ_TÍPUS '$TARGET_PATH' parancsot.\n"
"    "

#: ../src/device.py:60
msgid ""
"You need to change the label on $TARGET_PATH to a type of a similar device."
msgstr ""
"Meg kell változtatnia a cimkét a $TARGET_PATH a hasonló típusú eszközért."

#: ../src/device.py:61
msgid ""
"# semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"

#: ../src/disable_ipv6.py:30
msgid "\n"
"Disable IPV6 properly.\n"
"    "
msgstr "\n"
"Iktassa ki az IPV6 protokollt helyesen.\n"
"    "

#: ../src/disable_ipv6.py:40
msgid "If you want to disable IPV6 on this machine"
msgstr ""

#: ../src/disable_ipv6.py:41
msgid ""
"you need to set /proc/sys/net/ipv6/conf/all/disable_ipv6 to 1 and do not "
"blacklist the module'"
msgstr ""
"be kell állítani a /proc/sys/net/ipv6/conf/all/disable_ipv6 modult 1-esre és "
"ne tegye blacklist-re azt."

#: ../src/disable_ipv6.py:42
msgid "Add \n"
"net.ipv6.conf.all.disable_ipv6 = 1\n"
"to /etc/sysctl.conf\n"
msgstr ""
"Adja a  \n"
"net.ipv6.conf.all.disable_ipv6 = 1\n"
"a /etc/sysctl.conf fájlhoz\n"

#: ../src/file.py:27
msgid ""
"\n"
"    SELinux is preventing access to files with the label, file_t.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza a file_t címkéjű fájlokhoz való hozzáférést.\n"
"    "

#: ../src/file.py:31
msgid ""
"\n"
"    SELinux permission checks on files labeled file_t are being\n"
"    denied.  file_t is the context the SELinux kernel gives to files\n"
"    that do not have a label. This indicates a serious labeling\n"
"    problem. No files on an SELinux box should ever be labeled file_t.\n"
"    If you have just added a disk drive to the system you can\n"
"    relabel it using the restorecon command.  For example if you saved the\n"
"home directory from a previous installation that did not use SELinux, "
"'restorecon -R -v /home' will fix the labels.  Otherwise you should\n"
"    relabel the entire file system.\n"
"    "
msgstr ""
"\n"
"    A file_t címkéjű fájlok engedély ellenőrzését SELinux elutasítja.\n"
"    SELinux-kernelnek a címke nélküli fájlok beállítása file_t.\n"
"    Ez komoly címkézés problémát jelez. SELinux rendszerben\n"
"    egy fájlnak sem kellene file_t címkét kapnia.\n"
"    Ha éppen új lemezegységet adott hozzá a rendszerhez,\n"
"    újracímkézheti a „restorecon” paranccsal. Például\n"
"    ha a saját mappáját egy korábbi SELinux nélküli rendszerben\n"
"    mentette el, akkor „restorecon -R -v /home” a megoldás.\n"
"    Különben címkézze újra az egész fájlrendszert.\n"
"    "

#: ../src/file.py:42
msgid ""
"\n"
"    You can execute the following command as root to relabel your\n"
"    computer system: \"touch /.autorelabel; reboot\"\n"
"    "
msgstr ""
"\n"
"    A számítógépes rendszer újracímkézése a következő paranccsal\n"
"    végezhető el: \"touch /.autorelabel; reboot\" (rendszergazdai\n"
"    jogosultságot igényel).\n"
"    "

#: ../src/file.py:49
msgid "This is caused by a newly created file system."
msgstr ""

#: ../src/file.py:51
msgid "If you think this is caused by a badly mislabeled machine."
msgstr ""

#: ../src/file.py:55
msgid "you need to add labels to it."
msgstr "cimkéket kell hozzáadnia"

#: ../src/file.py:57
msgid "you need to fully relabel."
msgstr "teljesen újra kell cimkéznie"

#: ../src/filesystem_associate.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from creating a file with a context "
"of $SOURCE_TYPE on a filesystem.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza, hogy $SOURCE_PATH egy $SOURCE_TYPE\n"
"    beállítással fájlt készítsen egy fájlrendszerben.\n"
"    "

#: ../src/filesystem_associate.py:31
msgid ""
"\n"
"    SELinux is preventing $SOURCE from creating a file with a context of "
"$SOURCE_TYPE on a filesystem.\n"
"    Usually this happens when you ask the cp command to maintain the context "
"of a file when\n"
"    copying between file systems, \"cp -a\" for example.  Not all file "
"contexts should be maintained\n"
"    between the file systems.  For example, a read-only file type like "
"iso9660_t should not be placed\n"
"    on a r/w system.  \"cp -p\" might be a better solution, as this will "
"adopt the default file context\n"
"    for the destination.\n"
"    "
msgstr ""

#: ../src/filesystem_associate.py:40
msgid ""
"\n"
"    Use a command like \"cp -p\" to preserve all permissions except SELinux "
"context.\n"
"    "
msgstr ""
"\n"
"    Ha az SELinux beállításon kívül minden engedélyt meg szeretne tartani,\n"
"    akkor használja a „cp -p” parancsot.\n"
"    "

#: ../src/filesystem_associate.py:43
msgid ""
"If you believe $SOURCE_BASE_PATH should be allowed to create "
"$TARGET_BASE_PATH files"
msgstr ""

#: ../src/filesystem_associate.py:44
msgid ""
"you need to use a different command. You are not allowed to preserve the "
"SELinux context on the target file system."
msgstr ""
"másik parancsot kell alkalmaznia. Nincs jogosultsága hogy megtartsa az "
"SELinux beállításait a cél fájlrendszerében."

#: ../src/filesystem_associate.py:46
msgid ""
"use a command like \"cp -p\" to preserve all permissions except SELinux "
"context."
msgstr ""
"Ha a SELinux beállításon kívül minden engedélyt meg szeretne tartani, akkor "
"használja a „cp -p” parancsot."

#: ../src/httpd_can_sendmail.py:28
msgid "\n"
"    SELinux is preventing the http daemon from sending mail.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza, hogy a httpd szolgáltatás levelet küldjön.\n"
"    "

#: ../src/httpd_can_sendmail.py:32
msgid ""
"\n"
"    SELinux has denied the http daemon from sending mail. An\n"
"    httpd script is trying to connect to a mail port or execute the\n"
"    sendmail command. If you did not setup httpd to sendmail, this could\n"
"    signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/httpd_can_sendmail.py:39
msgid ""
"\n"
"    If you want httpd to send mail you need to turn on the\n"
"    $BOOLEAN boolean: \"setsebool -P\n"
"    $BOOLEAN=1\"\n"
"    "
msgstr ""
"\n"
"    Ha azt szeretné, hogy a httpd levelet küldjön, akkor be kell\n"
"    kapcsolnia $BOOLEAN logikai értéket:\n"
"    „setsebool -P $BOOLEAN=1”.\n"
"    "

#: ../src/httpd_can_sendmail.py:47
msgid "If you want to allow httpd to send mail"
msgstr ""

#: ../src/httpd_can_sendmail.py:48
msgid "you must setup SELinux to allow this"
msgstr "be kell állítania az SELinux-ot hogy lehetővé tegye"

#: ../src/httpd_unified.py:29
msgid "\n"
"    SELinux prevented httpd $ACCESS access to http files.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta httpd $ACCESS hozzáférését http fájlokhoz.\n"
"    "

#: ../src/httpd_unified.py:33
msgid ""
"\n"
"    SELinux prevented httpd $ACCESS access to http files.\n"
"\n"
"    Ordinarily httpd is allowed full access to all files labeled with http "
"file\n"
"    context.  This machine has a tightened security policy with the $BOOLEAN\n"
"    turned off,  This requires explicit labeling of all files.  If a file is\n"
"    a cgi script it needs to be labeled with httpd_TYPE_script_exec_t in "
"order\n"
"    to be executed.  If it is read only content, it needs to be labeled\n"
"    httpd_TYPE_content_t, it is writable content. it needs to be labeled\n"
"    httpd_TYPE_script_rw_t or httpd_TYPE_script_ra_t. You can use the\n"
"    chcon command to change these context.  Please refer to the man page\n"
"    \"man httpd_selinux\" or\n"
"    <a href=\"http://fedora.redhat.com/docs/selinux-apache-fc3\">FAQ</a>\n"
"    \"TYPE\" refers to one of \"sys\", \"user\" or \"staff\" or potentially "
"other\n"
"    script types.\n"
"    "
msgstr ""

#: ../src/httpd_unified.py:50
msgid ""
"\n"
"    Changing the \"$BOOLEAN\" boolean to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1\"\n"
"    "
msgstr ""
"\n"
"    „$BOOLEAN” logikai érték igazra állítása engedélyezi e hozzáférést:\n"
"    „setsebool -P $BOOLEAN=1”\n"
"    "

#: ../src/httpd_unified.py:57
msgid ""
"If you want to allow httpd to execute cgi scripts and to unify HTTPD "
"handling of all content files."
msgstr ""

#: ../src/httpd_unified.py:58
msgid ""
"you must tell SELinux about this by enabling the 'httpd_unified' and "
"'http_enable_cgi' booleans"
msgstr ""
"meg kell adnia az SELinux számára erről, hogy engedélyezi a  'httpd_unified' "
"és 'http_enable_cgi' boolean-okat"

#: ../src/httpd_write_content.py:30
msgid ""
"\n"
"    SELinux prevented httpd $ACCESS access to $TARGET_PATH.\n"
"\n"
"    httpd scripts are not allowed to write to content without explicit\n"
"    labeling of all files.  If $TARGET_PATH is writable content. it needs\n"
"    to be labeled httpd_sys_rw_content_t or if all you need is append you "
"can label it httpd_sys_ra_content_t.   Please refer to 'man httpd_selinux' "
"for more information on setting up httpd and selinux.\n"
"    "
msgstr ""

#: ../src/httpd_write_content.py:40 ../src/qemu_blk_image.py:45
#: ../src/samba_share.py:45 ../src/swapfile.py:45 ../src/xen_image.py:48
msgid "You need to change the label on '$FIX_TARGET_PATH'"
msgstr "Meg kell változtatnia a cimkét itt: '$FIX_TARGET_PATH'"

#: ../src/kernel_modules.py:29
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to modify "
"kernel configuration.\n"
"    "
msgstr ""
"\n"
"    A rendszer komolyan sérülhetett! $SOURCE_PATH rendszermag beállítást "
"próbált meg megváltoztatni.\n"
"    "

#: ../src/kernel_modules.py:33
msgid ""
"\n"
"    SELinux has prevented $SOURCE from modifying $TARGET.  This denial\n"
"    indicates $SOURCE was trying to modify the way the kernel runs or to\n"
"    actually insert code into the kernel. All applications that need this\n"
"    access should have already had policy written for them.  If a "
"compromised\n"
"    application tries to modify the kernel this AVC will be generated. This "
"is a\n"
"    serious issue. Your system may very well be compromised.\n"
"    "
msgstr ""

#: ../src/kernel_modules.py:44 ../src/selinuxpolicy.py:44
msgid ""
"If you do not think $SOURCE_BASE_PATH should try $ACCESS access on "
"$TARGET_BASE_PATH."
msgstr ""

#: ../src/kernel_modules.py:45 ../src/selinuxpolicy.py:45
msgid ""
"you may be under attack by a hacker, since confined applications should not "
"need this access."
msgstr ""
"úgy tűnik támadás alatt lehet a gépe, mivel a szabályozott alkalmazásoknak "
"nem szabad szüksége lennie ilyen hozzáférésre."

#: ../src/leaks.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH access to a leaked $TARGET_PATH file "
"descriptor.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza, hogy $SOURCE_PATH hozzáférjen $TARGET_PATH "
"fájleíróhoz.\n"
"    "

#: ../src/leaks.py:31
msgid ""
"\n"
"    SELinux denied access requested by the $SOURCE command. It looks like "
"this is either a leaked descriptor or $SOURCE output was redirected to a "
"file it is not allowed to access.  Leaks usually can be ignored since "
"SELinux is just closing the leak and reporting the error.  The application "
"does not use the descriptor, so it will run properly.  If this is a "
"redirection, you will not get output in the $TARGET_PATH.  You should "
"generate a bugzilla on selinux-policy, and it will get routed to the "
"appropriate package.  You can safely ignore this avc.\n"
"    "
msgstr ""
"\n"
"    SELinux megtagadta a hozzáférést, amit $SOURCE parancs kért. Úgy tűnik "
"ez vagy egy szivárgó leíró vagy $SOURCE kimenetét olyan fájlba irányították, "
"amire nem terjed ki a jogköre.  Szivárgásokat szokás szerint figyelmen kívül "
"hagyhatják, mivel SELinux lezárja azt, és jelenti a hibát.  Az alkalmazás "
"nem használja a leírót, így az jól fog futni.  Ha ez egy átirányítás, akkor "
"nem fog megjelenni $TARGET_PATH kimenete.  Készítsen egy bugzilla jelentést "
"az selinux-policy alkalmazásra, és azt a megfelelő csomaghoz továbbítják "
"majd.  Nyugodtan figyelmen kívül hagyhatja ezt az üzenetet.\n"
"    "

#: ../src/leaks.py:35
msgid ""
"\n"
"    You can generate a local policy module to allow this\n"
"    access - see <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"    "
msgstr ""
"\n"
"    Készíthet helyi szabályzatot, hogy megengedi-e ezt a hozzáférést\n"
"    – lásd <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"    "

#: ../src/leaks.py:42
msgid ""
"If you want to ignore $SOURCE_BASE_PATH trying to $ACCESS access the "
"$TARGET_BASE_PATH $TARGET_CLASS, because you believe it should not need this "
"access."
msgstr ""

#: ../src/leaks.py:43
msgid ""
"You should report this as a bug.  \n"
"You can generate a local policy module to dontaudit this access."
msgstr ""
"Jeletse ezt hibaként. \n"
"Előállíthatja a helyi szabályzat modult hogy ne auditálja ezt a hozzáférést."

#: ../src/leaks.py:44
msgid ""
"# ausearch -x $SOURCE_PATH --raw | audit2allow -D -M my-$SOURCE\n"
"# semodule -i my-$SOURCE.pp"
msgstr ""

#: ../src/mmap_zero.py:29
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH attempted to mmap "
"low kernel memory.\n"
"    "
msgstr ""
"\n"
"    A rendszer komolyan megsérülhetett! $SOURCE_PATH alacsony rendszermag "
"memórián próbált meg mmap műveletet végrehajtani.\n"
"    "

#: ../src/mmap_zero.py:33
msgid ""
"\n"
"    SELinux has denied the $SOURCE the ability to mmap low area of the "
"kernel \n"
"    address space.  The ability to mmap a low area of the address space is \n"
"    configured by /proc/sys/kernel/mmap_min_addr.  Preventing such mappings \n"
"    helps protect against exploiting null deref bugs in the kernel. All \n"
"    applications that need this access should have already had policy "
"written \n"
"    for them.  If a compromised application tries to modify the kernel, this "
"AVC \n"
"    would be generated. This is a serious issue. Your system may very well "
"be \n"
"    compromised.\n"
"    "
msgstr ""

#: ../src/mmap_zero.py:46
msgid ""
"If you do not think $SOURCE_PATH should need to mmap low memory in the "
"kernel."
msgstr ""

#: ../src/mmap_zero.py:47
msgid "you may be under attack by a hacker, this is a very dangerous access."
msgstr "támadás alatt lehet a gépe, mivel ez egy igen veszélyes hozzáférés."

#: ../src/mounton.py:29
msgid ""
"\n"
"    SELinux prevented $SOURCE from mounting on the file or directory\n"
"    \"$TARGET_PATH\" (type \"$TARGET_TYPE\").\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta, hogy a(z) $SOURCE fájlrendszer-csatolást\n"
"    végezzen ezen a fájlon vagy könyvtáron: \"$TARGET_PATH\" (típus:\n"
"    \"$TARGET_TYPE\").\n"
"    "

#: ../src/mounton.py:34
msgid ""
"\n"
"    SELinux prevented $SOURCE from mounting a filesystem on the file\n"
"    or directory \"$TARGET_PATH\" of type \"$TARGET_TYPE\". By default\n"
"    SELinux limits the mounting of filesystems to only some files or\n"
"    directories (those with types that have the mountpoint attribute). The\n"
"    type \"$TARGET_TYPE\" does not have this attribute. You can change the\n"
"    label of the file or directory.\n"
"    "
msgstr ""

#: ../src/mounton.py:43
msgid ""
"\n"
"    Changing the file_context to mnt_t will allow mount to mount the file "
"system:\n"
"    \"chcon -t mnt_t '$TARGET_PATH'.\"\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"mnt_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    A fájl beállítás megváltozatatása mnt_t típusúra megengedi mountnak, "
"hogy\n"
"    becsatoljon egy fájlrendszert: „chcon -t mnt_t '$TARGET_PATH'”.\n"
"    Az alapértelmezett fájl beállítást is meg kell változtatni a "
"rendszerben, hogy a teljes újracímkézés se rontsa el a beállítást: „semanage "
"fcontext -a -t mnt_t '$FIX_TARGET_PATH'”\n"
"    "

#: ../src/mounton.py:48
msgid "If you want to allow $SOURCE_BASE_PATH to mount on $TARGET_BASE_PATH."
msgstr ""

#: ../src/mounton.py:49
msgid "you must change the labeling on $TARGET_PATH."
msgstr "meg kell változtatnia a cimkézést itt: $TARGET_PATH."

#: ../src/mozplugger.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not expected that this "
"access is required by $SOURCE and this access may signal an intrusion "
"attempt. It is also possible that the specific version or configuration of "
"the application is causing it to require additional access.  mozplugger and "
"spice-xpi run applications within mozilla-plugins that require access to the "
"desktop, that the mozilla_plugin lockdown will not allow, so either you need "
"to turn off the mozilla_plugin lockdown or not use these packages.\n"
"    "
msgstr ""

#: ../src/mozplugger.py:35
msgid ""
"\n"
"Either remove the mozplugger or spice-xpi package by executing 'yum remove "
"mozplugger spice-xpi' or turn off enforcement of SELinux over the Firefox "
"plugins. setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "
msgstr ""

#: ../src/mozplugger.py:43
msgid "you must turn off SELinux controls on the Firefox plugins."
msgstr "ki kell kapcsolnia az SELinux vezérléseit a Firefox pluginjain."

#: ../src/mozplugger_remove.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not\n"
"    expected that this access is required by $SOURCE and this access\n"
"    may signal an intrusion attempt. It is also possible that the specific\n"
"    version or configuration of the application is causing it to require\n"
"    additional access.\n"
"    "
msgstr ""
"\n"
"SELinux megtagadta a hozzáférést $SOURCE forrás alapján. Ha ez nem volt "
"várható\n"
"hogy a hozzáférésre lesz szüksége a $SOURCE számára,\n"
"előfordulhat hogy ez egy jel a betörési kísérletre. Az is előfordulhat, hogy\n"
"egy specifikus verzió vagy összeállítása az alkalmazásnak okozza ezt, és "
"további \n"
"jogosultságokat igényel."

#: ../src/mozplugger_remove.py:39
msgid ""
"\n"
"Either remove the mozplluger package by executing 'yum remove mozplugger'\n"
"Or turn off enforcement of SELinux over the Firefox plugins.\n"
"setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "
msgstr ""
"\n"
"Akár eltávolítja a mozplugger csomagot a  'yum remove mozplugger' paranccsal\n"
"vagy kikapcsolja az SELinuxvezérlését a Firefoxon pluginokon keresztül.\n"
"setsebool -P unconfined_mozilla_plugin_transition 0"

#: ../src/mozplugger_remove.py:44
msgid ""
"If you want to to continue using SELinux Firefox plugin containment rather "
"then using mozplugger package"
msgstr ""

#: ../src/mozplugger_remove.py:45
msgid "you must remove the mozplugger package."
msgstr "el kell távolítania a mozplugger csomagot."

#: ../src/openvpn.py:35
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled. openvpn is allowed to read content in home directory if "
"it\n"
"    is labeled correctly.\n"
"    "
msgstr ""

#: ../src/openvpn.py:41
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  \n"
"    # restorecon -R /root/.ssh\n"
"    "
msgstr ""

#: ../src/openvpn.py:49
msgid ""
"If you want to mv $TARGET_BASE_PATH to standard location so that "
"$SOURCE_BASE_PATH can have $ACCESS access"
msgstr ""

#: ../src/openvpn.py:51
msgid ""
"If you want to modify the label on $TARGET_BASE_PATH so that "
"$SOURCE_BASE_PATH can have $ACCESS access on it"
msgstr ""

#: ../src/openvpn.py:55
msgid "you must move the cert file to the ~/.cert directory"
msgstr "el kell mozgatnia a cert fájlt a ~/.cert mappába"

#: ../src/openvpn.py:57 ../src/sshd_root.py:48
msgid "you must fix the labels."
msgstr "ki kell javítania a cimkéket."

#: ../src/public_content.py:31
msgid ""
"\n"
"    SELinux denied access to $TARGET_PATH requested by $SOURCE.\n"
"    $TARGET_PATH has a context used for sharing by a different program. If "
"you\n"
"    would like to share $TARGET_PATH from $SOURCE also, you need to\n"
"    change its file context to public_content_t.  If you did not intend to\n"
"    allow this access, this could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux elutasította $SOURCE által igényelt hozzáférést $TARGET_PATH\n"
"    helyre. $TARGET_PATH beállítását más program megosztásra használja.\n"
"    Ha szeretné megosztani $TARGET_PATH fájlt $SOURCE programból is,\n"
"    akkor változtassa a fájl beállítását public_content_t típusúra.\n"
"    Ha nem akart ilyen hozzáférést megengedni, akkor\n"
"    ez behatolási próbálkozást is jelezhet.\n"
"    "

#: ../src/public_content.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -t public_content_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"public_content_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    A fájl beállítását a chcon -t public_content_t '$TARGET_PATH' parancs "
"végrehajtásával lehet megváltoztatni.\n"
"    Az alapértelmezett fájl beállítás fájlokat is meg kell változtatni, hogy "
"a teljes újracímkézés ne rontsa el a változásokat:\n"
"    semanage fcontext -a -t public_content_t '$FIX_TARGET_PATH'\n"
"    "

#: ../src/public_content.py:50
msgid "If you want to treat $TARGET_BASE_PATH as public content"
msgstr ""

#: ../src/public_content.py:51
msgid ""
"You need to change the label on $TARGET_BASE_PATH to public_content_t or "
"public_content_rw_t."
msgstr ""
"megváltoztathatja a cimkét ezen:  $TARGET_BASE_PATH  erre: public_content_t "
"vagy public_content_rw_t cimkéjűre."

#: ../src/qemu_blk_image.py:31
msgid ""
"\n"
"    SELinux denied qemu access to the block device $TARGET_PATH.\n"
"    If this is a virtualization image, it needs to be labeled with a "
"virtualization file context (virt_image_t). You can relabel $TARGET_PATH to "
"be virt_image_t using chcon.  You also need to execute semanage fcontext -a -"
"t virt_image_t '$FIX_TARGET_PATH' to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a qemu\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux elutasította, hogy qemu hozzáférjen $TARGET_PATH\n"
"    blokk eszközhöz. Ha ez egy virtuálizációs kép, akkor virtualizációs\n"
"    fájl beállítás címkére van szüksége (virt_image_t). Újracímkézheti\n"
"    $TARGET_PATH fájlt virt_image_t típusúra a chcon paranccsal.\n"
"    Szintén szüksége lesz az semanage fcontext -a -t virt_image_t "
"'$FIX_TARGET_PATH'\n"
"    parancsra kell ahhoz, hogy ezt az új hozzáférési utat a rendszer "
"alapértelmezésévé\n"
"    tegye. Ha nem akarja a $TARGET_PATH fájlt quemu képként használni,\n"
"    akkor ez jelezhet hibát illetve behatolás próbálkozást.\n"
"    "

#: ../src/qemu_blk_image.py:38 ../src/qemu_file_image.py:41
msgid ""
"\n"
"    You can alter the file context by executing chcon -t virt_image_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"virt_image_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    A fájl beállítását megváltoztatni a chcon -t virt_image_t '$TARGET_PATH' "
"parancs végrehajtásával lehet.\n"
"    Az alapértelmezett fájl beállítást szintén meg kell változtatni, hogy az "
"megmaradjon teljes újracímkézés esetén is: semanage fcontext -a -t "
"virt_image_t '$FIX_TARGET_PATH'\n"
"    "

#: ../src/qemu_blk_image.py:46
msgid ""
"# semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"

#: ../src/qemu_file_image.py:31
msgid ""
"\n"
"    SELinux denied qemu access to $TARGET_PATH.\n"
"    If this is a virtualization image, it has to have a file context label "
"of\n"
"    virt_image_t. The system is setup to label image files in directory./var/"
"lib/libvirt/images\n"
"    correctly.  We recommend that you copy your image file to /var/lib/"
"libvirt/images.\n"
"    If you really want to have your qemu image files in the current "
"directory, you can relabel $TARGET_PATH to be virt_image_t using chcon.  You "
"also need to execute semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH' "
"to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a qemu\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux elutasította, hogy qemu hozzáférjen $TARGET_PATH\n"
"    fájlhoz. Ha ez egy virtualizációs kép, akkor virt_image_t\n"
"    fájl beállítás címkéje kell legyen. A rendszert úgy állították\n"
"    be, hogy a /var/lib/libvirt/images mappában levő kép fájlokat\n"
"    helyesen címkézze. Javasoljuk, hogy másolja kép fájlt a\n"
"    /var/lib/libvirt/images mappába. Ha tényleg az aktuális\n"
"    mappában akarja tartani a qemu kép fájlokat, akkor címkézze\n"
"    fel a $TARGET_PATH mappát virt_image_t típusúra a chcon\n"
"    parancsot használva. Szintén az semanage fcontext -a -t virt_image_t "
"'$FIX_TARGET_PATH'\n"
"    parancs is szükséges, hogy ezt az új elérési utat hozzáadja a\n"
"    rendszer alapértelmezéseihez. Ha nem akartja a $TARGET_PATH\n"
"    fájlt qemu képként használni, akkor ez hibát vagy egy behatolás\n"
"    próbálkozást jelezhet.\n"
"    "

#: ../src/qemu_file_image.py:48
msgid "If $TARGET_BASE_PATH is a virtualization target"
msgstr ""

#: ../src/restorecon.py:57
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon '$TARGET_PATH', if this file is a "
"directory,\n"
"    you can recursively restore using restorecon -R '$TARGET_PATH'.\n"
"    "
msgstr ""
"\n"
"    Visszaállíthatja az alap beállítást e fájlra a restorecon parancs\n"
"    végrehajtásával.  restorecon '$TARGET_PATH', ha e fájl mappa,\n"
"    akkor rekurzívan is teheti: restorecon -R '$TARGET_PATH'.\n"
"    "

#: ../src/restorecon.py:64
#, python-format
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled.  $TARGET_PATH default SELinux type is\n"
"    <B>%s</B>, but its current type is <B>$TARGET_TYPE</B>. Changing\n"
"    this file back to the default type may fix your problem.\n"
"    <p>\n"
"    File contexts can be assigned to a file in the following ways.\n"
"    <ul>\n"
"        <li>Files created in a directory receive the file context of the "
"parent directory by default.\n"
"        <li>The SELinux policy might override the default label inherited "
"from the parent directory by\n"
"            specifying a process running in context A which creates a file "
"in a directory labeled B\n"
"            will instead create the file with label C. An example of this "
"would be the dhcp client running\n"
"            with the dhclient_t type and creating a file in the directory /"
"etc. This file would normally\n"
"            receive the etc_t type due to parental inheritance but instead "
"the file\n"
"            is labeled with the net_conf_t type because the SELinux policy "
"specifies this.\n"
"        <li>Users can change the file context on a file using tools such as "
"chcon, or restorecon.\n"
"    </ul>\n"
"    This file could have been mislabeled either by user error, or if an "
"normally confined application\n"
"    was run under the wrong domain.\n"
"    <p>\n"
"    However, this might also indicate a bug in SELinux because the file "
"should not have been labeled\n"
"    with this type.\n"
"    <p>\n"
"    If you believe this is a bug, please file a bug report against this "
"package.\n"
"    "
msgstr ""

#: ../src/restorecon.py:90
#, python-format
msgid ""
"If you want to fix the label. \n"
"$TARGET_PATH default label should be %s."
msgstr ""

#: ../src/restorecon.py:96
msgid ""
"you can run restorecon. The access attempt may have been stopped due to "
"insufficient permissions to access a parent directory in which case try to "
"change the following command accordingly."
msgstr ""

#: ../src/restorecon.py:105 ../src/restorecon_source.py:73
msgid "Restore\n"
"Context"
msgstr "Helyreállítja\n"
"Kontextust"

#: ../src/restorecon_source.py:39
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon '$SOURCE_PATH'.\n"
"    "
msgstr ""
"\n"
"    Visszaállíthatja az alap beállítást erre a rendszer kontextusra a "
"restorecon parancs\n"
"    végrehajtásával. A restorecon visszaállítás: 'restorecon '$SOURCE_PATH'."

#: ../src/restorecon_source.py:45
#, python-format
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $SOURCE_PATH may\n"
"    be mislabeled.  $SOURCE_PATH default SELinux type is\n"
"    <B>%s</B>, but its current type is <B>$SOURCE_TYPE</B>. Changing\n"
"    this file back to the default type may fix your problem.\n"
"    <p>\n"
"    This file could have been mislabeled either by user error, or if an "
"normally confined application\n"
"    was run under the wrong domain.\n"
"    <p>\n"
"    However, this might also indicate a bug in SELinux because the file "
"should not have been labeled\n"
"    with this type.\n"
"    <p>\n"
"    If you believe this is a bug, please file a bug report against this "
"package.\n"
"    "
msgstr ""

#: ../src/restorecon_source.py:60
#, python-format
msgid ""
"If you want to fix the label. \n"
"$SOURCE_PATH default label should be %s."
msgstr ""

#: ../src/restorecon_source.py:65
msgid "you can run restorecon."
msgstr "futtathatja a restorecon parancsot."

#: ../src/rsync_data.py:31
msgid ""
"\n"
"    SELinux denied RSYNC access to $TARGET_PATH.\n"
"    If this is an RSYNC repository, it has to have a file context label of\n"
"    rsync_data_t. If you did not intend to use $TARGET_PATH as an RSYNC "
"repository,\n"
"    this message could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/rsync_data.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t rsync_data_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"rsync_data_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    A fájl beállítását megváltoztatni a chcon -R -t rsync_data_t "
"'$TARGET_PATH' parancs végrehajtásával lehet.\n"
"    Az alapértelmezett fájl beállítást szintén meg kell változtatni, hogy az "
"megmaradjon teljes újracímkézés esetén is: semanage fcontext -a -t "
"rsync_data_t '$FIX_TARGET_PATH'\n"
"    "

#: ../src/rsync_data.py:45
msgid "If $TARGET_BASE_PATH should be shared via the RSYNC daemon"
msgstr ""

#: ../src/rsync_data.py:46
msgid "You need to change the label on $TARGET_BASE_PATH"
msgstr "Meg kell változtatnia a cimkét ezen: $TARGET_BASE_PATH"

#: ../src/samba_share.py:27
msgid ""
"\n"
"    SELinux is preventing Samba ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza Samba ($SOURCE_PATH) $ACCESS hozzáférését "
"$TARGET_PATH fájlhoz.\n"
"    "

#: ../src/samba_share.py:31
msgid ""
"\n"
"    SELinux denied samba access to $TARGET_PATH.\n"
"    If you want to share this directory with samba it has to have a file "
"context label of\n"
"    samba_share_t. If you did not intend to use $TARGET_PATH as a samba "
"repository,\n"
"    this message could indicate either a bug or an intrusion attempt.\n"
"    Please refer to 'man samba_selinux' for more information on setting up "
"Samba and SELinux.\n"
"    "
msgstr ""

#: ../src/samba_share.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t samba_share_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"samba_share_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    A fájl beállítását megváltoztatni a chcon -R -t samba_share_t "
"'$TARGET_PATH' parancs végrehajtásával lehet.\n"
"    Az alapértelmezett fájl beállítást szintén meg kell változtatni, hogy az "
"megmaradjon teljes újracímkézés esetén is: semanage fcontext -a -t "
"samba_share_t '$FIX_TARGET_PATH'\n"
"    "

#: ../src/samba_share.py:53
#, python-format
msgid ""
"# semanage fcontext -a -t samba_share_t '$FIX_TARGET_PATH%s'\n"
"# restorecon %s -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t samba_share_t '$FIX_TARGET_PATH%s'\n"
"# restorecon %s -v '$FIX_TARGET_PATH'"

#: ../src/sandbox_connect.py:33
msgid ""
"\n"
"    SELinux has denied $SOURCE from connecting to a network port "
"$PORT_NUMBER within a sandbox.\n"
"    If $SOURCE should be allowed to connect on $PORT_NUMBER, you need to use "
"a different sandbox type like sandbox_web_t or sandbox_net_t.  \n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to connect to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/sandbox_connect.py:41
msgid ""
"\n"
"    If you want to allow $SOURCE to connect to $PORT_NUMBER, you can execute "
"\n"
"\n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    "
msgstr ""
"\n"
"Ha engedélyezni szeretné $SOURCE számára, hogy csatlakozhasson a "
"$PORT_NUMBER számú porthoz, hajtsa végre a következőt:\n"
"\n"
"# sandbox -X -t sandbox_net_t $SOURCE"

#: ../src/sandbox_connect.py:49
msgid ""
"you need to modify the sandbox type. sandbox_web_t or sandbox_net_t.\n"
"For example:\n"
"sandbox -X -t sandbox_net_t $SOURCE_PATH\n"
"Please read 'sandbox' man page for more details.\n"
msgstr ""

#: ../src/selinuxpolicy.py:29
msgid "\n"
"    Your system may be seriously compromised!\n"
"    "
msgstr "\n"
"    A rendszer komoly veszélyben lehet!\n"
"    "

#: ../src/selinuxpolicy.py:33
msgid ""
"\n"
"    SELinux has prevented $SOURCE from modifying $TARGET.  This denial\n"
"    indicates $SOURCE was trying to modify the selinux policy configuration.\n"
"    All applications that need this access should have already had policy\n"
"    written for them.  If a compromised application tries to modify the "
"SELinux\n"
"    policy this AVC will be generated. This is a serious issue. Your system\n"
"    may very well be compromised.\n"
"    "
msgstr ""

#: ../src/setenforce.py:27
msgid "If you did not directly cause this AVC through testing."
msgstr ""

#: ../src/setenforce.py:28
msgid "if you think that you might have been hacked"
msgstr "ha úgy érzi hogy lehetséges, hogy feltörték"

#: ../src/setenforce.py:32
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to modify "
"SELinux enforcement.\n"
"    "
msgstr ""
"\n"
"    A rendszer komoly veszélyben lehet! $SOURCE_PATH megpróbálta "
"megváltoztatni a SELinux kényszerítést.\n"
"    "

#: ../src/setenforce.py:36
msgid ""
"\n"
"    SELinux has prevented $SOURCE from writing to a file under /sys/fs/"
"selinux.\n"
"    Files under /sys/fs/selinux control the way SELinux is configured.\n"
"    All programs that need to write to files under /sys/fs/selinux should "
"have already had policy\n"
"    written for them. If a compromised application tries to turn off SELinux\n"
"    this AVC will be generated. This is a serious issue. Your system may "
"very\n"
"    well be compromised.\n"
"    "
msgstr ""

#: ../src/setenforce.py:48
msgid "If you believe $SOURCE_PATH tried to disable SELinux."
msgstr ""

#: ../src/setenforce.py:49
msgid ""
"you may be under attack by a hacker, since confined applications should "
"never need this access."
msgstr ""
"előfordulhat hogy támadás alatt van, amióta egy szabályozott alkalmazásnak "
"nincs soha szüksége ilyen hozzáférésre."

#: ../src/sshd_root.py:36
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled. sshd is allowed to read content in /root/.ssh directory "
"if it\n"
"    is labeled correctly.\n"
"    "
msgstr ""

#: ../src/sshd_root.py:42
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.\n"
"    # restorecon -R /root/.ssh\n"
"    "
msgstr ""

#: ../src/sshd_root.py:55
msgid "Restore Context"
msgstr "Beállítás visszaállítása"

#: ../src/swapfile.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" to $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza $SOURCE_PATH „$ACCESS” hozzáférését $TARGET_PATH "
"fájlhoz.\n"
"    "

#: ../src/swapfile.py:31
msgid ""
"\n"
"    SELinux denied $SOURCE access to $TARGET_PATH.\n"
"    If this is a swapfile, it has to have a file context label of\n"
"    swapfile_t. If you did not intend to use\n"
"    $TARGET_PATH as a swapfile, this message could indicate either a bug or "
"an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/swapfile.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -t swapfile_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"swapfile_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    A fájl beállítását megváltoztatni a chcon -t swapfile_t '$TARGET_PATH' "
"parancs végrehajtásával lehet.\n"
"    Az alapértelmezett fájl beállítást szintén meg kell változtatni, hogy az "
"megmaradjon teljes újracímkézés esetén is: semanage fcontext -a -t "
"swapfile_t '$FIX_TARGET_PATH'\n"
"    "

#: ../src/sys_module.py:28
msgid ""
"If you do not believe your $SOURCE_PATH should be modifying the kernel, by "
"loading kernel modules"
msgstr ""

#: ../src/sys_module.py:29
msgid "You might have been hacked."
msgstr "Valószínűleg betörtek a gépére."

#: ../src/sys_module.py:33
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to load a "
"kernel module.\n"
"    "
msgstr ""
"\n"
"    A rendszer komoly veszélyben lehet! $SOURCE_PATH rendszermag modult "
"próbált betölteni.\n"
"    "

#: ../src/sys_module.py:37
msgid ""
"\n"
"    SELinux has prevented $SOURCE from loading a kernel module.\n"
"    All confined programs that need to load kernel modules should have "
"already had policy\n"
"    written for them. If a compromised application\n"
"    tries to modify the kernel this AVC will be generated. This is a serious\n"
"    issue. Your system may very well be compromised.\n"
"    "
msgstr ""

#: ../src/sys_module.py:46
msgid ""
"If you do not believe that $SOURCE_PATH should be attempting to modify the "
"kernel by loading a kernel module."
msgstr ""

#: ../src/sys_module.py:47
msgid "A process might be attempting to hack into your system."
msgstr "A folyamat valószínűleg betörési kísérlet a gépére."

#: ../src/sys_resource.py:28
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH the \"sys_resource\" capability.\n"
"    "
msgstr ""

#: ../src/sys_resource.py:32
msgid ""
"\n"
"    Confined domains should not require \"sys_resource\". This usually means "
"that     your system is running out some system resource like disk space, "
"memory, quota etc. Please clear up the disk and this\n"
"    AVC message should go away. If this AVC continues after you clear up the "
"disk space, please report this as a bug.\n"
"    "
msgstr ""

#: ../src/sys_resource.py:39
msgid ""
"If you do not want processes to require capabilities to use up all the "
"system resources on your system;"
msgstr ""

#: ../src/sys_resource.py:40
msgid ""
"you need to diagnose why your system is running out of system resources and "
"fix the problem.\n"
"\n"
"According to /usr/include/linux/capability.h, sys_resource is required to:\n"
"\n"
"/* Override resource limits. Set resource limits. */\n"
"/* Override quota limits. */\n"
"/* Override reserved space on ext2 filesystem */\n"
"/* Modify data journaling mode on ext3 filesystem (uses journaling\n"
"   resources) */\n"
"/* NOTE: ext2 honors fsuid when checking for resource overrides, so\n"
"   you can override using fsuid too */\n"
"/* Override size restrictions on IPC message queues */\n"
"/* Allow more than 64hz interrupts from the real-time clock */\n"
"/* Override max number of consoles on console allocation */\n"
"/* Override max number of keymaps */\n"
msgstr ""

#: ../src/vbetool.py:30
msgid ""
"\n"
"    SELinux has prevented vbetool from performing an unsafe memory operation."
"\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta, hogy vbetool nem biztonságos memóriaműveletet "
"végezzen.\n"
"    "

#: ../src/vbetool.py:34
msgid ""
"\n"
"SELinux denied an operation requested by $SOURCE, a program used\n"
"to alter video hardware state.  This program is known to use\n"
"an unsafe operation on system memory but so are a number of\n"
"malware/exploit programs which masquerade as vbetool.  This tool is used to\n"
"reset video state when a machine resumes from a suspend.  If your machine\n"
"is not resuming properly your only choice is to allow this\n"
"operation and reduce your system security against such malware.\n"
"\n"
"    "
msgstr ""

#: ../src/vbetool.py:45 ../src/wine.py:56
msgid ""
"\n"
"If you decide to continue to run the program in question you will need\n"
"to allow this operation.  This can be done on the command line by\n"
"executing:\n"
"\n"
"# setsebool -P mmap_low_allowed 1\n"
msgstr ""
"\n"
"Ha úgy dönt, hogy folytatja a kérdéses program futtatását, akkor \n"
"engedélyezze e műveletet.  Ezt teheti a parancssorból a következő\n"
"végrehajtásával:\n"
"\n"
"# setsebool -P mmap_low_allowed 1\n"

#: ../src/vbetool.py:55
msgid ""
"If you want to ignore this AVC because it is dangerous and your machine "
"seems to be working correctly."
msgstr ""

#: ../src/vbetool.py:56
msgid ""
"you must tell SELinux about this by enabling the vbetool_mmap_zero_ignore "
"boolean."
msgstr ""
"meg kell adnia az SELinux számára erről, azzal hogy engedélyezi a "
"vbetool_mmap_zero_ignore boolean-t."

#: ../src/vbetool.py:62 ../src/wine.py:73
msgid "Turn off memory protection"
msgstr "Kapcsolja ki a memória védelmet"

#: ../src/wine.py:31
msgid ""
"\n"
"    SELinux has prevented wine from performing an unsafe memory operation.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozta, hogy wine nem biztonságos memóriaműveletet "
"végezzen.\n"
"    "

#: ../src/wine.py:35
msgid ""
"\n"
"SELinux denied an operation requested by wine-preloader, a program used\n"
"to run Windows applications under Linux.  This program is known to use\n"
"an unsafe operation on system memory but so are a number of\n"
"malware/exploit programs which masquerade as wine.  If you were\n"
"attempting to run a Windows program your only choices are to allow this\n"
"operation and reduce your system security against such malware or to\n"
"refrain from running Windows applications under Linux.  If you were not\n"
"attempting to run a Windows application this indicates you are likely\n"
"being attacked by some for of malware or program trying to exploit your\n"
"system for nefarious purposes.\n"
"\n"
"Please refer to\n"
"\n"
"http://wiki.winehq.org/PreloaderPageZeroProblem\n"
"\n"
"Which outlines the other problems wine encounters due to its unsafe use\n"
"of memory and solutions to those problems.\n"
"\n"
"    "
msgstr ""

#: ../src/wine.py:66
msgid ""
"If you want to ignore this AVC because it is dangerous and your wine "
"applications are working correctly."
msgstr ""

#: ../src/wine.py:67
msgid ""
"you must tell SELinux about this by enabling the wine_mmap_zero_ignore "
"boolean."
msgstr ""
"ezt meg kell adnia az SELinux számára, azzal hogy engedélyezi a "
"wine_mmap_zero_ignore boolean-t"

#: ../src/xen_image.py:27
msgid ""
"\n"
"    SELinux is preventing xen ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux megakadályozza xen ($SOURCE_PATH) $ACCESS hozzáférését "
"$TARGET_PATH fájlhoz.\n"
"    "

#: ../src/xen_image.py:31
msgid ""
"\n"
"    SELinux denied xen access to $TARGET_PATH.\n"
"    If this is a XEN image, it has to have a file context label of\n"
"    xen_image_t. The system is setup to label image files in directory /var/"
"lib/xen/images\n"
"    correctly.  We recommend that you copy your image file to /var/lib/xen/"
"images.\n"
"    If you really want to have your xen image files in the current "
"directory, you can relabel $TARGET_PATH to be xen_image_t using chcon.  You "
"also need to execute semanage fcontext -a -t xen_image_t '$FIX_TARGET_PATH' "
"to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a xen\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux elutasította, hogy xen hozzáférjen $TARGET_PATH\n"
"    fájlhoz. Ha ez XEN kép, akkor xen_image_t fájl beállítás\n"
"    címke kell neki. A rendszert úgy állították be, hogy a /var/lib/xen/\n"
"    helyen levő kép fájlokat jól címkézze. Javasolt e könyvtárba másolni\n"
"    a kép fájlt. Ha valóban az aktuális mappába akarja tenni a xem kép "
"fájlokat, akkor $TARGET_PATH fájlt átcímkézheti xen_image_t típusra a chcon "
"paranccsal. A semanage fcontext -a -t xen_image_t '$FIX_TARGET_PATH' "
"végrehajtására szintén szükség lehet, hogy ezt az új ösvényt hozzáadja a "
"rendszer alapértelmezésihez.\n"
"    Ha nem akarta $TARGET_PATH fájlt Xen képként használni,\n"
"    akkor ez egy hibát vagy egy behatolás próbálkozást jelezhet.\n"
"    "

#: ../src/xen_image.py:41
msgid ""
"\n"
"    You can alter the file context by executing chcon -t xen_image_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"xen_image_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    A fájl beállítását megváltoztatni a chcon -t xen_image_t '$TARGET_PATH' "
"parancs végrehajtásával lehet.\n"
"    Az alapértelmezett fájl beállítást szintén meg kell változtatni, hogy az "
"megmaradjon teljes újracímkézés esetén is: semanage fcontext -a -t "
"xen_image_t '$FIX_TARGET_PATH'\n"
"    "
