# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Hajime Taira <htaira@redhat.com>, 2012
# hyuugabaru <hyu_gabaru@yahoo.co.jp>, 2009
# Kiyoto Hashida <khashida@redhat.com>, 2008-2012
# Kiyoto Hashida <khashida@redhat.com>, 2006, 2007
# noriko <noriko@fedoraproject.org>, 2013
# noriko <noriko@fedoraproject.org>, 2012
# Noriko Mizumoto <noriko@redhat.com>, 2006, 2008
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2012-2013
# Aiko Sasaki <asasaki@redhat.com>, 2016. #zanata
# Kenzo Moriguchi <kmoriguc@redhat.com>, 2016. #zanata
# Noriko Mizumoto <noriko@redhat.com>, 2016. #zanata
# Vit Mojzis <vmojzis@redhat.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-10-31 20:57+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2017-09-01 08:32-0400\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/fedora/language/"
"ja/)\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Zanata 3.9.6\n"

#: ../src/allow_anon_write.py:27
msgid ""
"\n"
"    SELinux policy is preventing an httpd script from writing to a public\n"
"    directory.\n"
"    "
msgstr "\n"
"SELinux ポリシーにより httpd スクリプトのパブリックディレクトリへの書き込むが\n"
"阻止されています。\n"
"     "

#: ../src/allow_anon_write.py:32
msgid ""
"\n"
"    SELinux policy is preventing an httpd script from writing to a public\n"
"    directory.  If httpd is not setup to write to public directories, this\n"
"    could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"SELinux ポリシーにより httpd スクリプトのパブリックディレクトリへの書き込みが\n"
"阻止されています。 httpd でパブリックディレクトリへの書き込み設定を行なって\n"
"いない場合、 セキュリティ侵害が行なわれた可能性があります。\n"
"    "

#: ../src/allow_anon_write.py:38
msgid ""
"\n"
"    If httpd scripts should be allowed to write to public directories you "
"need to turn on the $BOOLEAN boolean and change the file context of the "
"public directory to public_content_rw_t.  Read the httpd_selinux\n"
"    man page for further information:\n"
"    \"setsebool -P $BOOLEAN=1; chcon -t public_content_rw_t <path>\"\n"
"    You must also change the default file context labeling files on the "
"system in order to preserve public directory labeling even on a full relabel."
"  \"semanage fcontext -a -t public_content_rw_t <path>\"\n"
"    "
msgstr ""
"\n"
"httpd スクリプトによるパブリックディレクトリへの書き込みを許可する場合、 $BOOLEAN boolean "
"をオンにしてパブリックディレクトリのファイルコンテキストを public_content_rw_t に変更する必要があります。 詳細については "
"httpd_selinux の man ページをご覧ください:\n"
"\"setsebool -P $BOOLEAN=1; chcon -t public_content_rw_t<path>\"\n"
"また、 完全な再ラベル付けを行なった後もパブリックディレクトリのラベルを維持させたい場合は、 "
"システム上のデフォルトのファイルコンテキストラベル設定ファイルも変更する必要があります。 \"semanage fcontext -a -t "
"public_content_rw_t <path>\""

#: ../src/allow_anon_write.py:44
msgid ""
"If you want to allow $SOURCE_PATH to be able to write to shared public "
"content"
msgstr ""

#: ../src/allow_anon_write.py:45
msgid ""
"you need to change the label on $TARGET_PATH to public_content_rw_t, and "
"potentially turn on the allow_httpd_sys_script_anon_write boolean."
msgstr ""
"$TARGET_PATH のラベルを public_content_rw_t に変更する必要があります。 また、 "
"allow_httpd_sys_script_anon_write boolean を有効にする必要があるかもしれません。"

#: ../src/allow_execheap.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from changing the access\n"
"    protection of memory on the heap.\n"
"    "
msgstr ""
"\n"
"     SELinux は $SOURCE_PATH が ヒープのメモリーへのアクセス保護を\n"
"     変更することを阻止しています。\n"
"     "

#: ../src/allow_execheap.py:32
msgid ""
"\n"
"    The $SOURCE application attempted to change the access protection of "
"memory on\n"
"    the heap (e.g., allocated using malloc).  This is a potential security\n"
"    problem.  Applications should not be doing this. Applications are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  If $SOURCE does not "
"work and\n"
"    you need it to work, you can configure SELinux temporarily to allow\n"
"    this access until the application is fixed. Please file a bug\n"
"    report against this package.\n"
"    "
msgstr ""
"\n"
"    $SOURCE アプリケーションがヒープのメモリー (例えば malloc を使った割当て)\n"
"    のアクセス保護の変更を試行しました。セキュリティー上の問題となる可能性が\n"
"    あります。アプリケーションはこのような動作を行うべきではありません。\n"
"    アプリケーションは誤って記述されることがあり、 このパーミッションを要求\n"
"    することがあります。\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    のウェブページにはこの要求の削除方法が記載されています。 $SOURCE が動作しなくて\n"
"    動作させる必要がある場合、 アプリケーションが修正されるまでの間、 \n"
"    SELinux を設定して一時的にこのアクセスを許可することができます。 このパッケージ\n"
"    に関するバグレポートを提出してください。\n"
"    "

#: ../src/allow_execheap.py:44
msgid ""
"\n"
"    If you want $SOURCE to continue, you must turn on the\n"
"    $BOOLEAN boolean.  Note: This boolean will affect all applications\n"
"    on the system.\n"
"    "
msgstr ""
"\n"
"    $SOURCE を継続したい場合は、$BOOLEAN boolean をオンにする必要があり\n"
"    ます。 注記: この boolean はシステム上の全てのアプリケーションに影響\n"
"    します。\n"
"    "

#: ../src/allow_execheap.py:50
msgid ""
"If you do not think $SOURCE_PATH should need to map heap memory that is both "
"writable and executable."
msgstr ""

#: ../src/allow_execheap.py:51
msgid "you need to report a bug. This is a potentially dangerous access."
msgstr "バグをレポートする必要があります。これは危険なアクセスです。"

#: ../src/allow_execheap.py:52 ../src/allow_execstack.py:91
#: ../src/kernel_modules.py:46 ../src/mmap_zero.py:48
#: ../src/selinuxpolicy.py:46 ../src/setenforce.py:29 ../src/setenforce.py:50
#: ../src/sys_module.py:30 ../src/sys_module.py:48
msgid "Contact your security administrator and report this issue."
msgstr "セキュリティ管理者にコンタクトし、この問題を報告してください。"

#: ../src/allow_execmod.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from loading $TARGET_PATH which "
"requires text relocation.\n"
"    "
msgstr ""
"\n"
"    SELinux はテキスト再配置を要求する $TARGET_PATH を $SOURCE_PATH がロードすることを阻止しています。\n"
"    "

#: ../src/allow_execmod.py:33
msgid ""
"\n"
"    The $SOURCE application attempted to load $TARGET_PATH which\n"
"    requires text relocation.  This is a potential security problem.\n"
"    Most libraries do not need this permission. Libraries are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  You can configure\n"
"    SELinux temporarily to allow $TARGET_PATH to use relocation as a\n"
"    workaround, until the library is fixed. Please file a\n"
"bug report.\n"
"    "
msgstr ""
"\n"
"    $SOURCE アプリケーションは、テキスト移動を要求する $TARGET_PATH \n"
"    のロードを試行しました。 セキュリティー上の問題となる可能性があります。\n"
"    ほとんどのライブラリーはこの許可を必要としません。 ライブラリーは\n"
"    誤って記述されることがあり、 この許可を要求することがあります。\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    のウェブページにはこの要求の削除方法が記載されています。 ライブラリーが\n"
"    修正されるまでの間の回避策として SELinux を設定し一時的に $TARGET_PATH が\n"
"    移動を使用できるようにすることができます。 このパッケージに関するバグレポート\n"
"    を提出してください。\n"
"    "

#: ../src/allow_execmod.py:45
msgid ""
"\n"
"    The $SOURCE application attempted to load $TARGET_PATH which\n"
"    requires text relocation.  This is a potential security problem.\n"
"    Most libraries should not need this permission.   The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">\n"
"    SELinux Memory Protection Tests</a>\n"
"    web page explains this check.  This tool examined the library and it "
"looks\n"
"    like it was built correctly. So setroubleshoot can not determine if this\n"
"    application is compromised or not.  This could be a serious issue. Your\n"
"    system may very well be compromised.\n"
"\n"
"    Contact your security administrator and report this issue.\n"
"\n"
"    "
msgstr ""

#: ../src/allow_execmod.py:62
msgid ""
"\n"
"    If you trust $TARGET_PATH to run correctly, you can change the\n"
"    file context to textrel_shlib_t. \"chcon -t textrel_shlib_t\n"
"    '$TARGET_PATH'\"\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"textrel_shlib_t '$FIX_TARGET_PATH'\"\n"
"\n"
"    "
msgstr ""
"\n"
"    $TARGET_PATH が正しく実行することを信用できる場合は、ファイルコンテキストを \n"
"    textrel_shlib_t へ変更することができます。\"chcon -t textrel_shlib_t\n"
"     '$TARGET_PATH'\"\n"
"    "
"また、システム上のデフォルトファイルコンテキストのファイルを完全な再ラベルでも保持するようにそれらを変更しなければなりません。\"semanage "
"fcontext -a -t textrel_shlib_t '$FIX_TARGET_PATH'\"\n"
"    \n"
"    "

#: ../src/allow_execstack.py:60
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from making the program stack "
"executable.\n"
"    "
msgstr "\n"
"    SELinux は $SOURCE_PATH がプログラムスタックを実行可能にすることを阻止しています。\n"
"    "

#: ../src/allow_execstack.py:64
msgid ""
"\n"
"    The $SOURCE application attempted to make its stack\n"
"    executable.  This is a potential security problem.  This should\n"
"    never ever be necessary. Stack memory is not executable on most\n"
"    OSes these days and this will not change. Executable stack memory\n"
"    is one of the biggest security problems. An execstack error might\n"
"    in fact be most likely raised by malicious code. Applications are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  If $SOURCE does not\n"
"    work and you need it to work, you can configure SELinux\n"
"    temporarily to allow this access until the application is fixed. Please\n"
"file a bug report.\n"
"    "
msgstr ""
"\n"
"    $SOURCE アプリケーションが独自のスタックを実行可能にしようと試みました。\n"
"     セキュリティー上の問題となる可能性があります。これは完全に不要な動作です。\n"
"     最近の OS ではほとんどの場合スタックメモリーは実行可能になっていません。また、\n"
"    これが変更されることもありません。実行可能なスタックメモリーはセキュリティー上の\n"
"    重大な問題の1 つです。実際、execstack エラーは悪意のあるコードに\n"
"    よって発生する可能性が最も高いのです。アプリケーションは誤って記述\n"
"    されることがあり、この許可を要求することがあります。\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    のウェブページにはこの要求の削除方法が記載されています。$SOURCE が動作せず、これを\n"
"    動作させる必要がある場合には、アプリケーションが修正されるまでの間、\n"
"    SELinux を設定して一時的にこのアクセスを許可することができます。\n"
"    バグレポートを提出してください。\n"
"    "

#: ../src/allow_execstack.py:79
msgid ""
"\n"
"    Sometimes a library is accidentally marked with the execstack flag,\n"
"    if you find a library with this flag you can clear it with the\n"
"    execstack -c LIBRARY_PATH.  Then retry your application.  If the\n"
"    app continues to not work, you can turn the flag back on with\n"
"    execstack -s LIBRARY_PATH.\n"
"    "
msgstr ""
"\n"
"ライブラリーには間違って execstack フラグが付けられていることがあります。⏎ このフラグの付いたライブラリーを発見した場合は、⏎ "
"execstack -c LIBRARY_PATH "
"を使用してそれを消去できます。その後にアプリケーションを再試行して下さい。アプリケーションが機能しない状態が継続する場合は、⏎ execstack -s "
"LIBRARY_PATH を使用してフラグを戻すことができます。⏎ "

#: ../src/allow_execstack.py:89
msgid ""
"If you do not think $SOURCE_PATH should need to map stack memory that is "
"both writable and executable."
msgstr ""

#: ../src/allow_execstack.py:90
msgid "you need to report a bug. \n"
"This is a potentially dangerous access."
msgstr "バグをレポートする必要があります。\n"
"これは危険なアクセスです。"

#: ../src/allow_execstack.py:99
#, python-format
msgid "If you believe that \n"
"%s\n"
"should not require execstack"
msgstr ""

#: ../src/allow_execstack.py:108
#, python-format
msgid ""
"you should clear the execstack flag and see if $SOURCE_PATH works correctly.\n"
"Report this as a bug on %s.\n"
"You can clear the exestack flag by executing:"
msgstr ""
"execstack フラグをクリアして $SOURCE_PATH が正常に機能していることを確認する必要があります。\n"
"これは %s のバグとして報告します。\n"
"あなたは以下の実行による execstack フラグをクリアすることができます。"

#: ../src/allow_execstack.py:118
#, python-format
msgid "execstack -c %s"
msgstr "execstack -c %s"

#: ../src/allow_ftpd_use_cifs.py:29
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a CIFS "
"filesystem.\n"
"    "
msgstr ""
"\n"
"     SELinux は ftp デーモンが $ACCESS から CIFS ファイルシステム上に保存されているファイルへのアクセスを阻止しました。\n"
"      "

#: ../src/allow_ftpd_use_cifs.py:33
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a CIFS "
"filesystem.\n"
"    CIFS (Comment Internet File System) is a network filesystem similar to\n"
"    SMB (<a href=\"http://www.microsoft.com/mind/1196/cifs.asp\">http://www."
"microsoft.com/mind/1196/cifs.asp</a>)\n"
"    The ftp daemon attempted to read one or more files or directories from\n"
"    a mounted filesystem of this type.  As CIFS filesystems do not support\n"
"    fine-grained SELinux labeling, all files and directories in the\n"
"    filesystem will have the same security context.\n"
"\n"
"    If you have not configured the ftp daemon to read files from a CIFS "
"filesystem\n"
"    this access attempt could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は CIFS ファイルシステムに格納されているファイルが ftp デーモンによって $ACCESS されるのを阻止しました。\n"
"    CIFS (Comment Internet File System) は SMB と同様のネットワークファイルシステムです、\n"
"    (<a href=\"http://www.microsoft.com/mind/1196/cifs.asp\">http://www."
"microsoft.com/mind/1196/cifs.asp</a>)。\n"
"    ftp デーモンはマウントされているこのタイプのファイルシステムから 1 つまたは複数の\n"
"ファイルまたはディレクトリーを読み込もうとしました。 CIFS ファイルシステムは SELinux の\n"
"詳細なラベル機能をサポートしていないため、ファイルシステム内のすべてのファイルおよびディレクトリーは\n"
"同じセキュリティーコンテキストを有することになります。\n"
"    \n"
"    ftp デーモンが CIFS ファイルシステムからファイルを読み込むように設定していない場合、\n"
"    このアクセスの試行が不正侵入の試行を示唆する可能性があります。\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:46
msgid ""
"\n"
"    Changing the \"$BOOLEAN\" boolean to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1.\"\n"
"    "
msgstr ""
"\n"
"    \"$BOOLEAN\" boolean を 「true」に変更するとこのアクセスを許可します:\n"
"    \"setsebool -P $BOOLEAN=1.\"\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:53
msgid ""
" Changing the \"$BOOLEAN\" and\n"
"    \"$WRITE_BOOLEAN\" booleans to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1 $WRITE_BOOLEAN=1\".\n"
"    warning: setting the \"$WRITE_BOOLEAN\" boolean to true will\n"
"    allow the ftp daemon to write to all public content (files and\n"
"    directories with type public_content_t) in addition to writing to\n"
"    files and directories on CIFS filesystems.  "
msgstr ""
"\"$BOOLEAN\" 及び \"$WRITE_BOOLEAN\" の boolean を true に変更すると、 \n"
"このアクセスが許可されます:\n"
"\"setsebool -P $BOOLEAN=1 $WRITE_BOOLEAN=1\"\n"
"警告: \"$WRITE_BOOLEAN\" の boolean を true に設定すると、 CIFS \n"
"ファイルシステム上のファイルやディレクトリへの書き込みに加えて、 \n"
"すべての公開コンテンツ (タイプが public_content_t のファイルと\n"
"ディレクトリ) への書き込みも ftp デーモンに許可することになります。"

#: ../src/allow_ftpd_use_cifs.py:62
msgid "If you want to allow ftpd to write to cifs file systems"
msgstr ""

#: ../src/allow_ftpd_use_cifs.py:63 ../src/allow_ftpd_use_nfs.py:65
msgid "you must tell SELinux about this"
msgstr "これについては、SELinux に設定をしなければいけません"

#: ../src/allow_ftpd_use_nfs.py:29
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a NFS "
"filesystem.\n"
"    "
msgstr ""
"\n"
"     SELinux は ftp デーモンが $ACCESS から NFS ファイルシステム上に保存されているファイルへのアクセスを阻止しました。\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:33
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a NFS "
"filesystem.\n"
"    NFS (Network Filesystem) is a network filesystem commonly used on Unix / "
"Linux\n"
"    systems.\n"
"\n"
"    The ftp daemon attempted to read one or more files or directories from\n"
"    a mounted filesystem of this type.  As NFS filesystems do not support\n"
"    fine-grained SELinux labeling, all files and directories in the\n"
"    filesystem will have the same security context.\n"
"\n"
"    If you have not configured the ftp daemon to read files from a NFS "
"filesystem\n"
"    this access attempt could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は NFS ファイルシステムに格納されているファイルが ftp デーモンによって $ACCESS されるのを阻止しました。\n"
"    NFS (Network Filesystem) は Unix システム/ Linux システムで一般的に使用されるネットワーク\n"
"    ファイルシステムです。\n"
"    \n"
"    ftp デーモンはマウントされているこのタイプのファイルシステムから 1 つまたは複数の\n"
"ファイルまたはディレクトリーを読み込もうとしました。 NFS ファイルシステムは SELinux の詳細な\n"
"ラベル機能はサポートしていないため、 ファイルシステム内のすべてのファイルおよびディレクトリーは\n"
"同じセキュリティーコンテキストを有することになります。\n"
"    \n"
"    ftp デーモンが NFS ファイルシステムからファイルを読み込むよう設定してない場合、\n"
"    このアクセスの試行が不正侵入の試行を示唆する可能性があります。\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:47
msgid ""
"\n"
"    Changing the \"allow_ftpd_use_nfs\" boolean to true will allow this "
"access:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1.\"\n"
"    "
msgstr ""
"\n"
"      \"allow_ftpd_use_nfs\" boolean を「true」に変更するとこのアクセスを 許可します:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1.\"\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:54
msgid ""
" Changing the \"allow_ftpd_use_nfs\" and\n"
"    \"$WRITE_BOOLEAN\" booleans to true will allow this access:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1 $WRITE_BOOLEAN=1\".\n"
"    warning: setting the \"$WRITE_BOOLEAN\" boolean to true will\n"
"    allow the ftp daemon to write to all public content (files and\n"
"    directories with type public_content_t) in addition to writing to\n"
"    files and directories on NFS filesystems.  "
msgstr ""
"\"allow_ftpd_use_nfs\" と \"$WRITE_BOOLEAN\" の boolean を\n"
"true に変更すると、 このアクセスが許可されます:\n"
"\"setsebool -P allow_ftpd_use_nfs=1 $WRITE_BOOLEAN=1\"\n"
"警告: \"$WRITE_BOOLEAN\" の boolean を true に設定すると、 \n"
"NFS ファイルシステム上のファイルやディレクトリへの\n"
"書き込みに加えて、 すべての公開コンテンツ (タイプが \n"
"public_content_t のファイルとディレクトリ) への書き込みも \n"
"ftp デーモンに許可することになります。"

#: ../src/allow_ftpd_use_nfs.py:64
msgid "If you want to allow ftpd to write to nfs file systems"
msgstr ""

#: ../src/associate.py:32 ../src/openvpn.py:31 ../src/public_content.py:27
#: ../src/qemu_blk_image.py:27 ../src/qemu_file_image.py:27
#: ../src/restorecon.py:51 ../src/restorecon_source.py:33
#: ../src/rsync_data.py:27 ../src/sshd_root.py:32
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access to $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE_PATH による $TARGET_PATH への \"$ACCESS\" アクセスを阻止しています。\n"
"    "

#: ../src/associate.py:37
#, python-format
msgid ""
"\n"
"You tried to place a type on a %s that is not a file type.  This is not "
"allowed, you must assigne a file type.  You can list all file types using "
"the seinfo command.\n"
"\n"
"seinfo -afile_type -x\n"
"\n"
"    "
msgstr ""
"\n"
" %s 上にファイルタイプではない１つのタイプの配置を試みました。これは許可されていないため、ファイルタイプを指定する必要があります。次の seinfo "
"コマンドを使用すると、全てのファイルタイプを一覧表示することが出来ます。⏎ ⏎ seinfo -afile_type -x⏎ ⏎ "

#: ../src/associate.py:44
#, python-format
msgid ""
"If you want to change the label of $TARGET_PATH to %s, you are not allowed "
"to since it is not a valid file type."
msgstr ""

#: ../src/associate.py:49
msgid "you must pick a valid file label."
msgstr "有効なファイルラベルを選択する必要があります。"

#: ../src/automount_exec_config.py:27
msgid ""
"\n"
"    SELinux is preventing the $SOURCE_PATH from executing potentially "
"mislabeled files $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE_PATH による、誤ったラベル付けの可能性のあるファイル $TARGET_PATH の使用を阻止しています。\n"
"    "

#: ../src/automount_exec_config.py:31
msgid ""
"\n"
"    SELinux has denied the $SOURCE_PATH from executing potentially\n"
"    mislabeled files $TARGET_PATH.  Automounter can be setup to execute\n"
"    configuration files. If $TARGET_PATH is an automount executable\n"
"    configuration file it needs to have a file label of bin_t.\n"
"    If automounter is trying to execute something that it is not supposed "
"to, this could indicate an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE_PATH が間違ったラベルを持つ可能性のあるファイル\n"
"      $TARGET_PATH を実行するのを拒否しました。自動マウンタは設定ファイルを\n"
"      実行するようにセット出来ます。 $TARGET_PATH が自動マウント実行可能な \n"
"     設定ファイルである場合、bin_t のファイルラベルを持つ必要があります。\n"
"      自動マウンタが想定されていない何かを実行しようとしている場合、\n"
"     これは不正侵入をを示唆している可能性があります。\n"
"     "

#: ../src/automount_exec_config.py:39
msgid ""
"\n"
"    If you want to change the file context of $TARGET_PATH so that the "
"automounter can execute it you can execute \"chcon -t bin_t $TARGET_PATH\".  "
"If you want this to survive a relabel, you need to permanently change the "
"file context: execute  \"semanage fcontext -a -t bin_t '$FIX_TARGET_PATH'\".\n"
"    "
msgstr ""
"\n"
"自動マウンタで実行できるよう $TARGET_PATH のファイルコンテキストを変更する場合は、 \"chcon -t bin_t "
"$TARGET_PATH\" を実行します。 再ラベル後もこの変更を維持させる場合は、 ファイルコンテキストを永久に変更する必要があります。 "
"\"semanage fcontext -a -t bin_t '$FIX_TARGET_PATH'\" を実行します。\n"
"    "

#: ../src/bind_ports.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from binding to port $PORT_NUMBER.\n"
"    "
msgstr "\n"
"    SELinux は $SOURCE_PATH によるポート $PORT_NUMBER へのバインドを阻止しています。\n"
"    "

#: ../src/bind_ports.py:31
#, python-format
msgid ""
"\n"
"    SELinux has denied the $SOURCE from binding to a network port "
"$PORT_NUMBER which does not have an SELinux type associated with it.\n"
"    If $SOURCE should be allowed to listen on $PORT_NUMBER, use the "
"<i>semanage</i> command to assign $PORT_NUMBER to a port type that "
"$SOURCE_TYPE can bind to (%s).\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to bind to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    $SOURCE が、ポートに関連付けられた SELinux タイプを持たないネットワークポート $PORT_NUMBER "
"にバインドすることを、SELinux は拒否しました。\n"
"    $SOURCE の $PORT_NUMBER でのリッスンを許可する必要がある場合、 <i>semanage</i> コマンドを使用して "
"$PORT_NUMBER を $SOURCE_TYPE が バインドできるポートタイプへ割り当てます (%s)  。 \n"
"    \n"
"\n"
"$SOURCE による $PORT_NUMBER へのバインドが想定されていない場合、 \n"
"    不正侵入の試行が示唆される可能性があります。\n"
"    "

#: ../src/bind_ports.py:38
#, python-format
msgid ""
"\n"
"    If you want to allow $SOURCE to bind to port $PORT_NUMBER, you can "
"execute \n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    \n"
"where PORT_TYPE is one of the following: %s.\n"
"\n"
"    \n"
"\n"
"If this system is running as an NIS Client, turning on the allow_ypbind "
"boolean may fix the problem.  setsebool -P allow_ypbind=1.\n"
"    "
msgstr ""
"\n"
"     $SOURCE がポート $PORT_NUMBER にバインドできるようにしたい場合、以下コマンドを実行します。\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    \n"
"ここで PORT_TYPE は下のいずれかです: %s.\n"
"\n"
"    \n"
"\n"
"使用システムが NIS クライアントとして稼働している場合、 allow_ypbind boolean "
"をオンにすると問題を解決するかも知れません。setsebool -P allow_ypbind=1\n"
"    "

#: ../src/bind_ports.py:47
msgid "If you want to allow $SOURCE_PATH to bind to network port $PORT_NUMBER"
msgstr ""

#: ../src/bind_ports.py:53 ../src/connect_ports.py:51
#, python-format
msgid ""
"# semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    where PORT_TYPE is one of the following: %s."
msgstr ""
"# semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"　　ここで、PORT_TYPE は 以下の１つとなります: %s    "

#: ../src/bind_ports.py:56 ../src/connect_ports.py:54
#, python-format
msgid "# semanage port -a -t %s -p %s $PORT_NUMBER"
msgstr "# semanage port -a -t %s -p %s $PORT_NUMBER"

#: ../src/catchall_boolean.py:32
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access on $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は  $TARGET_PATH への $SOURCE_PATH による \"$ACCESS\" アクセスを阻止しています。\n"
"    "

#: ../src/catchall_boolean.py:36
msgid ""
"\n"
"\n"
"    SELinux denied access requested by $SOURCE. The current boolean\n"
"    settings do not allow this access.  If you have not setup $SOURCE to\n"
"    require this access this may signal an intrusion attempt. If you do "
"intend\n"
"    this access you need to change the booleans on this system to allow\n"
"    the access.\n"
"    "
msgstr ""
"\n"
"\n"
"    SELinux は $SOURCE により要求されたアクセスを拒否しました。 \n"
"    現在のブーリアン設定はこのアクセスを許可しません。このアクセスを\n"
"    要求するように $SOURCE を設定していない場合、不正侵入の試行が示唆される\n"
"     可能性があります。 アクセスする必要がある場合は、このシステム上でブーリアン値を変更し、アクセスを許可するようにしなければなりません。\n"
"\n"
"    "

#: ../src/catchall_boolean.py:45
msgid ""
"\n"
"    Confined processes can be configured to run requiring different access, "
"SELinux provides booleans to allow you to turn on/off\n"
"    access as needed.\n"
"\n"
"    "
msgstr ""
"\n"
"    別のアクセスを必要とする、限定されたプロセスを実行するように設定できます。 SELInux は必要に応じて、ユーザーがアクセスをオン/"
"オフに切り替えできる \n"
"    ブーリアン値を提供します。\n"
"\n"
"    "

#: ../src/catchall_boolean.py:62
#, python-format
msgid "If you want to %s"
msgstr ""

#: ../src/catchall_boolean.py:65
#, python-format
msgid "setsebool -P %s %s"
msgstr "setsebool -P %s %s"

#: ../src/catchall_boolean.py:68
#, python-format
msgid "You must tell SELinux about this by enabling the '%s' boolean.\n"
msgstr "'%s' boolean を有効にすることにより、 これを SELinux に伝える必要があります。\n"

#: ../src/catchall_boolean.py:71
#, python-format
msgid "You can read '%s' man page for more details."
msgstr "詳細情報については、'%s' man ページをご覧下さい。"

#: ../src/catchall_labels.py:28
#, python-format
msgid ""
"\n"
"    SELinux has denied the $SOURCE access to potentially\n"
"    mislabeled files $TARGET_PATH.  This means that SELinux will not\n"
"    allow httpd to use these files. If httpd should be allowed this access "
"to these files you should change the file context to one of the following "
"types, %s.\n"
"    Many third party apps install html files\n"
"    in directories that SELinux policy cannot predict.  These directories\n"
"    have to be labeled with a file context which httpd can access.\n"
"    "
msgstr ""
"\n"
"SELinux により誤ったラベル付けの可能性のある $TARGET_PATH ファイル\n"
"への $SOURCE のアクセスが拒否されています。 これは、 SELinux では httpd \n"
"によるこれらのファイルの使用が許可されないということになります。 \n"
"httpd にこうしたファイルへの同様の アクセスを許可する場合は、 \n"
"ファイルコンテキストを次のいずれかのタイプに変更する必要があります、 %s。\n"
"多くのサードパーティーのアプリケーションでは、 SELinux ポリシーでは\n"
"予期できないディレクトリ内に html ファイルがインストールされます。\n"
"これらのディレクトリには httpd によるアクセスが可能なファイルコンテキスト\n"
"でラベル付けを行なう必要があります。"

#: ../src/catchall_labels.py:37
msgid "You need to change the label on $FIX_TARGET_PATH"
msgstr "$FIX_TARGET_PATH のラベルを変更する必要があります"

#: ../src/catchall_labels.py:40
#, python-format
msgid ""
"# semanage fcontext -a -t FILE_TYPE '$FIX_TARGET_PATH'\n"
"where FILE_TYPE is one of the following: %s.\n"
"Then execute:\n"
"restorecon -v '$FIX_TARGET_PATH'\n"
msgstr ""
"# semanage fcontext -a -t FILE_TYPE '$FIX_TARGET_PATH'\n"
"この FILE_TYPE は以下のいずれかになります: %s. \n"
"次に以下を実行してください: \n"
"restorecon -v '$FIX_TARGET_PATH'\n"

#: ../src/catchall.py:29 ../src/chrome.py:29 ../src/mozplugger.py:29
#: ../src/mozplugger_remove.py:29
msgid "SELinux is preventing $SOURCE_PATH \"$ACCESS\" access."
msgstr "SELinux は $SOURCE_PATH による \"$ACCESS\" アクセスを阻止しています。    "

#: ../src/catchall.py:31
msgid ""
"\n"
"\n"
"    SELinux denied access requested by $SOURCE. It is not\n"
"    expected that this access is required by $SOURCE and this access\n"
"    may signal an intrusion attempt. It is also possible that the specific\n"
"    version or configuration of the application is causing it to require\n"
"    additional access.\n"
"\n"
"    "
msgstr ""
"\n"
"\n"
"    SELinux は $SOURCE により要求されたアクセスを拒否しました。 \n"
"    このアクセスは $SOURCE に必要であると想定されないため不正侵入\n"
"    の試行を示している可能性があります。 また、 アプリケーションの特定\n"
"    バージョンまたは設定が追加アクセス要求の原因となっている可能性\n"
"    もあります。\n"
"\n"
"    "

#: ../src/catchall.py:41
msgid ""
"\n"
"    You can generate a local policy module to allow this\n"
"    access - see <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"\n"
"    Please file a bug report.\n"
"    "
msgstr ""
"\n"
"    ローカルポリシーモジュールを生成して、このアクセスを許可するように\n"
"    できます：<a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a> をご覧下さい。\n"
"\n"
"    バグレポートを提出してください。\n"
"    "

#: ../src/catchall.py:50
msgid ""
"If you believe that $SOURCE_BASE_PATH should be allowed $ACCESS access on "
"processes labeled $TARGET_TYPE by default."
msgstr ""

#: ../src/catchall.py:52
msgid ""
"If you believe that $SOURCE_BASE_PATH should have the $ACCESS capability by "
"default."
msgstr ""

#: ../src/catchall.py:53
msgid ""
"If you believe that $SOURCE_BASE_PATH should be allowed $ACCESS access on "
"the $TARGET_BASE_PATH $TARGET_CLASS by default."
msgstr ""

#: ../src/catchall.py:55
msgid ""
"You should report this as a bug.\n"
"You can generate a local policy module to allow this access."
msgstr "バグとして報告してください。 \n"
"ローカルのポリシーモジュールを生成すると、\n"
" このアクセスを許可することができます。"

#: ../src/catchall.py:56
msgid ""
"Allow this access for now by executing:\n"
"# ausearch -c '$SOURCE' --raw | audit2allow -M my-$MODULE_NAME\n"
"# semodule -i my-$MODULE_NAME.pp"
msgstr ""

#: ../src/connect_ports.py:27 ../src/sandbox_connect.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from connecting to port $PORT_NUMBER.\n"
"    "
msgstr "\n"
"    SELinux は $SOURCE_PATH によるポート $PORT_NUMBER への接続を 阻止しています。\n"
"    "

#: ../src/connect_ports.py:31
#, python-format
msgid ""
"\n"
"    SELinux has denied $SOURCE from connecting to a network port "
"$PORT_NUMBER which does not have an SELinux type associated with it.\n"
"    If $SOURCE should be allowed to connect on $PORT_NUMBER, use the "
"<i>semanage</i> command to assign $PORT_NUMBER to a port type that "
"$SOURCE_TYPE can connect to (%s).\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to connect to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/connect_ports.py:38
#, python-format
msgid ""
"\n"
"    If you want to allow $SOURCE to connect to $PORT_NUMBER, you can execute "
"\n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"\n"
"    where PORT_TYPE is one of the following: %s.\n"
"    "
msgstr ""
"\n"
"    $SOURCE による $PORT_NUMBER への接続を許可する場合は、 以下を実行します。\n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"\n"
"   ここで、PORT_TYPE は 以下の１つとなります: %s 。\n"
"    "

#: ../src/connect_ports.py:45 ../src/sandbox_connect.py:47
msgid ""
"If you want to allow $SOURCE_PATH to connect to network port $PORT_NUMBER"
msgstr ""

#: ../src/chrome.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not expected that this "
"access is required by $SOURCE and this access may signal an intrusion "
"attempt. It is also possible that the specific version or configuration of "
"the application is causing it to require additional access.  spice-xpi run "
"applications within mozilla-plugins that require access to the desktop, that "
"the mozilla_plugin lockdown will not allow, so either you need to turn off "
"the mozilla_plugin lockdown or not use these packages.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE が要求したアクセスを拒否しました。$SOURCE "
"がこのアクセスを必要とすることは想定されておらず、このアクセスは侵入の試行である可能性があります。アプリケーションの特定のバージョンまたは設定により、追加アクセスが必要となっている可能性もあります。spice-"
"xpi は、デスクトップへのアクセスを必要とする mozilla-plugins 内でアプリケーションを実行し、mozilla_plugin "
"ロックダウンは許可されないことから、mozilla_plugin ロックダウンをオフにするか、これらのパッケージを使用しないようにする必要があります。\n"
" "

#: ../src/chrome.py:35
msgid ""
"\n"
"Either remove the mozplugger or spice-xpi package by executing 'yum remove "
"mozplugger spice-xpi', or turn off enforcement of SELinux over the Chrome "
"plugins. setsebool -P unconfined_chrome_sandbox_transition 0\n"
"    "
msgstr ""
"\n"
"'yum remove mozplugger spice-xpi' を実行して mozplluger または spice-xpi "
"のパッケージを削除するか、Chrome プラグインで SELinux の強制をオフにします。setsebool -P "
"unconfined_chrome_sandbox_transition 0\n"
"    "

#: ../src/chrome.py:38 ../src/mozplugger.py:38
#, python-format
msgid "If you want to use the %s package"
msgstr ""

#: ../src/chrome.py:43
msgid "you must turn off SELinux controls on the Chrome plugins."
msgstr "Chrome プラグインにおいて SELinux 制御を無効化する必要があります。"

#: ../src/cvs_data.py:27
msgid ""
"\n"
"    SELinux is preventing cvs ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH\n"
"    "
msgstr ""
"\n"
"    SELinux は cvs ($SOURCE_PATH) による $TARGET_PATH への \"$ACCESS\" "
"アクセスを阻止しています\n"
"    "

#: ../src/cvs_data.py:31
msgid ""
"\n"
"    SELinux denied cvs access to $TARGET_PATH.\n"
"    If this is a CVS repository it needs to have a file context label of\n"
"    cvs_data_t. If you did not intend to use $TARGET_PATH as a CVS "
"repository\n"
"    it could indicate either a bug or it could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への cvs アクセスを拒否しました。\n"
"    これが CVS リポジトリーの場合は、 cvs_data_t のファイルコンテキストラベルを \n"
"    持っていなければなりません。CVS リポジトリーとして $TARGET_PATH を\n"
"    使用するつもりではなかった場合、これはバグであるか不正侵入の試行を示している可能性があります。\n"
"    "

#: ../src/cvs_data.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t cvs_data_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"cvs_data_t '$FIX_TARGET_PATH'\"\n"
"    \n"
"    "
msgstr ""
"\n"
"    chcon -R -t cvs_data_t '$TARGET_PATH' を実行すると、ファイルコンテキストを変更することが出来ます。\n"
"    "
"また、完全な再ラベルの後でもそれらを維持できるようにするには、システム上のデフォルトのファイルコンテキストファイルの変更もしなければなりません。\"semanage "
"fcontext -a -t cvs_data_t '$FIX_TARGET_PATH'\"\n"
"    \n"
"    "

#: ../src/cvs_data.py:44
msgid "If $TARGET_BASE_PATH should be shared via the cvs daemon"
msgstr ""

#: ../src/cvs_data.py:45 ../src/qemu_file_image.py:49
msgid "You need to change the label on $TARGET_BASE_PATH'"
msgstr "$TARGET_BASE_PATH' のラベルを変更する必要があります。"

#: ../src/dac_override.py:28
msgid "\n"
"    SELinux is preventing $SOURCE_PATH the \"$ACCESS\" capability.\n"
"    "
msgstr "\n"
"    SELinux は $SOURCE_PATH の \"$ACCESS\" 機能を阻止しています。\n"
"    "

#: ../src/dac_override.py:32
msgid ""
"\n"
"\tdac_override and dac_read_search capabilities usually indicates that the "
"root process does not have access to a file based on the permission flags.  "
"This usually mean you have some file with the wrong ownership/permissions on "
"it.\n"
"    "
msgstr ""
"\n"
" \tdac_override と dac_read_search の機能は通常、root プロセスがパーミッションフラグを "
"基にしたファイルへのアクセスを持たないことを表示します。これは通常、ユーザーがそのファイルに 間違えた所有権/"
"パーミッションを持っていることを意味します。 \n"
"    "

#: ../src/dac_override.py:38
msgid ""
"If you want to help identify if domain needs this access or you have a file "
"with the wrong permissions on your system"
msgstr ""

#: ../src/dac_override.py:39
msgid ""
"turn on full auditing to get path information about the offending file and "
"generate the error again."
msgstr "全面的な監査を開始して違反しているファイルに関するパス情報を取得し、 再度エラーを生成します。"

#: ../src/dac_override.py:40
msgid ""
"\n"
"Turn on full auditing\n"
"# auditctl -w /etc/shadow -p w\n"
"Try to recreate AVC. Then execute\n"
"# ausearch -m avc -ts recent\n"
"If you see PATH record check ownership/permissions on file, and fix it,\n"
"otherwise report as a bugzilla."
msgstr ""
"\n"
"全面的な監査を開始します\n"
"# auditctl -w /etc/shadow -p w\n"
"AVC の再作成を試みます。その後に以下を実行します。\n"
"# ausearch -m avc -ts recent\n"
"PATH 記録を確認できる場合は、ファイルの所有権/許可をチェックして修正し、\n"
"確認できない場合はバグとして報告します。"

#: ../src/device.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access to device "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は デバイス $TARGET_PATH への $SOURCE_PATH による \"$ACCESS\" "
"アクセスを阻止しています。\n"
"    "

#: ../src/device.py:33
msgid ""
"\n"
"\n"
"    SELinux has denied $SOURCE \"$ACCESS\" access to device $TARGET_PATH.\n"
"    $TARGET_PATH is mislabeled, this device has the default label of the /"
"dev directory, which should not\n"
"    happen.  All Character and/or Block Devices should have a label.\n"
"\n"
"    You can attempt to change the label of the file using\n"
"\n"
"    restorecon -v '$TARGET_PATH'.\n"
"\n"
"    If this device remains labeled device_t, then this is a bug in SELinux "
"policy.\n"
"\n"
"    Please file a bg report.\n"
"\n"
"    If you look at the other similar devices labels, ls -lZ /dev/SIMILAR, "
"and find a type that would work for $TARGET_PATH,\n"
"    you can use chcon -t SIMILAR_TYPE '$TARGET_PATH', If this fixes the "
"problem, you can make this permanent by executing\n"
"    semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"\n"
"    If the restorecon changes the context, this indicates that the "
"application that created the device, created it without\n"
"    using SELinux APIs.  If you can figure out which application created the "
"device, please file a bug report against this application.\n"
"\n"
"    "
msgstr ""
"\n"
"\n"
"    SELinux はデバイス $TARGET_PATH への $SOURCE による \"$ACCESS\" アクセスを拒否しています。\n"
"    $TARGET_PATH には誤ったラベルが付けられています。このデバイスには /dev "
"ディレクトリーのデフォルトラベルがありますが、これは誤った設定です。すべてのキャラクターデバイス\n"
"またはブロックデバイスにはラベルがなければなりません。\n"
"\n"
"    以下を実行してファイルのラベル変更を試行することができます。\n"
"\n"
"    restorecon -v $TARGET_PATH\n"
"\n"
"    このデバイスのラベルが device_t のままである場合、これは  SELinux ポリシーのバグということになります。\n"
"\n"
"    バグレポートを提出してください。\n"
"\n"
"    他の同様のデバイスラベルを確認するために  ls -lZ /dev/SIMILAR を実行し、 $TARGET_PATH "
"に対して動作すると想定されるタイプを見つけたら\n"
"    chcon -t SIMILAR_TYPE $TARGET_PATH "
"を使用します。これで問題が解決する場合は、以下を実行して永続的に変更します。\n"
"    semanage fcontext -a -t SIMILAR_TYPE $FIX_TARGET_PATH\n"
"\n"
"    restorecon がコンテキストを変更する場合、 デバイスを作成したアプリケーションが SELinux API "
"を使用せずに作成したということを示しています。\n"
"    デバイスを作成したアプリケーションを判別できる場合は、そのアプリケーションについてのバグレポートを提出してください。\n"
"    \n"
"    "

#: ../src/device.py:56
msgid ""
"\n"
"    Attempt restorecon -v '$TARGET_PATH' or chcon -t SIMILAR_TYPE "
"'$TARGET_PATH'\n"
"    "
msgstr ""
"\n"
"    restorecon -v $TARGET_PATH または chcon -t SIMILAR_TYPE $TARGET_PATH "
"を試してください。\n"
"    "

#: ../src/device.py:60
msgid ""
"You need to change the label on $TARGET_PATH to a type of a similar device."
msgstr "$TARGET_PATH のラベルを同種のデバイスのタイプに変更する必要があります。"

#: ../src/device.py:61
msgid ""
"# semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"

#: ../src/disable_ipv6.py:30
msgid "\n"
"Disable IPV6 properly.\n"
"    "
msgstr "\n"
"IPv6 を正しく無効化しました。\n"
"    "

#: ../src/disable_ipv6.py:40
msgid "If you want to disable IPV6 on this machine"
msgstr ""

#: ../src/disable_ipv6.py:41
msgid ""
"you need to set /proc/sys/net/ipv6/conf/all/disable_ipv6 to 1 and do not "
"blacklist the module'"
msgstr ""
"/proc/sys/net/ipv6/conf/all/disable_ipv6 を 1 に設定する必要があり、モジュールをブラックリストにしません。"

#: ../src/disable_ipv6.py:42
msgid "Add \n"
"net.ipv6.conf.all.disable_ipv6 = 1\n"
"to /etc/sysctl.conf\n"
msgstr "net.ipv6.conf.all.disable_ipv6 = 1 を\n"
"/etc/sysctl.conf に追加します\n"

#: ../src/file.py:27
msgid ""
"\n"
"    SELinux is preventing access to files with the label, file_t.\n"
"    "
msgstr "\n"
"    SELinux は file_t ラベルが付いたファイルへのアクセスを阻止しています。\n"
"    "

#: ../src/file.py:31
msgid ""
"\n"
"    SELinux permission checks on files labeled file_t are being\n"
"    denied.  file_t is the context the SELinux kernel gives to files\n"
"    that do not have a label. This indicates a serious labeling\n"
"    problem. No files on an SELinux box should ever be labeled file_t.\n"
"    If you have just added a disk drive to the system you can\n"
"    relabel it using the restorecon command.  For example if you saved the\n"
"home directory from a previous installation that did not use SELinux, "
"'restorecon -R -v /home' will fix the labels.  Otherwise you should\n"
"    relabel the entire file system.\n"
"    "
msgstr ""
"\n"
"file_t のラベルが付いたファイル上の SELinux 権限チェックは拒否⏎ されています。file_t は、SELinux "
"カーネルがラベルを持たないファイルに付与するコンテキストです。これは真剣なラベル付けの問題を⏎ 示します。SELinux ボックス上のファイルはいずれも "
"file_t のラベルを付けるべきものではありません。システムにディスクドライブを追加したばかりの場合は、restorecon "
"コマンドを使用してラベルの変更ができます。例えば、SELinux "
"を使用していない以前のインストールからホームディレクトリを保存した場合、'restorecon -R -v /home' "
"でラベルを修正できます。　それ以外には、全てのファイルシステムをラベル変更する必要があります。"

#: ../src/file.py:42
msgid ""
"\n"
"    You can execute the following command as root to relabel your\n"
"    computer system: \"touch /.autorelabel; reboot\"\n"
"    "
msgstr ""
"\n"
"    root として次のコマンドを実行するとご使用のコンピュータを再ラベルする\n"
"    ことができます: \"touch /.autorelabel; reboot\"\n"
"    "

#: ../src/file.py:49
msgid "This is caused by a newly created file system."
msgstr ""

#: ../src/file.py:51
msgid "If you think this is caused by a badly mislabeled machine."
msgstr ""

#: ../src/file.py:55
msgid "you need to add labels to it."
msgstr "これにラベルを追加する必要があります。"

#: ../src/file.py:57
msgid "you need to fully relabel."
msgstr "すべてにラベルを付け直す必要があります。"

#: ../src/filesystem_associate.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from creating a file with a context "
"of $SOURCE_TYPE on a filesystem.\n"
"    "
msgstr ""
"\n"
"      SELinux は $SOURCE_PATH がファイルシステム上で $SOURCE_TYPE "
"のコンテキストでファイルを作成することを阻止しています。\n"
"      "

#: ../src/filesystem_associate.py:31
msgid ""
"\n"
"    SELinux is preventing $SOURCE from creating a file with a context of "
"$SOURCE_TYPE on a filesystem.\n"
"    Usually this happens when you ask the cp command to maintain the context "
"of a file when\n"
"    copying between file systems, \"cp -a\" for example.  Not all file "
"contexts should be maintained\n"
"    between the file systems.  For example, a read-only file type like "
"iso9660_t should not be placed\n"
"    on a r/w system.  \"cp -p\" might be a better solution, as this will "
"adopt the default file context\n"
"    for the destination.\n"
"    "
msgstr ""
"\n"
"     SELinux は $SOURCE がファイルシステム上で $SOURCE_TYPE "
"のコンテキストを持つファイルを作成することを阻止しています。\n"
"     通常、これは、例えば \"cp -a\" のようにファイルシステム間でのコピーの実行時に、 cp "
"コマンドにファイルのコンテキストを維持するように依頼する際に生じます。すべてのファイルコンテキストがファイルシステム間で維持されるべきではありません。\n"
"     例えば、iso9660_t のような読み込み専用のファイルタイプは r/w システム上に置くべきではありません。\n"
"     \"cp -p\" はコピー先のデフォルトファイルコンテキストを採用するため、より適切なソリューションとなる可能性があります。\n"
"     "

#: ../src/filesystem_associate.py:40
msgid ""
"\n"
"    Use a command like \"cp -p\" to preserve all permissions except SELinux "
"context.\n"
"    "
msgstr "\n"
"     \"cp -p\" などのコマンドを使用して、SELinux コンテキスト以外の全ての権限を保存します。\n"
"     "

#: ../src/filesystem_associate.py:43
msgid ""
"If you believe $SOURCE_BASE_PATH should be allowed to create "
"$TARGET_BASE_PATH files"
msgstr ""

#: ../src/filesystem_associate.py:44
msgid ""
"you need to use a different command. You are not allowed to preserve the "
"SELinux context on the target file system."
msgstr ""
"別のコマンドを使用する必要があります。あなたはターゲットのファイルシステムで、SELinux コンテンツを保存することが許可されていません。"

#: ../src/filesystem_associate.py:46
msgid ""
"use a command like \"cp -p\" to preserve all permissions except SELinux "
"context."
msgstr "\"cp -p\" などのコマンドを使用して、SELinux コンテキスト以外の全ての権限を保存します。     "

#: ../src/httpd_can_sendmail.py:28
msgid "\n"
"    SELinux is preventing the http daemon from sending mail.\n"
"    "
msgstr "\n"
"    SELinux は http デーモンによるメール送信を阻止しています。\n"
"    "

#: ../src/httpd_can_sendmail.py:32
msgid ""
"\n"
"    SELinux has denied the http daemon from sending mail. An\n"
"    httpd script is trying to connect to a mail port or execute the\n"
"    sendmail command. If you did not setup httpd to sendmail, this could\n"
"    signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/httpd_can_sendmail.py:39
msgid ""
"\n"
"    If you want httpd to send mail you need to turn on the\n"
"    $BOOLEAN boolean: \"setsebool -P\n"
"    $BOOLEAN=1\"\n"
"    "
msgstr ""
"\n"
"    httpd にメール送信をさせる場合は、 $BOOLEAN boolean\n"
"    をオンにする必要があります: \"setsebool -P\n"
"    $BOOLEAN=1\"\n"
"    "

#: ../src/httpd_can_sendmail.py:47
msgid "If you want to allow httpd to send mail"
msgstr ""

#: ../src/httpd_can_sendmail.py:48
msgid "you must setup SELinux to allow this"
msgstr "これを許可するには、SELinux を設定しなければいけません"

#: ../src/httpd_unified.py:29
msgid "\n"
"    SELinux prevented httpd $ACCESS access to http files.\n"
"    "
msgstr "\n"
"      httpdの、 http ファイルへの $ACCESS アクセスを、SELinux は阻止しました。\n"
"    "

#: ../src/httpd_unified.py:33
msgid ""
"\n"
"    SELinux prevented httpd $ACCESS access to http files.\n"
"\n"
"    Ordinarily httpd is allowed full access to all files labeled with http "
"file\n"
"    context.  This machine has a tightened security policy with the $BOOLEAN\n"
"    turned off,  This requires explicit labeling of all files.  If a file is\n"
"    a cgi script it needs to be labeled with httpd_TYPE_script_exec_t in "
"order\n"
"    to be executed.  If it is read only content, it needs to be labeled\n"
"    httpd_TYPE_content_t, it is writable content. it needs to be labeled\n"
"    httpd_TYPE_script_rw_t or httpd_TYPE_script_ra_t. You can use the\n"
"    chcon command to change these context.  Please refer to the man page\n"
"    \"man httpd_selinux\" or\n"
"    <a href=\"http://fedora.redhat.com/docs/selinux-apache-fc3\">FAQ</a>\n"
"    \"TYPE\" refers to one of \"sys\", \"user\" or \"staff\" or potentially "
"other\n"
"    script types.\n"
"    "
msgstr ""
"\n"
"SELinux により http ファイルへの  httpd の $ACCESS アクセスが阻止されました。\n"
"\n"
"通常の httpd の場合、 http ファイルコンテキストのラベルが付けられたファイルには\n"
"完全アクセスが許可されます。 このマシンでは、 $BOOLEAN がオフに設定され、 \n"
"セキュリティーポリシーが強化されています。 このため、 すべてのファイルに明示的なラベル付けを行なう必要があります。 ファイルが cgi "
"スクリプトの場合は、 スクリプト\n"
"を実行するために httpd_TYPE_script_exec_t のラベルを付ける必要があります。\n"
"読み取り専用のコンテンツの場合は、 httpd_TYPE_content_t のラベルを\n"
"付けます。 書込み可能なコンテンツなら、 httpd_TYPE_script_rw_t または \n"
"httpd_TYPE_script_ra_t のラベルを付ける必要があります。 コンテキストの変更は \n"
"chcon コマンドを使用して実行することができます。man ページの \"man httpd_selinux\" を参照するか、 <a href="
"\"http://fedora.redhat.com/docs/selinux-apache-fc3\">FAQ</a> \n"
"をご覧ください。 \"TYPE\" は \"sys\"、 \"user\"、 \"staff\" "
"を参照しているか、または他のスクリプトタイプのいずれかを参照している場合があります。\n"
"    "

#: ../src/httpd_unified.py:50
msgid ""
"\n"
"    Changing the \"$BOOLEAN\" boolean to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1\"\n"
"    "
msgstr ""
"\n"
"     \"$BOOLEAN\" boolean 値を「true」に変更すると、このアクセスを許可します：\n"
"     \"setsebool -P $BOOLEAN=1\"\n"
"     "

#: ../src/httpd_unified.py:57
msgid ""
"If you want to allow httpd to execute cgi scripts and to unify HTTPD "
"handling of all content files."
msgstr ""

#: ../src/httpd_unified.py:58
msgid ""
"you must tell SELinux about this by enabling the 'httpd_unified' and "
"'http_enable_cgi' booleans"
msgstr ""
"これについては、SELinux で 'httpd_unified' と 'http_enable_cgi' booleans "
"を有効にしなければいけません"

#: ../src/httpd_write_content.py:30
msgid ""
"\n"
"    SELinux prevented httpd $ACCESS access to $TARGET_PATH.\n"
"\n"
"    httpd scripts are not allowed to write to content without explicit\n"
"    labeling of all files.  If $TARGET_PATH is writable content. it needs\n"
"    to be labeled httpd_sys_rw_content_t or if all you need is append you "
"can label it httpd_sys_ra_content_t.   Please refer to 'man httpd_selinux' "
"for more information on setting up httpd and selinux.\n"
"    "
msgstr ""
"\n"
"    SELinux は httpd の $TARGET_PATH への $ACCESS アクセスを阻止しました。\n"
"\n"
"    httpd スクリプトは、すべてのファイルの明示的なラベルなしではコンテンツに \n"
"    書き込むよう許可されません。$TARGET_PATH が書き込み可能なコンテンツである \n"
"    場合、httpd_sys_rw_content_t のラベルが必要となり、追記が必要なだけの場合は、 "
"httpd_sys_ra_content_t のラベルを付けます。httpd と selinux のセットアップに関する 詳細は、'man "
"httpd_selinux' を参照して下さい。\n"
"    "

#: ../src/httpd_write_content.py:40 ../src/qemu_blk_image.py:45
#: ../src/samba_share.py:45 ../src/swapfile.py:45 ../src/xen_image.py:48
msgid "You need to change the label on '$FIX_TARGET_PATH'"
msgstr "'$FIX_TARGET_PATH' のラベルを変更する必要があります"

#: ../src/kernel_modules.py:29
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to modify "
"kernel configuration.\n"
"    "
msgstr "\n"
"    ご使用のシステムには深刻な侵害の可能性があります! $SOURCE_PATH がカーネル設定を変更しようとしました。\n"
"    "

#: ../src/kernel_modules.py:33
msgid ""
"\n"
"    SELinux has prevented $SOURCE from modifying $TARGET.  This denial\n"
"    indicates $SOURCE was trying to modify the way the kernel runs or to\n"
"    actually insert code into the kernel. All applications that need this\n"
"    access should have already had policy written for them.  If a "
"compromised\n"
"    application tries to modify the kernel this AVC will be generated. This "
"is a\n"
"    serious issue. Your system may very well be compromised.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE による $TARGET の修正を阻止しました。この阻止は、\n"
"    $SOURCE "
"がカーネルの実行方法を修正しようとしていたか、またはそのカーネルにコードを挿入しようとしていたことを示します。このアクセスを必要とするすべてのアプリケーションで、それぞれのポリシーが事前に作成されている必要がありました。セキュリティーのリスクにさらされている\n"
"    アプリケーションがカーネルを修正しようとすると、この AVC が生成されます。 これは\n"
"    重大な問題です。ご使用のシステムはすでにセキュリティーのリスクにさらされている可能性があります。\n"
"    "

#: ../src/kernel_modules.py:44 ../src/selinuxpolicy.py:44
msgid ""
"If you do not think $SOURCE_BASE_PATH should try $ACCESS access on "
"$TARGET_BASE_PATH."
msgstr ""

#: ../src/kernel_modules.py:45 ../src/selinuxpolicy.py:45
msgid ""
"you may be under attack by a hacker, since confined applications should not "
"need this access."
msgstr "制限したアプリケーションではこのアクセスは必要とされないため、 ハッカーから攻撃を受けている可能性があります。"

#: ../src/leaks.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH access to a leaked $TARGET_PATH file "
"descriptor.\n"
"    "
msgstr ""
"\n"
"    SELinux は 漏洩した $TARGET_PATH のファイル記述子へ $SOURCE_PATH  がアクセスすることを阻止しています。\n"
"    "

#: ../src/leaks.py:31
msgid ""
"\n"
"    SELinux denied access requested by the $SOURCE command. It looks like "
"this is either a leaked descriptor or $SOURCE output was redirected to a "
"file it is not allowed to access.  Leaks usually can be ignored since "
"SELinux is just closing the leak and reporting the error.  The application "
"does not use the descriptor, so it will run properly.  If this is a "
"redirection, you will not get output in the $TARGET_PATH.  You should "
"generate a bugzilla on selinux-policy, and it will get routed to the "
"appropriate package.  You can safely ignore this avc.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE コマンドにより要求されたアクセスを拒否しました。これは、 リークした記述子か、又は $SOURCE "
"の出力がアクセスの許可がないファイルへ再転送 されたように見えます。SELinux がリークを閉じてエラーを報告するため、リークは通常 "
"無視されます。アプリケーションは正常の稼働するように記述子を使用しません。これが 再転送であった場合、$TARGET_PATH "
"には出力を得ることはありません。selinux-policy 上に bugzilla "
"を生成すべきで、そうすると、それが適切なパッケージまで巡回します。この avc は 無視しても安全です。\n"
"     "

#: ../src/leaks.py:35
msgid ""
"\n"
"    You can generate a local policy module to allow this\n"
"    access - see <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"    "
msgstr ""
"\n"
"    ローカルポリシーモジュールを生成して、このアクセスを許可するように\n"
"    できます：<a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a> をご覧下さい。\n"
"    "

#: ../src/leaks.py:42
msgid ""
"If you want to ignore $SOURCE_BASE_PATH trying to $ACCESS access the "
"$TARGET_BASE_PATH $TARGET_CLASS, because you believe it should not need this "
"access."
msgstr ""

#: ../src/leaks.py:43
msgid ""
"You should report this as a bug.  \n"
"You can generate a local policy module to dontaudit this access."
msgstr "バグとして報告してください。  \n"
"ローカルのポリシーモジュールを生成すると、このアクセスを監査しないようにすることができます。"

#: ../src/leaks.py:44
msgid ""
"# ausearch -x $SOURCE_PATH --raw | audit2allow -D -M my-$SOURCE\n"
"# semodule -i my-$SOURCE.pp"
msgstr ""

#: ../src/mmap_zero.py:29
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH attempted to mmap "
"low kernel memory.\n"
"    "
msgstr ""
"\n"
"    ご使用のシステムには深刻な侵害の可能性があります! $SOURCE_PATH が低位置カーネルメモリーへの mmap を試行しました。\n"
"    "

#: ../src/mmap_zero.py:33
msgid ""
"\n"
"    SELinux has denied the $SOURCE the ability to mmap low area of the "
"kernel \n"
"    address space.  The ability to mmap a low area of the address space is \n"
"    configured by /proc/sys/kernel/mmap_min_addr.  Preventing such mappings \n"
"    helps protect against exploiting null deref bugs in the kernel. All \n"
"    applications that need this access should have already had policy "
"written \n"
"    for them.  If a compromised application tries to modify the kernel, this "
"AVC \n"
"    would be generated. This is a serious issue. Your system may very well "
"be \n"
"    compromised.\n"
"    "
msgstr ""

#: ../src/mmap_zero.py:46
msgid ""
"If you do not think $SOURCE_PATH should need to mmap low memory in the "
"kernel."
msgstr ""

#: ../src/mmap_zero.py:47
msgid "you may be under attack by a hacker, this is a very dangerous access."
msgstr "ハッカーから攻撃されている可能性があります。これは非常に危険なアクセスです。"

#: ../src/mounton.py:29
msgid ""
"\n"
"    SELinux prevented $SOURCE from mounting on the file or directory\n"
"    \"$TARGET_PATH\" (type \"$TARGET_TYPE\").\n"
"    "
msgstr ""
"\n"
"SELinux により \"$TARGET_PATH\" という名前のファイルまたはディレクトリ \n"
"(タイプ \"$TARGET_TYPE\") での $SOURCE によるマウントが阻止されました。\n"
"     "

#: ../src/mounton.py:34
msgid ""
"\n"
"    SELinux prevented $SOURCE from mounting a filesystem on the file\n"
"    or directory \"$TARGET_PATH\" of type \"$TARGET_TYPE\". By default\n"
"    SELinux limits the mounting of filesystems to only some files or\n"
"    directories (those with types that have the mountpoint attribute). The\n"
"    type \"$TARGET_TYPE\" does not have this attribute. You can change the\n"
"    label of the file or directory.\n"
"    "
msgstr ""
"\n"
"    SELinux は、$SOURCE がタイプ \"$TARGET_TYPE\"の \"$TARGET_PATH\" のファイルまたは\n"
"    ディレクトリー上にファイルシステムをマウントすることを阻止しました。デフォルトでは、\n"
"     SELinux は一部のファイルやディレクトリー (マウントポイント属性を持つタイプがあるもの) のみに \n"
"    ファイルシステムのマウントを制限します。タイプ \"$TARGET_TYPE\" "
"はこの属性を持ちません。ファイルまたはディレクトリーのラベルは変更することができます。\n"
"     "

#: ../src/mounton.py:43
msgid ""
"\n"
"    Changing the file_context to mnt_t will allow mount to mount the file "
"system:\n"
"    \"chcon -t mnt_t '$TARGET_PATH'.\"\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"mnt_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    file_context を mnt_t に変更すると、mount によるファイルシステムのマウントが 許可されます:\n"
"    \"chcon -t mnt_t '$TARGET_PATH'.\"\n"
"    また、完全な再ラベルの後でもそれらを保持できるように、システム上でデフォルトの "
"ファイルコンテキストファイルの変更もしなければなりません。\"semanage fcontext -a -t mnt_t "
"'$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/mounton.py:48
msgid "If you want to allow $SOURCE_BASE_PATH to mount on $TARGET_BASE_PATH."
msgstr ""

#: ../src/mounton.py:49
msgid "you must change the labeling on $TARGET_PATH."
msgstr "$TARGET_PATH のラベルを変更しなければいけません。"

#: ../src/mozplugger.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not expected that this "
"access is required by $SOURCE and this access may signal an intrusion "
"attempt. It is also possible that the specific version or configuration of "
"the application is causing it to require additional access.  mozplugger and "
"spice-xpi run applications within mozilla-plugins that require access to the "
"desktop, that the mozilla_plugin lockdown will not allow, so either you need "
"to turn off the mozilla_plugin lockdown or not use these packages.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE が要求したアクセスを拒否しました。$SOURCE "
"がこのアクセスを必要とすることは想定されておらず、このアクセスは侵入の試行である可能性があります。アプリケーションの特定のバージョンまたは設定により、追加アクセスが必要となっている可能性もあります。mozplugger "
"および spice-xpi は、デスクトップへのアクセスを必要とする mozilla-plugins "
"内でアプリケーションを実行し、mozilla_plugin ロックダウンは許可されないことから、mozilla_plugin "
"ロックダウンをオフにするか、これらのパッケージを使用しないようにする必要があります。\n"
" "

#: ../src/mozplugger.py:35
msgid ""
"\n"
"Either remove the mozplugger or spice-xpi package by executing 'yum remove "
"mozplugger spice-xpi' or turn off enforcement of SELinux over the Firefox "
"plugins. setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "
msgstr ""
"\n"
"'yum remove mozplugger spice-xpi' を実行して mozplluger または spice-xpi "
"のパッケージを削除するか、Firefox プラグインで SELinux の強制をオフにします。setsebool -P "
"unconfined_mozilla_plugin_transition 0"

#: ../src/mozplugger.py:43
msgid "you must turn off SELinux controls on the Firefox plugins."
msgstr "Firefox プラグインで SELinux の制御を全てオフにする必要があります。"

#: ../src/mozplugger_remove.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not\n"
"    expected that this access is required by $SOURCE and this access\n"
"    may signal an intrusion attempt. It is also possible that the specific\n"
"    version or configuration of the application is causing it to require\n"
"    additional access.\n"
"    "
msgstr ""
"\n"
"$SOURCE から要求されたアクセスは SELinux が拒否しました。⏎ このアクセスは $SOURCE で必要であると予測されていないため、⏎ "
"このアクセスは侵害の形跡かも知れません。また、アプリケーションの特定の⏎ バージョン、又は設定が余分なアクセスを要求する原因である可能性も⏎ あります。"

#: ../src/mozplugger_remove.py:39
msgid ""
"\n"
"Either remove the mozplluger package by executing 'yum remove mozplugger'\n"
"Or turn off enforcement of SELinux over the Firefox plugins.\n"
"setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "
msgstr ""
"\n"
"'yum remove mozplugger' を実行して mozplluger パッケージを削除するか、⏎ あるいは Firefox プラグイン上の "
"SELinux の強制をオフにします。⏎ setsebool -P unconfined_mozilla_plugin_transition 0⏎ "

#: ../src/mozplugger_remove.py:44
msgid ""
"If you want to to continue using SELinux Firefox plugin containment rather "
"then using mozplugger package"
msgstr ""

#: ../src/mozplugger_remove.py:45
msgid "you must remove the mozplugger package."
msgstr "mozplugger パッケージを削除する必要があります。"

#: ../src/openvpn.py:35
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled. openvpn is allowed to read content in home directory if "
"it\n"
"    is labeled correctly.\n"
"    "
msgstr ""

#: ../src/openvpn.py:41
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  \n"
"    # restorecon -R /root/.ssh\n"
"    "
msgstr ""

#: ../src/openvpn.py:49
msgid ""
"If you want to mv $TARGET_BASE_PATH to standard location so that "
"$SOURCE_BASE_PATH can have $ACCESS access"
msgstr ""

#: ../src/openvpn.py:51
msgid ""
"If you want to modify the label on $TARGET_BASE_PATH so that "
"$SOURCE_BASE_PATH can have $ACCESS access on it"
msgstr ""

#: ../src/openvpn.py:55
msgid "you must move the cert file to the ~/.cert directory"
msgstr "cert ファイルを ~/.cert directory に移動しなければいけません"

#: ../src/openvpn.py:57 ../src/sshd_root.py:48
msgid "you must fix the labels."
msgstr "ラベルを修正しなければいけません。"

#: ../src/public_content.py:31
msgid ""
"\n"
"    SELinux denied access to $TARGET_PATH requested by $SOURCE.\n"
"    $TARGET_PATH has a context used for sharing by a different program. If "
"you\n"
"    would like to share $TARGET_PATH from $SOURCE also, you need to\n"
"    change its file context to public_content_t.  If you did not intend to\n"
"    allow this access, this could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"SELinux で $SOURCE が要求した $TARGET_PATH へのアクセスが拒否されました。\n"
"$TARGET_PATH には、 別のプログラムで共有に使用されるコンテキストがあります。\n"
"$SOURCE からも $TARGET_PATH を共有したい場合、 そのファイルコンテキストを \n"
"public_content_t に変更する必要があります。 このアクセスを意図的に許可して\n"
"いなかった場合、 不正侵入が行なわれた可能性があります。\n"
"    "

#: ../src/public_content.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -t public_content_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"public_content_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"chcon -t public_content_t '$TARGET_PATH' を実行すると、 ファイルのコンテキストを\n"
"変更することができます。 また、 完全な再ラベル付けが行なわれた後も変更した\n"
"ファイルコンテキストを維持させたい場合には、 システム上でデフォルトのファイル\n"
"コンテキストのファイルも変更する必要があります。 \"semanage fcontext -a -t public_content_t "
"'$FIX_TARGET_PATH'\"    "

#: ../src/public_content.py:50
msgid "If you want to treat $TARGET_BASE_PATH as public content"
msgstr ""

#: ../src/public_content.py:51
msgid ""
"You need to change the label on $TARGET_BASE_PATH to public_content_t or "
"public_content_rw_t."
msgstr ""
"$TARGET_BASE_PATH のラベルを public_content_t または public_content_rw_t "
"に変更する必要があります。"

#: ../src/qemu_blk_image.py:31
msgid ""
"\n"
"    SELinux denied qemu access to the block device $TARGET_PATH.\n"
"    If this is a virtualization image, it needs to be labeled with a "
"virtualization file context (virt_image_t). You can relabel $TARGET_PATH to "
"be virt_image_t using chcon.  You also need to execute semanage fcontext -a -"
"t virt_image_t '$FIX_TARGET_PATH' to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a qemu\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux はブロックデバイス $TARGET_PATH への qemu のアクセスを拒否しました。\n"
"    これが仮想化イメージの場合は、仮想化ファイルコンテキスト (virt_image_t) でラベルが付けられる必要があります。chcon "
"を使用して $TARGET_PATH を virt_image_t  に 再度ラベル付けすることができます。 また、semanage fcontext -"
"a - t virt_image_t '$FIX_TARGET_PATH'も 実行して、この新しいパスをシステムデフォルトに    "
"追加する必要があります。$TARGET_PATH を qemu イメージとして使用するつもりでなかった場合は、\n"
"     それは、バグを示すか、又は不正侵入の試みを示すことになります。\n"
"    "

#: ../src/qemu_blk_image.py:38 ../src/qemu_file_image.py:41
msgid ""
"\n"
"    You can alter the file context by executing chcon -t virt_image_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"virt_image_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"   chcon  -t virt_image_t '$TARGET_PATH' を実行すると、ファイルコンテキストの 変更ができます。\n"
"    "
"また、完全な再ラベルの後でもそれらが保持できるようにシステム上でデフォルトのファイルコンテキストファイルの変更もしなければなりません。\"semanage "
"fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/qemu_blk_image.py:46
msgid ""
"# semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"

#: ../src/qemu_file_image.py:31
msgid ""
"\n"
"    SELinux denied qemu access to $TARGET_PATH.\n"
"    If this is a virtualization image, it has to have a file context label "
"of\n"
"    virt_image_t. The system is setup to label image files in directory./var/"
"lib/libvirt/images\n"
"    correctly.  We recommend that you copy your image file to /var/lib/"
"libvirt/images.\n"
"    If you really want to have your qemu image files in the current "
"directory, you can relabel $TARGET_PATH to be virt_image_t using chcon.  You "
"also need to execute semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH' "
"to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a qemu\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
" SELinux により $TARGET_PATH への qemu のアクセスが拒否されました。\n"
"これが仮想化イメージの場合は、 virt_image_t のファイルコンテキストラベルを持たせる\n"
"必要があります。 システムは /var/lib/libvirt/images ディレクトリ内でイメージファイル\n"
"のラベル付けを行なうよう正しく設定されています。 使用するイメージファイルを \n"
"var/lib/libvirt/images にコピーすることをお勧めします。 qemu イメージファイルを\n"
"どうしても現在のディレクトリ内に配置する必要がある場合は、 chcon を使用して \n"
"$TARGET_PATH に virt_image_t  のラベルを付け直してください。 また、\n"
"semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH' を実行して、 この新しいパスを\n"
"システムのデフォルト設定に追加する必要があります。 $TARGET_PATH を qemu イメージ\n"
"として使用する意図がなかった場合は、 バグまたは不正侵入の試行を示している可能性があります。"

#: ../src/qemu_file_image.py:48
msgid "If $TARGET_BASE_PATH is a virtualization target"
msgstr ""

#: ../src/restorecon.py:57
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon '$TARGET_PATH', if this file is a "
"directory,\n"
"    you can recursively restore using restorecon -R '$TARGET_PATH'.\n"
"    "
msgstr ""
"\n"
"restorecon コマンドを実行することにより、 このファイルにデフォルトの\n"
"システムコンテキストを復元することができます (restorecon '$TARGET_PATH')。\n"
"このファイルがディレクトリの場合には、 restorecon -R '$TARGET_PATH' を\n"
"使用して再帰的に復元することができます。\n"
"    "

#: ../src/restorecon.py:64
#, python-format
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled.  $TARGET_PATH default SELinux type is\n"
"    <B>%s</B>, but its current type is <B>$TARGET_TYPE</B>. Changing\n"
"    this file back to the default type may fix your problem.\n"
"    <p>\n"
"    File contexts can be assigned to a file in the following ways.\n"
"    <ul>\n"
"        <li>Files created in a directory receive the file context of the "
"parent directory by default.\n"
"        <li>The SELinux policy might override the default label inherited "
"from the parent directory by\n"
"            specifying a process running in context A which creates a file "
"in a directory labeled B\n"
"            will instead create the file with label C. An example of this "
"would be the dhcp client running\n"
"            with the dhclient_t type and creating a file in the directory /"
"etc. This file would normally\n"
"            receive the etc_t type due to parental inheritance but instead "
"the file\n"
"            is labeled with the net_conf_t type because the SELinux policy "
"specifies this.\n"
"        <li>Users can change the file context on a file using tools such as "
"chcon, or restorecon.\n"
"    </ul>\n"
"    This file could have been mislabeled either by user error, or if an "
"normally confined application\n"
"    was run under the wrong domain.\n"
"    <p>\n"
"    However, this might also indicate a bug in SELinux because the file "
"should not have been labeled\n"
"    with this type.\n"
"    <p>\n"
"    If you believe this is a bug, please file a bug report against this "
"package.\n"
"    "
msgstr ""

#: ../src/restorecon.py:90
#, python-format
msgid ""
"If you want to fix the label. \n"
"$TARGET_PATH default label should be %s."
msgstr ""

#: ../src/restorecon.py:96
msgid ""
"you can run restorecon. The access attempt may have been stopped due to "
"insufficient permissions to access a parent directory in which case try to "
"change the following command accordingly."
msgstr ""

#: ../src/restorecon.py:105 ../src/restorecon_source.py:73
msgid "Restore\n"
"Context"
msgstr "コンテキストの\n"
"復元"

#: ../src/restorecon_source.py:39
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon '$SOURCE_PATH'.\n"
"    "
msgstr ""
"\n"
"    restorecon コマンドを実行することにより、このファイルのコンテキストを\n"
"    システムの初期値に復元できます。 restorecon '$SOURCE_PATH' 。\n"
"    "

#: ../src/restorecon_source.py:45
#, python-format
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $SOURCE_PATH may\n"
"    be mislabeled.  $SOURCE_PATH default SELinux type is\n"
"    <B>%s</B>, but its current type is <B>$SOURCE_TYPE</B>. Changing\n"
"    this file back to the default type may fix your problem.\n"
"    <p>\n"
"    This file could have been mislabeled either by user error, or if an "
"normally confined application\n"
"    was run under the wrong domain.\n"
"    <p>\n"
"    However, this might also indicate a bug in SELinux because the file "
"should not have been labeled\n"
"    with this type.\n"
"    <p>\n"
"    If you believe this is a bug, please file a bug report against this "
"package.\n"
"    "
msgstr ""

#: ../src/restorecon_source.py:60
#, python-format
msgid ""
"If you want to fix the label. \n"
"$SOURCE_PATH default label should be %s."
msgstr ""

#: ../src/restorecon_source.py:65
msgid "you can run restorecon."
msgstr "restorecon を実行することができます。"

#: ../src/rsync_data.py:31
msgid ""
"\n"
"    SELinux denied RSYNC access to $TARGET_PATH.\n"
"    If this is an RSYNC repository, it has to have a file context label of\n"
"    rsync_data_t. If you did not intend to use $TARGET_PATH as an RSYNC "
"repository,\n"
"    this message could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/rsync_data.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t rsync_data_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"rsync_data_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -R -t rsync_data_t '$TARGET_PATH' を実行すると、ファイルコンテキストを変更することが出来ます。\n"
"    また、それらを完全な再ラベルの後でも保持できるようにシステム上でデフォルトのファイルコンテキストも変更しなければなりません。\"semanage "
"fcontext -a -t rsync_data_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/rsync_data.py:45
msgid "If $TARGET_BASE_PATH should be shared via the RSYNC daemon"
msgstr ""

#: ../src/rsync_data.py:46
msgid "You need to change the label on $TARGET_BASE_PATH"
msgstr "$TARGET_BASE_PATH のラベルを変更する必要があります。"

#: ../src/samba_share.py:27
msgid ""
"\n"
"    SELinux is preventing Samba ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への Samba ($SOURCE_PATH) による \"$ACCESS\" "
"アクセスを阻止しています。\n"
"    "

#: ../src/samba_share.py:31
msgid ""
"\n"
"    SELinux denied samba access to $TARGET_PATH.\n"
"    If you want to share this directory with samba it has to have a file "
"context label of\n"
"    samba_share_t. If you did not intend to use $TARGET_PATH as a samba "
"repository,\n"
"    this message could indicate either a bug or an intrusion attempt.\n"
"    Please refer to 'man samba_selinux' for more information on setting up "
"Samba and SELinux.\n"
"    "
msgstr ""

#: ../src/samba_share.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t samba_share_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"samba_share_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -R -t samba_share_t '$TARGET_PATH' を実行すると、ファイルコンテキストを変更することができます。\n"
"    "
"また、完全な再ラベルの後にもそれらを保持するためにシステム上でデフォルトのファイルコンテキストファイルも変更しなければなりません。\"semanage "
"fcontext -a -t samba_share_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/samba_share.py:53
#, python-format
msgid ""
"# semanage fcontext -a -t samba_share_t '$FIX_TARGET_PATH%s'\n"
"# restorecon %s -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t samba_share_t '$FIX_TARGET_PATH%s'\n"
"# restorecon %s -v '$FIX_TARGET_PATH'"

#: ../src/sandbox_connect.py:33
msgid ""
"\n"
"    SELinux has denied $SOURCE from connecting to a network port "
"$PORT_NUMBER within a sandbox.\n"
"    If $SOURCE should be allowed to connect on $PORT_NUMBER, you need to use "
"a different sandbox type like sandbox_web_t or sandbox_net_t.  \n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to connect to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/sandbox_connect.py:41
msgid ""
"\n"
"    If you want to allow $SOURCE to connect to $PORT_NUMBER, you can execute "
"\n"
"\n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    "
msgstr ""
"\n"
"    $SOURCE による $PORT_NUMBER への接続を許可する場合は、以下を実行します。\n"
"\n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    "

#: ../src/sandbox_connect.py:49
msgid ""
"you need to modify the sandbox type. sandbox_web_t or sandbox_net_t.\n"
"For example:\n"
"sandbox -X -t sandbox_net_t $SOURCE_PATH\n"
"Please read 'sandbox' man page for more details.\n"
msgstr ""
"サンドボックスタイプを変更する必要があります。sandbox_web_t または sandbox_net_t です。 \n"
"例:\n"
"sandbox -X -t sandbox_net_t $SOURCE_PATH\n"
"詳細は 'sandbox' の man ページを参照してください。\n"

#: ../src/selinuxpolicy.py:29
msgid "\n"
"    Your system may be seriously compromised!\n"
"    "
msgstr "\n"
"    ご使用のシステムには深刻な侵害の可能性があります! \n"
"    "

#: ../src/selinuxpolicy.py:33
msgid ""
"\n"
"    SELinux has prevented $SOURCE from modifying $TARGET.  This denial\n"
"    indicates $SOURCE was trying to modify the selinux policy configuration.\n"
"    All applications that need this access should have already had policy\n"
"    written for them.  If a compromised application tries to modify the "
"SELinux\n"
"    policy this AVC will be generated. This is a serious issue. Your system\n"
"    may very well be compromised.\n"
"    "
msgstr ""
"\n"
"    SELinux は、$SOURCE による $TARGET の修正を阻止しました。この阻止は\n"
"    $SOURCE が selinux ポリシー設定を修正しようとしていたことを 示します。\n"
"    "
"このアクセスを必要とするすべてのアプリケーションで、それぞれのポリシーが事前に設定されている必要がありました。セキュリティーのリスクにさらされているアプリケーションが "
"SELinux ポリシーを修正しようとすると、この AVC が生成されます。これは重大な問題です。 "
"ご使用のシステムはすでにセキュリティーのリスクにさらされている可能性があります。\n"
"    "

#: ../src/setenforce.py:27
msgid "If you did not directly cause this AVC through testing."
msgstr ""

#: ../src/setenforce.py:28
msgid "if you think that you might have been hacked"
msgstr "これがハッキングされていると考える場合"

#: ../src/setenforce.py:32
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to modify "
"SELinux enforcement.\n"
"    "
msgstr ""
"\n"
"    ご使用のシステムには深刻な侵害の可能性があります! $SOURCE_PATH が SELinux 強制を修正しようとしました。\n"
"    "

#: ../src/setenforce.py:36
msgid ""
"\n"
"    SELinux has prevented $SOURCE from writing to a file under /sys/fs/"
"selinux.\n"
"    Files under /sys/fs/selinux control the way SELinux is configured.\n"
"    All programs that need to write to files under /sys/fs/selinux should "
"have already had policy\n"
"    written for them. If a compromised application tries to turn off SELinux\n"
"    this AVC will be generated. This is a serious issue. Your system may "
"very\n"
"    well be compromised.\n"
"    "
msgstr ""

#: ../src/setenforce.py:48
msgid "If you believe $SOURCE_PATH tried to disable SELinux."
msgstr ""

#: ../src/setenforce.py:49
msgid ""
"you may be under attack by a hacker, since confined applications should "
"never need this access."
msgstr "このアクセスが制限したアプリケーションで必要とされることは絶対にないため、 ハッカーからの攻撃を受けている可能性があります。"

#: ../src/sshd_root.py:36
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled. sshd is allowed to read content in /root/.ssh directory "
"if it\n"
"    is labeled correctly.\n"
"    "
msgstr ""

#: ../src/sshd_root.py:42
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.\n"
"    # restorecon -R /root/.ssh\n"
"    "
msgstr ""

#: ../src/sshd_root.py:55
msgid "Restore Context"
msgstr "コンテキストの復元"

#: ../src/swapfile.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" to $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への $SOURCE_PATH による \"$ACCESS\" を阻止しています。\n"
"    "

#: ../src/swapfile.py:31
msgid ""
"\n"
"    SELinux denied $SOURCE access to $TARGET_PATH.\n"
"    If this is a swapfile, it has to have a file context label of\n"
"    swapfile_t. If you did not intend to use\n"
"    $TARGET_PATH as a swapfile, this message could indicate either a bug or "
"an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/swapfile.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -t swapfile_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"swapfile_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -t swapfile_t '$TARGET_PATH' を実行すると、ファイルコンテキストを 変更することができます。\n"
"    また、完全な再ラベルの後でもそれらを保持するために、システム上でデフォルトの "
"ファイルコンテキストファイルも変更しなければなりません。\"semanage fcontext -a -t swapfile_t "
"'$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/sys_module.py:28
msgid ""
"If you do not believe your $SOURCE_PATH should be modifying the kernel, by "
"loading kernel modules"
msgstr ""

#: ../src/sys_module.py:29
msgid "You might have been hacked."
msgstr "あなたはハッキングされているかもしれません。"

#: ../src/sys_module.py:33
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to load a "
"kernel module.\n"
"    "
msgstr ""
"\n"
"    ご使用のシステムには深刻な侵害の可能性があります! $SOURCE_PATH がカーネルモジュールをロードしようとしました。\n"
"    "

#: ../src/sys_module.py:37
msgid ""
"\n"
"    SELinux has prevented $SOURCE from loading a kernel module.\n"
"    All confined programs that need to load kernel modules should have "
"already had policy\n"
"    written for them. If a compromised application\n"
"    tries to modify the kernel this AVC will be generated. This is a serious\n"
"    issue. Your system may very well be compromised.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE による カーネルモジュールのロードを阻止しました。\n"
"    "
"カーネルモジュールをロードする必要のあるすべての制限されたプログラムで、それぞれのポリシーが事前に作成されている必要がありました。セキュリティーのリスクにさらされているアプリケーションがカーネルを修正しようとすると、この "
"AVC が生成されます。これは 重大な問題です。ご使用のシステムはすでにセキュリティーのリスクにさらされている可能性があります。\n"
"    "

#: ../src/sys_module.py:46
msgid ""
"If you do not believe that $SOURCE_PATH should be attempting to modify the "
"kernel by loading a kernel module."
msgstr ""

#: ../src/sys_module.py:47
msgid "A process might be attempting to hack into your system."
msgstr "あるプロセスがあなたのシステムへハッキングしようとしているかもしれません。"

#: ../src/sys_resource.py:28
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH the \"sys_resource\" capability.\n"
"    "
msgstr "\n"
"    SELinux は $SOURCE_PATH の \"sys_resource\" 機能を阻止しています。\n"
"    "

#: ../src/sys_resource.py:32
msgid ""
"\n"
"    Confined domains should not require \"sys_resource\". This usually means "
"that     your system is running out some system resource like disk space, "
"memory, quota etc. Please clear up the disk and this\n"
"    AVC message should go away. If this AVC continues after you clear up the "
"disk space, please report this as a bug.\n"
"    "
msgstr ""
"\n"
"制限されたドメインでは \"sys_resource\" を必要としません。 つまり、 通常はディスク領域、 メモリー、 "
"クォータなどのシステムリソースがそのシステムに不足していることになります。 ディスク領域を解放すると、この AVC "
"メッセージは表示されなくなるはずです。 ディスク領域を解放しても AVC メッセージが表示される場合は、この問題をバグとして報告してください。"

#: ../src/sys_resource.py:39
msgid ""
"If you do not want processes to require capabilities to use up all the "
"system resources on your system;"
msgstr ""

#: ../src/sys_resource.py:40
msgid ""
"you need to diagnose why your system is running out of system resources and "
"fix the problem.\n"
"\n"
"According to /usr/include/linux/capability.h, sys_resource is required to:\n"
"\n"
"/* Override resource limits. Set resource limits. */\n"
"/* Override quota limits. */\n"
"/* Override reserved space on ext2 filesystem */\n"
"/* Modify data journaling mode on ext3 filesystem (uses journaling\n"
"   resources) */\n"
"/* NOTE: ext2 honors fsuid when checking for resource overrides, so\n"
"   you can override using fsuid too */\n"
"/* Override size restrictions on IPC message queues */\n"
"/* Allow more than 64hz interrupts from the real-time clock */\n"
"/* Override max number of consoles on console allocation */\n"
"/* Override max number of keymaps */\n"
msgstr ""

#: ../src/vbetool.py:30
msgid ""
"\n"
"    SELinux has prevented vbetool from performing an unsafe memory operation."
"\n"
"    "
msgstr "\n"
"    SELinux は vbetool による安全でないメモリー操作を阻止 しました\n"
"    "

#: ../src/vbetool.py:34
msgid ""
"\n"
"SELinux denied an operation requested by $SOURCE, a program used\n"
"to alter video hardware state.  This program is known to use\n"
"an unsafe operation on system memory but so are a number of\n"
"malware/exploit programs which masquerade as vbetool.  This tool is used to\n"
"reset video state when a machine resumes from a suspend.  If your machine\n"
"is not resuming properly your only choice is to allow this\n"
"operation and reduce your system security against such malware.\n"
"\n"
"    "
msgstr ""
"\n"
"SELinux は ビデオハードウェアの状態を変更するためのプログラムである $SOURCE によって \n"
"要求された操作を拒否しました。vbetool として偽装する他の多くの \n"
"違法/悪意プログラムと同様に、このプログラムはシステムメモリー上で \n"
"安全でない操作をすることで知られています。このツールはマシンがサスペンドから 復帰する際に \n"
"ビデオの状態をリセットするために使用されます。使用中のマシンが正常に復帰しない場合は、\n"
" この操作を許可するのが唯一の選択肢となり、悪意プログラムに対するシステムのセキュリティーは低下します。\n"
"\n"
"     "

#: ../src/vbetool.py:45 ../src/wine.py:56
msgid ""
"\n"
"If you decide to continue to run the program in question you will need\n"
"to allow this operation.  This can be done on the command line by\n"
"executing:\n"
"\n"
"# setsebool -P mmap_low_allowed 1\n"
msgstr ""
"\n"
"問題になっているプログラムを継続して実行する決定をした場合は、この \n"
"操作を許可する必要があります。これは以下のようにコマンドラインで \n"
"実行できます:\n"
"\n"
"# setsebool -P mmap_low_allowed 1\n"

#: ../src/vbetool.py:55
msgid ""
"If you want to ignore this AVC because it is dangerous and your machine "
"seems to be working correctly."
msgstr ""

#: ../src/vbetool.py:56
msgid ""
"you must tell SELinux about this by enabling the vbetool_mmap_zero_ignore "
"boolean."
msgstr ""
"これについては、SELinux に vbetool_mmap_zero_ignore boolean を有効にする設定をしなければいけません。"

#: ../src/vbetool.py:62 ../src/wine.py:73
msgid "Turn off memory protection"
msgstr "メモリーの保護をオフにします"

#: ../src/wine.py:31
msgid ""
"\n"
"    SELinux has prevented wine from performing an unsafe memory operation.\n"
"    "
msgstr "\n"
"    SELinux は wine による安全でないメモリー操作の実行を阻止しました。\n"
"    "

#: ../src/wine.py:35
msgid ""
"\n"
"SELinux denied an operation requested by wine-preloader, a program used\n"
"to run Windows applications under Linux.  This program is known to use\n"
"an unsafe operation on system memory but so are a number of\n"
"malware/exploit programs which masquerade as wine.  If you were\n"
"attempting to run a Windows program your only choices are to allow this\n"
"operation and reduce your system security against such malware or to\n"
"refrain from running Windows applications under Linux.  If you were not\n"
"attempting to run a Windows application this indicates you are likely\n"
"being attacked by some for of malware or program trying to exploit your\n"
"system for nefarious purposes.\n"
"\n"
"Please refer to\n"
"\n"
"http://wiki.winehq.org/PreloaderPageZeroProblem\n"
"\n"
"Which outlines the other problems wine encounters due to its unsafe use\n"
"of memory and solutions to those problems.\n"
"\n"
"    "
msgstr ""
"\n"
"SELinux は Linux 上で Windows アプリケーションを実行するのに使用されるプログラムである \n"
"wine-preloader で要求された操作を拒否しました。このプログラムは wine として偽装した \n"
"違法/悪意プログラムの多くと同様に、システムメモリー上で安全でない操作を使用することで \n"
"知られています。Windows "
"プログラムを実行しようとしている場合は、選択可能なオプションとして、この操作を許可して、そのような悪意のあるプログラムに対するシステムセキュリティーを低下させるか、または "
"Linux 上で Windows アプリケーションの実行を避けることができます。Windows アプリケーションの \n"
"実行を試行していない場合は、これは不正目的でユーザーのシステムを悪用しようとしている悪意のあるプログラムから攻撃を受けていることを示します。\n"
"\n"
"以下のサイトを参照して下さい：\n"
"\n"
"http://wiki.winehq.org/PreloaderPageZeroProblem\n"
"\n"
"このサイトには、メモリーの安全でない使用のために wine が遭遇する他の問題とその問題へのソリューションの概要が記載されています。\n"
"\n"
"    "

#: ../src/wine.py:66
msgid ""
"If you want to ignore this AVC because it is dangerous and your wine "
"applications are working correctly."
msgstr ""

#: ../src/wine.py:67
msgid ""
"you must tell SELinux about this by enabling the wine_mmap_zero_ignore "
"boolean."
msgstr "これについては、SELinux に wine_mmap_zero_ignore を有効にする設定をしなければいけません。"

#: ../src/xen_image.py:27
msgid ""
"\n"
"    SELinux is preventing xen ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への xen ($SOURCE_PATH) による  \"$ACCESS\" "
"アクセスを阻止しています。\n"
"    "

#: ../src/xen_image.py:31
msgid ""
"\n"
"    SELinux denied xen access to $TARGET_PATH.\n"
"    If this is a XEN image, it has to have a file context label of\n"
"    xen_image_t. The system is setup to label image files in directory /var/"
"lib/xen/images\n"
"    correctly.  We recommend that you copy your image file to /var/lib/xen/"
"images.\n"
"    If you really want to have your xen image files in the current "
"directory, you can relabel $TARGET_PATH to be xen_image_t using chcon.  You "
"also need to execute semanage fcontext -a -t xen_image_t '$FIX_TARGET_PATH' "
"to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a xen\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"SELinux により $TARGET_PATH への xen のアクセスが拒否されました。\n"
"これが XEN イメージの場合は、 xen_image_t のファイルコンテキストラベルを持たせる\n"
"必要があります。 システムは /var/lib/xen/images ディレクトリ内でイメージファイル\n"
"にラベル付けを行なうよう正しく設定されています。 使用するイメージファイルを \n"
"/var/lib/xen/images ディレクトリにコピーすることをお勧めします。 どうしても xen イメージ\n"
"ファイルを現在のディレクトリに配置する必要がある場合は、 chcon  を使用して \n"
"$TARGET_PATH に xen_image_t のラベルを付け直してください。 \n"
"また、 semanage fcontext -a -t xen_image_t '$FIX_TATGET_PATH' を実行して、 この新しい\n"
"パスをシステムのデフォルト設定に追加する必要があります。 $TARGET_PATH を xen イメージ\n"
"として使用する意図がなかった場合は、 バグまたは不正侵入の試行を示している可能性があります。"

#: ../src/xen_image.py:41
msgid ""
"\n"
"    You can alter the file context by executing chcon -t xen_image_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"xen_image_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"   chcon -t xen_image_t '$TARGET_PATH' を実行すると、ファイルコンテキストの 変更ができます。\n"
"    "
"また、完全な再ラベルの後でもそれらが保持できるようにシステム上でデフォルトのファイルコンテキストファイルの変更もしなければなりません。\"semanage "
"fcontext -a -t xen_image_t '$FIX_TARGET_PATH'\"\n"
"    "
