# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# sandeeps <sshedmak@redhat.com>, 2012
# sandeeps <sshedmak@redhat.com>, 2012-2013
# sandeeps <sshedmak@redhat.com>, 2012
# Vit Mojzis <vmojzis@redhat.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-11-20 17:16+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2017-09-01 08:32-0400\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Marathi (http://www.transifex.com/projects/p/fedora/language/"
"mr/)\n"
"Language: mr\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Zanata 3.9.6\n"

#: ../src/allow_anon_write.py:27
msgid ""
"\n"
"    SELinux policy is preventing an httpd script from writing to a public\n"
"    directory.\n"
"    "
msgstr ""
"\n"
"    SELinux करार httpd स्क्रीप्टला पब्लिक डिरेक्ट्री वर\n"
"    लिहीण्यापासून रोखले.\n"
"     "

#: ../src/allow_anon_write.py:32
msgid ""
"\n"
"    SELinux policy is preventing an httpd script from writing to a public\n"
"    directory.  If httpd is not setup to write to public directories, this\n"
"    could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux करार httpd स्क्रिप्टला पब्लिक\n"
"    डिरेक्ट्रीवर लिहीण्यापासून रोखले.  httpd पब्लिक डिरेक्ट्रीवर लिहीण्यास "
"सेटअप केले नसल्यास, हे\n"
"    अवैध प्रवेश प्रयत्न ठरेल.\n"
"    "

#: ../src/allow_anon_write.py:38
msgid ""
"\n"
"    If httpd scripts should be allowed to write to public directories you "
"need to turn on the $BOOLEAN boolean and change the file context of the "
"public directory to public_content_rw_t.  Read the httpd_selinux\n"
"    man page for further information:\n"
"    \"setsebool -P $BOOLEAN=1; chcon -t public_content_rw_t <path>\"\n"
"    You must also change the default file context labeling files on the "
"system in order to preserve public directory labeling even on a full relabel."
"  \"semanage fcontext -a -t public_content_rw_t <path>\"\n"
"    "
msgstr ""
"\n"
"    httpd स्क्रिप्टला पब्लिक डिरेक्ट्रीवर लिहण्याची परवानगी द्यायची असल्यास "
"तुम्हाला $BOOLEAN बूलीयन सुरू करावे लागेल व पब्लिक डिरेक्ट्रीचे संदर्भ "
"public_content_rw_t असे करावे लागेल.  अधिक माहिती करीता httpd_selinux\n"
"    man पान पहा:\n"
"    \"setsebool -P $BOOLEAN=1; chcon -t public_content_rw_t <path>\"\n"
"    पूर्णतया पुनःलेबल झाल्यावरहि पब्लिक डिरेक्ट्रिचे लेबलिंग साठवण्याकरिता "
"प्रणालीवरील पूर्वनिर्धारित फाइल संदर्भ बदलणे आवश्यक आहे.  \"semanage "
"fcontext -a -t public_content_rw_t <path>\"\n"
"    "

#: ../src/allow_anon_write.py:44
msgid ""
"If you want to allow $SOURCE_PATH to be able to write to shared public "
"content"
msgstr ""

#: ../src/allow_anon_write.py:45
msgid ""
"you need to change the label on $TARGET_PATH to public_content_rw_t, and "
"potentially turn on the allow_httpd_sys_script_anon_write boolean."
msgstr ""
"$TARGET_PATH वरील लेबलला public_content_rw_t करीता बदलणे, व  "
"allow_httpd_sys_script_anon_write बूलियन सुर करणे आवश्यक आहे."

#: ../src/allow_execheap.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from changing the access\n"
"    protection of memory on the heap.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH ला heap वरील स्मृतीच्या\n"
"    सुरक्षा करीता प्रवेश देण्यापासून रोखत आहे.\n"
"    "

#: ../src/allow_execheap.py:32
msgid ""
"\n"
"    The $SOURCE application attempted to change the access protection of "
"memory on\n"
"    the heap (e.g., allocated using malloc).  This is a potential security\n"
"    problem.  Applications should not be doing this. Applications are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  If $SOURCE does not "
"work and\n"
"    you need it to work, you can configure SELinux temporarily to allow\n"
"    this access until the application is fixed. Please file a bug\n"
"    report against this package.\n"
"    "
msgstr ""
"\n"
"    $SOURCE ऍप्लीकेशनने हीप (उ.दा., malloc चा वापर करून वाटप केलेले) वरील "
"स्मृतीचे प्रवेश बदलविण्याचा\n"
"    प्रयत्न केला. ही एक\n"
"    सुरक्षा त्रुटी आहे.\n"
"    ऍप्लीकेशनने असे केले नाही पाहिजे. अनुप्रयोग\n"
"    कधिकधी अयोग्यरित्या कोड केले जाते व ही परनावगी करीता सहमती मांगतात.  \n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"स्मृती सुरक्षा चाचणी</a>\n"
"    वेब पान तुम्हाला ही आवश्यकता काढूण टाकण्यास विश्लेषीत करते.  $SOURCE "
"कार्य करतनाही व\n"
"    तुम्हाला ते कार्यरत करण्याची आवश्यकता आहे, तुम्ही SELinux तात्पूरते\n"
"    अनुप्रयोग निर्धारीत होईपर्यंत संयोजीत करू शकता. कृपया या संकुलच्या "
"विरूध्द बग\n"
"    अहवाल सादर करा.\n"
"    "

#: ../src/allow_execheap.py:44
msgid ""
"\n"
"    If you want $SOURCE to continue, you must turn on the\n"
"    $BOOLEAN boolean.  Note: This boolean will affect all applications\n"
"    on the system.\n"
"    "
msgstr ""
"\n"
"    $SOURCE ला पुढे चालवायचे असल्यास, तुम्ही\n"
"    $BOOLEAN बूलीयन असे निश्चित केले पाहिजे.  लक्षात घ्या: या बूलीयनमुळे इतर\n"
"    सर्व अनुप्रयोग प्रभावित ठरतात\n"
"    "

#: ../src/allow_execheap.py:50
msgid ""
"If you do not think $SOURCE_PATH should need to map heap memory that is both "
"writable and executable."
msgstr ""

#: ../src/allow_execheap.py:51
msgid "you need to report a bug. This is a potentially dangerous access."
msgstr "तुम्हाला बग कळवावे लागेल. हे प्रवेश घातक ठरू शकते."

#: ../src/allow_execheap.py:52 ../src/allow_execstack.py:91
#: ../src/kernel_modules.py:46 ../src/mmap_zero.py:48
#: ../src/selinuxpolicy.py:46 ../src/setenforce.py:29 ../src/setenforce.py:50
#: ../src/sys_module.py:30 ../src/sys_module.py:48
msgid "Contact your security administrator and report this issue."
msgstr "सुरक्षा प्रशासकाशी संपर्क करा व हि अडचण कळवा."

#: ../src/allow_execmod.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from loading $TARGET_PATH which "
"requires text relocation.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH ला $TARGET_PATH लोड करण्यापासून रोखत आहे ज्यांस "
"पाठ्य पुन्हस्थानंतरनची आवश्यकता आहे.\n"
"    "

#: ../src/allow_execmod.py:33
msgid ""
"\n"
"    The $SOURCE application attempted to load $TARGET_PATH which\n"
"    requires text relocation.  This is a potential security problem.\n"
"    Most libraries do not need this permission. Libraries are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  You can configure\n"
"    SELinux temporarily to allow $TARGET_PATH to use relocation as a\n"
"    workaround, until the library is fixed. Please file a\n"
"bug report.\n"
"    "
msgstr ""

#: ../src/allow_execmod.py:45
msgid ""
"\n"
"    The $SOURCE application attempted to load $TARGET_PATH which\n"
"    requires text relocation.  This is a potential security problem.\n"
"    Most libraries should not need this permission.   The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">\n"
"    SELinux Memory Protection Tests</a>\n"
"    web page explains this check.  This tool examined the library and it "
"looks\n"
"    like it was built correctly. So setroubleshoot can not determine if this\n"
"    application is compromised or not.  This could be a serious issue. Your\n"
"    system may very well be compromised.\n"
"\n"
"    Contact your security administrator and report this issue.\n"
"\n"
"    "
msgstr ""

#: ../src/allow_execmod.py:62
msgid ""
"\n"
"    If you trust $TARGET_PATH to run correctly, you can change the\n"
"    file context to textrel_shlib_t. \"chcon -t textrel_shlib_t\n"
"    '$TARGET_PATH'\"\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"textrel_shlib_t '$FIX_TARGET_PATH'\"\n"
"\n"
"    "
msgstr ""

#: ../src/allow_execstack.py:60
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from making the program stack "
"executable.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH ला कार्यक्रमचे स्टॅक कार्यान्वीत करण्यापासून रोखत "
"आहे.\n"
"    "

#: ../src/allow_execstack.py:64
msgid ""
"\n"
"    The $SOURCE application attempted to make its stack\n"
"    executable.  This is a potential security problem.  This should\n"
"    never ever be necessary. Stack memory is not executable on most\n"
"    OSes these days and this will not change. Executable stack memory\n"
"    is one of the biggest security problems. An execstack error might\n"
"    in fact be most likely raised by malicious code. Applications are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  If $SOURCE does not\n"
"    work and you need it to work, you can configure SELinux\n"
"    temporarily to allow this access until the application is fixed. Please\n"
"file a bug report.\n"
"    "
msgstr ""

#: ../src/allow_execstack.py:79
msgid ""
"\n"
"    Sometimes a library is accidentally marked with the execstack flag,\n"
"    if you find a library with this flag you can clear it with the\n"
"    execstack -c LIBRARY_PATH.  Then retry your application.  If the\n"
"    app continues to not work, you can turn the flag back on with\n"
"    execstack -s LIBRARY_PATH.\n"
"    "
msgstr ""

#: ../src/allow_execstack.py:89
msgid ""
"If you do not think $SOURCE_PATH should need to map stack memory that is "
"both writable and executable."
msgstr ""

#: ../src/allow_execstack.py:90
msgid "you need to report a bug. \n"
"This is a potentially dangerous access."
msgstr "तुम्हाला बग कळवावे लागेल.\n"
"हे प्रवेश घातक ठरू शकते."

#: ../src/allow_execstack.py:99
#, python-format
msgid "If you believe that \n"
"%s\n"
"should not require execstack"
msgstr ""

#: ../src/allow_execstack.py:108
#, python-format
msgid ""
"you should clear the execstack flag and see if $SOURCE_PATH works correctly.\n"
"Report this as a bug on %s.\n"
"You can clear the exestack flag by executing:"
msgstr ""
"execstack फ्लॅग नष्ट करा व $SOURCE_PATH योग्यरित्या कार्य करते याची तपासणी "
"करा.\n"
"यास बग म्हणून %s येथे कळवा.\n"
"खालील चालवून exestack फ्लॅग नष्ट करणे शक्य आहे:"

#: ../src/allow_execstack.py:118
#, python-format
msgid "execstack -c %s"
msgstr "execstack -c %s"

#: ../src/allow_ftpd_use_cifs.py:29
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a CIFS "
"filesystem.\n"
"    "
msgstr ""
"\n"
"    SELinux ने ftp डिमनला CIFS फाइलप्रणालीवरील $ACCESS फाइल्सकरीता रोखले.\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:33
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a CIFS "
"filesystem.\n"
"    CIFS (Comment Internet File System) is a network filesystem similar to\n"
"    SMB (<a href=\"http://www.microsoft.com/mind/1196/cifs.asp\">http://www."
"microsoft.com/mind/1196/cifs.asp</a>)\n"
"    The ftp daemon attempted to read one or more files or directories from\n"
"    a mounted filesystem of this type.  As CIFS filesystems do not support\n"
"    fine-grained SELinux labeling, all files and directories in the\n"
"    filesystem will have the same security context.\n"
"\n"
"    If you have not configured the ftp daemon to read files from a CIFS "
"filesystem\n"
"    this access attempt could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/allow_ftpd_use_cifs.py:46
msgid ""
"\n"
"    Changing the \"$BOOLEAN\" boolean to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1.\"\n"
"    "
msgstr ""
"\n"
"    \"$BOOLEAN\" ला बूलीयन निश्चित केल्यास प्रवेश प्राप्त होईल:\n"
"    \"setsebool -P $BOOLEAN=1.\"\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:53
msgid ""
" Changing the \"$BOOLEAN\" and\n"
"    \"$WRITE_BOOLEAN\" booleans to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1 $WRITE_BOOLEAN=1\".\n"
"    warning: setting the \"$WRITE_BOOLEAN\" boolean to true will\n"
"    allow the ftp daemon to write to all public content (files and\n"
"    directories with type public_content_t) in addition to writing to\n"
"    files and directories on CIFS filesystems.  "
msgstr ""
" \"$BOOLEAN\" व\n"
"    \"$WRITE_BOOLEAN\" बूलीयनला खरे निश्चित केल्यास प्रवेश प्राप्त होईल:\n"
"    \"setsebool -P $BOOLEAN=1 $WRITE_BOOLEAN=1\".\n"
"    सावधानी: \"$WRITE_BOOLEAN\" बूलीयनला खरे निश्चित केल्यास\n"
"    ftp डीमनला सर्व पब्लिक पाठ्य करीता लेखनाची परवानगी देईल (फाइल व\n"
"    डिरेक्ट्री public_content_t प्रकारे) CIFS प्रणाली वरील फाइल व "
"डिरेक्ट्रीवर \n"
"    लिहीणाच्या व्यतिरिक्त.  "

#: ../src/allow_ftpd_use_cifs.py:62
msgid "If you want to allow ftpd to write to cifs file systems"
msgstr ""

#: ../src/allow_ftpd_use_cifs.py:63 ../src/allow_ftpd_use_nfs.py:65
msgid "you must tell SELinux about this"
msgstr "तुम्ही SELinux ला याविषयी कळवा"

#: ../src/allow_ftpd_use_nfs.py:29
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a NFS "
"filesystem.\n"
"    "
msgstr ""
"\n"
"    SELinux ने ftp डिमनला NFS  फाइलप्रणालीवरील $ACCESS फाइल्सकरीता रोखले.\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:33
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a NFS "
"filesystem.\n"
"    NFS (Network Filesystem) is a network filesystem commonly used on Unix / "
"Linux\n"
"    systems.\n"
"\n"
"    The ftp daemon attempted to read one or more files or directories from\n"
"    a mounted filesystem of this type.  As NFS filesystems do not support\n"
"    fine-grained SELinux labeling, all files and directories in the\n"
"    filesystem will have the same security context.\n"
"\n"
"    If you have not configured the ftp daemon to read files from a NFS "
"filesystem\n"
"    this access attempt could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/allow_ftpd_use_nfs.py:47
msgid ""
"\n"
"    Changing the \"allow_ftpd_use_nfs\" boolean to true will allow this "
"access:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1.\"\n"
"    "
msgstr ""
"\n"
"    \"allow_ftpd_use_nfs\" बूलीयनला खरे असे निश्चित केल्यास प्रवेश स्थापीत "
"होईल:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1.\"\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:54
msgid ""
" Changing the \"allow_ftpd_use_nfs\" and\n"
"    \"$WRITE_BOOLEAN\" booleans to true will allow this access:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1 $WRITE_BOOLEAN=1\".\n"
"    warning: setting the \"$WRITE_BOOLEAN\" boolean to true will\n"
"    allow the ftp daemon to write to all public content (files and\n"
"    directories with type public_content_t) in addition to writing to\n"
"    files and directories on NFS filesystems.  "
msgstr ""
" \"allow_ftpd_use_nfs\" व\n"
"    \"$WRITE_BOOLEAN\" बूलीयनला खरे निश्चित केल्यास प्रवेश प्राप्त होईल:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1 $WRITE_BOOLEAN=1\".\n"
"    सावधानी: \"$WRITE_BOOLEAN\" बूलीयनला खरे निश्चित केल्यास\n"
"    ftp डीमन सर्व पब्लिक पाठ्यवर लेखन करीता परवानगी देतो (फाइल व \n"
"    public_content_t प्रकारावरील डिरेक्ट्री) व \n"
"    NFS फाइलप्रणालीवरील फाइल व डिरेक्ट्रीवर लेखनच्या व्यतिरीक्त.  "

#: ../src/allow_ftpd_use_nfs.py:64
msgid "If you want to allow ftpd to write to nfs file systems"
msgstr ""

#: ../src/associate.py:32 ../src/openvpn.py:31 ../src/public_content.py:27
#: ../src/qemu_blk_image.py:27 ../src/qemu_file_image.py:27
#: ../src/restorecon.py:51 ../src/restorecon_source.py:33
#: ../src/rsync_data.py:27 ../src/sshd_root.py:32
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access to $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH \"$ACCESS\" ला उपकरन $TARGET_PATH करीता प्रवेश "
"करण्यापासून रोखत आहे. \n"
"    "

#: ../src/associate.py:37
#, python-format
msgid ""
"\n"
"You tried to place a type on a %s that is not a file type.  This is not "
"allowed, you must assigne a file type.  You can list all file types using "
"the seinfo command.\n"
"\n"
"seinfo -afile_type -x\n"
"\n"
"    "
msgstr ""
"\n"
"%s वरील प्रकार ठरवण्याचे प्रयत्न केले जे फाइल प्रकार नाही.  हे स्वीकार्य "
"नाही, फाइल प्रकार लागू करणे आवश्यक आहे.  seinfo आदेशचा वापर करून सर्व फाइल "
"प्रकार सूचीत दाखवणे शक्य आहे.\n"
"\n"
"seinfo -afile_type -x\n"
"\n"
"    "

#: ../src/associate.py:44
#, python-format
msgid ""
"If you want to change the label of $TARGET_PATH to %s, you are not allowed "
"to since it is not a valid file type."
msgstr ""

#: ../src/associate.py:49
msgid "you must pick a valid file label."
msgstr "वैध फाइल लेबलची नीवड करणे आवश्यक."

#: ../src/automount_exec_config.py:27
msgid ""
"\n"
"    SELinux is preventing the $SOURCE_PATH from executing potentially "
"mislabeled files $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH ला अयोग्यरित्या लेबल केलेल्या फाइल्स् $TARGET_PATH "
"कार्यान्वीत करण्यापासून रोखत आहे.\n"
"    "

#: ../src/automount_exec_config.py:31
msgid ""
"\n"
"    SELinux has denied the $SOURCE_PATH from executing potentially\n"
"    mislabeled files $TARGET_PATH.  Automounter can be setup to execute\n"
"    configuration files. If $TARGET_PATH is an automount executable\n"
"    configuration file it needs to have a file label of bin_t.\n"
"    If automounter is trying to execute something that it is not supposed "
"to, this could indicate an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux ने $SOURCE_PATH ला सदोषीत लेबेल केलेली फाइल\n"
"    $TARGET_PATH चालवण्यापासून नकारले.  Automounter संयोजना फाइल\n"
"    चालवण्यासाठी सेटअप केले जाऊ शकते. $TARGET_PATH स्वयंमाउंट एक्जीक्यूटेबल\n"
"    संयोजना फाइल असल्यास त्यांस\n"
"    bin_t चे लेबल असणे आवश्यक आहे.\n"
"    automounter न चालवण्याजोगी बाब कार्यान्वीत करण्याचा प्रयत्न करत असल्यास, "
"हा अवैध प्रवेश प्रयत्न ठरेल.\n"
"    "

#: ../src/automount_exec_config.py:39
msgid ""
"\n"
"    If you want to change the file context of $TARGET_PATH so that the "
"automounter can execute it you can execute \"chcon -t bin_t $TARGET_PATH\".  "
"If you want this to survive a relabel, you need to permanently change the "
"file context: execute  \"semanage fcontext -a -t bin_t '$FIX_TARGET_PATH'\".\n"
"    "
msgstr ""
"\n"
"    $TARGET_PATH याचे फाइल संदर्श बदलायचे असल्यास व automounter चालवायचे "
"असल्यास \"chcon -t bin_t $TARGET_PATH\" चालवा.  पुनःलेबलवेळी अस्तित्वातील "
"लेबल गमवायचे नसल्यास, नेहमीकरीता फाइल संदर्भ बदलावे लागेल:  \"semanage "
"fcontext -a -t bin_t '$FIX_TARGET_PATH'\" चालवा.\n"
"    "

#: ../src/bind_ports.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from binding to port $PORT_NUMBER.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH ला $PORT_NUMBER शी बांधणी करण्यापासून रोखत आहे.\n"
"    "

#: ../src/bind_ports.py:31
#, python-format
msgid ""
"\n"
"    SELinux has denied the $SOURCE from binding to a network port "
"$PORT_NUMBER which does not have an SELinux type associated with it.\n"
"    If $SOURCE should be allowed to listen on $PORT_NUMBER, use the "
"<i>semanage</i> command to assign $PORT_NUMBER to a port type that "
"$SOURCE_TYPE can bind to (%s).\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to bind to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/bind_ports.py:38
#, python-format
msgid ""
"\n"
"    If you want to allow $SOURCE to bind to port $PORT_NUMBER, you can "
"execute \n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    \n"
"where PORT_TYPE is one of the following: %s.\n"
"\n"
"    \n"
"\n"
"If this system is running as an NIS Client, turning on the allow_ypbind "
"boolean may fix the problem.  setsebool -P allow_ypbind=1.\n"
"    "
msgstr ""
"\n"
"    $SOURCE ला पोर्ट $PORT_NUMBER करीता बाइंड करायचे असल्यास, खालील चालवा \n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    \n"
"जेथे PORT_TYPE खालीलपैकी एक असते: %s.\n"
"\n"
"    \n"
"\n"
"हि प्रणाली NIS क्लाएंट म्हणून कार्यरत असल्यास, allow_ypbind बूलियन सुरू "
"केल्याने अडचणीचे निवारण शक्य आहे.  setsebool -P allow_ypbind=1.\n"
"    "

#: ../src/bind_ports.py:47
msgid "If you want to allow $SOURCE_PATH to bind to network port $PORT_NUMBER"
msgstr ""

#: ../src/bind_ports.py:53 ../src/connect_ports.py:51
#, python-format
msgid ""
"# semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    where PORT_TYPE is one of the following: %s."
msgstr ""
"# semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    जेथे PORT_TYPE खालीलपैकी एक आहे: %s."

#: ../src/bind_ports.py:56 ../src/connect_ports.py:54
#, python-format
msgid "# semanage port -a -t %s -p %s $PORT_NUMBER"
msgstr "# semanage port -a -t %s -p %s $PORT_NUMBER"

#: ../src/catchall_boolean.py:32
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access on $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH \"$ACCESS\" ला उपकरन $TARGET_PATH करीता प्रवेश "
"करण्यापासून रोखत आहे. \n"
"    "

#: ../src/catchall_boolean.py:36
msgid ""
"\n"
"\n"
"    SELinux denied access requested by $SOURCE. The current boolean\n"
"    settings do not allow this access.  If you have not setup $SOURCE to\n"
"    require this access this may signal an intrusion attempt. If you do "
"intend\n"
"    this access you need to change the booleans on this system to allow\n"
"    the access.\n"
"    "
msgstr ""

#: ../src/catchall_boolean.py:45
msgid ""
"\n"
"    Confined processes can be configured to run requiring different access, "
"SELinux provides booleans to allow you to turn on/off\n"
"    access as needed.\n"
"\n"
"    "
msgstr ""

#: ../src/catchall_boolean.py:62
#, python-format
msgid "If you want to %s"
msgstr ""

#: ../src/catchall_boolean.py:65
#, python-format
msgid "setsebool -P %s %s"
msgstr "setsebool -P %s %s"

#: ../src/catchall_boolean.py:68
#, python-format
msgid "You must tell SELinux about this by enabling the '%s' boolean.\n"
msgstr "'%s' बूलियन सुरू करून तुम्ही SELinuxला याविषयी कळवा.\n"

#: ../src/catchall_boolean.py:71
#, python-format
msgid "You can read '%s' man page for more details."
msgstr "अधिक माहितीकरीता '%s' man पृष्ठ वाचणे शक्य आहे."

#: ../src/catchall_labels.py:28
#, python-format
msgid ""
"\n"
"    SELinux has denied the $SOURCE access to potentially\n"
"    mislabeled files $TARGET_PATH.  This means that SELinux will not\n"
"    allow httpd to use these files. If httpd should be allowed this access "
"to these files you should change the file context to one of the following "
"types, %s.\n"
"    Many third party apps install html files\n"
"    in directories that SELinux policy cannot predict.  These directories\n"
"    have to be labeled with a file context which httpd can access.\n"
"    "
msgstr ""
"\n"
"    SELinux ने $SOURCE ला \n"
"    अयोग्य लेबल फाइल $TARGET_PATH करीता प्रवेश नकारले.  याचा अर्थ SELinux\n"
"    httpd ला या फाइल्स् वापरण्यासाठी परवानगी देणार नाही.  httpd ने परवानगी "
"दिल्यास, फाइल संदर्भ, %s खालील प्रकारांपैकी एकाशी जुळवा.\n"
"    बरेच तिसरे पक्षीय ऍप्लिकेशन्स् html फाइल्सचे\n"
"    प्रतिष्ठापन योग्य डिरेक्ट्रीज् मध्ये करत नाही.  या डिरेक्ट्रीज्चे लेबल\n"
"    httpd द्वारे प्रवेशजोगी फाइल संदर्भसह करा.\n"
"    "

#: ../src/catchall_labels.py:37
msgid "You need to change the label on $FIX_TARGET_PATH"
msgstr "$FIX_TARGET_PATH वरील लेबल बदलणे आवश्यक आहे"

#: ../src/catchall_labels.py:40
#, python-format
msgid ""
"# semanage fcontext -a -t FILE_TYPE '$FIX_TARGET_PATH'\n"
"where FILE_TYPE is one of the following: %s.\n"
"Then execute:\n"
"restorecon -v '$FIX_TARGET_PATH'\n"
msgstr ""

#: ../src/catchall.py:29 ../src/chrome.py:29 ../src/mozplugger.py:29
#: ../src/mozplugger_remove.py:29
msgid "SELinux is preventing $SOURCE_PATH \"$ACCESS\" access."
msgstr "SELinux $SOURCE_PATH \"$ACCESS\" प्रवेश रोखत आहे."

#: ../src/catchall.py:31
msgid ""
"\n"
"\n"
"    SELinux denied access requested by $SOURCE. It is not\n"
"    expected that this access is required by $SOURCE and this access\n"
"    may signal an intrusion attempt. It is also possible that the specific\n"
"    version or configuration of the application is causing it to require\n"
"    additional access.\n"
"\n"
"    "
msgstr ""
"\n"
"    SELinux ने $SOURCE करीता विनंती नकारली. या प्रवेश\n"
"    करीता $SOURCE ची आवश्यकता आहे असे अपेक्षीत नाही व या प्रवेश\n"
"    घुसखोरीचा प्रयत्न म्हणून पाहिला जाऊ शकतो. ठराविक आवृत्ती किंवा अनुप्रयोग "
"संयोजनामुळे \n"
"    अगाऊ प्रवेश करीता आवश्यकता वाढते.\n"
"\n"
"    "

#: ../src/catchall.py:41
msgid ""
"\n"
"    You can generate a local policy module to allow this\n"
"    access - see <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"\n"
"    Please file a bug report.\n"
"    "
msgstr ""
"\n"
"    या प्रवेशकरीता तुम्ही स्थानीय करार घटक\n"
"    निर्माण करू शकता - <a href=\"http://docs.fedoraproject.org/selinux-faq-"
"fc5/#id2961385\">FAQ</a> पहा\n"
"    कृपया बग अहवाल सादर करा.\n"
"    "

#: ../src/catchall.py:50
msgid ""
"If you believe that $SOURCE_BASE_PATH should be allowed $ACCESS access on "
"processes labeled $TARGET_TYPE by default."
msgstr ""

#: ../src/catchall.py:52
msgid ""
"If you believe that $SOURCE_BASE_PATH should have the $ACCESS capability by "
"default."
msgstr ""

#: ../src/catchall.py:53
msgid ""
"If you believe that $SOURCE_BASE_PATH should be allowed $ACCESS access on "
"the $TARGET_BASE_PATH $TARGET_CLASS by default."
msgstr ""

#: ../src/catchall.py:55
msgid ""
"You should report this as a bug.\n"
"You can generate a local policy module to allow this access."
msgstr ""
"यास बग म्हणून कळवा.\n"
"प्रवेश स्वीकारण्यासाठी तुम्ही स्थानीय करार घटक निर्माण करू शकता."

#: ../src/catchall.py:56
msgid ""
"Allow this access for now by executing:\n"
"# ausearch -c '$SOURCE' --raw | audit2allow -M my-$MODULE_NAME\n"
"# semodule -i my-$MODULE_NAME.pp"
msgstr ""

#: ../src/connect_ports.py:27 ../src/sandbox_connect.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from connecting to port $PORT_NUMBER.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH ला पोर्ट $PORT_NUMBER शी जुळवणी करण्यापासून रोखत "
"आहे.\n"
"    "

#: ../src/connect_ports.py:31
#, python-format
msgid ""
"\n"
"    SELinux has denied $SOURCE from connecting to a network port "
"$PORT_NUMBER which does not have an SELinux type associated with it.\n"
"    If $SOURCE should be allowed to connect on $PORT_NUMBER, use the "
"<i>semanage</i> command to assign $PORT_NUMBER to a port type that "
"$SOURCE_TYPE can connect to (%s).\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to connect to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/connect_ports.py:38
#, python-format
msgid ""
"\n"
"    If you want to allow $SOURCE to connect to $PORT_NUMBER, you can execute "
"\n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"\n"
"    where PORT_TYPE is one of the following: %s.\n"
"    "
msgstr ""
"\n"
"    $SOURCE ला $PORT_NUMBER सह जोडणी करण्यासाठी परवानगी द्यायची असल्यास, "
"खालील चालवा \n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"\n"
"    जेथे PORT_TYPE खालीलपैकी एक आहे: %s.\n"
"    "

#: ../src/connect_ports.py:45 ../src/sandbox_connect.py:47
msgid ""
"If you want to allow $SOURCE_PATH to connect to network port $PORT_NUMBER"
msgstr ""

#: ../src/chrome.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not expected that this "
"access is required by $SOURCE and this access may signal an intrusion "
"attempt. It is also possible that the specific version or configuration of "
"the application is causing it to require additional access.  spice-xpi run "
"applications within mozilla-plugins that require access to the desktop, that "
"the mozilla_plugin lockdown will not allow, so either you need to turn off "
"the mozilla_plugin lockdown or not use these packages.\n"
"    "
msgstr ""

#: ../src/chrome.py:35
msgid ""
"\n"
"Either remove the mozplugger or spice-xpi package by executing 'yum remove "
"mozplugger spice-xpi', or turn off enforcement of SELinux over the Chrome "
"plugins. setsebool -P unconfined_chrome_sandbox_transition 0\n"
"    "
msgstr ""

#: ../src/chrome.py:38 ../src/mozplugger.py:38
#, python-format
msgid "If you want to use the %s package"
msgstr ""

#: ../src/chrome.py:43
msgid "you must turn off SELinux controls on the Chrome plugins."
msgstr "क्रोम प्लगइन्सवरील SELinux कंट्रोल्स बंद करा."

#: ../src/cvs_data.py:27
msgid ""
"\n"
"    SELinux is preventing cvs ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH\n"
"    "
msgstr ""
"\n"
"    SELinux cvs $SOURCE_PATH \"$ACCESS\" ला उपकरन $TARGET_PATH करीता प्रवेश "
"करण्यापासून रोखत आहे\n"
"    "

#: ../src/cvs_data.py:31
msgid ""
"\n"
"    SELinux denied cvs access to $TARGET_PATH.\n"
"    If this is a CVS repository it needs to have a file context label of\n"
"    cvs_data_t. If you did not intend to use $TARGET_PATH as a CVS "
"repository\n"
"    it could indicate either a bug or it could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux ने $TARGET_PATH करीता cvs प्रवेश नकारले.\n"
"    ही CVS रेपॉजटरी असल्यास\n"
"    त्यांस cvs_data_t लेबल असणे आवश्यक आहे. $TARGET_PATH ला cvs "
"रेपॉजटरीप्रमाणे वापरायचे नसल्यास\n"
"    ते बग किंवा अवैध प्रवेश प्रयत्न ठरेल.\n"
"    "

#: ../src/cvs_data.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t cvs_data_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"cvs_data_t '$FIX_TARGET_PATH'\"\n"
"    \n"
"    "
msgstr ""
"\n"
"    chcon -R -t cvs_data_t '$TARGET_PATH' चालवून तुम्ही फाइल संदर्भ बदलवू "
"शकता\n"
"    पूर्णतया पुनः लेबल झाल्यावर प्रणालीवरील पूर्वनिर्धारीत फाइल्स्चे संदर्भ "
"देखील तुम्हाला बदलावे लागेल.  \"semanage fcontext -a -t cvs_data_t "
"'$FIX_TARGET_PATH'\"\n"
"    \n"
"    "

#: ../src/cvs_data.py:44
msgid "If $TARGET_BASE_PATH should be shared via the cvs daemon"
msgstr ""

#: ../src/cvs_data.py:45 ../src/qemu_file_image.py:49
msgid "You need to change the label on $TARGET_BASE_PATH'"
msgstr "$TARGET_BASE_PATH' वरील लेबल बदलणे आवश्यक आहे"

#: ../src/dac_override.py:28
msgid "\n"
"    SELinux is preventing $SOURCE_PATH the \"$ACCESS\" capability.\n"
"    "
msgstr ""

#: ../src/dac_override.py:32
msgid ""
"\n"
"\tdac_override and dac_read_search capabilities usually indicates that the "
"root process does not have access to a file based on the permission flags.  "
"This usually mean you have some file with the wrong ownership/permissions on "
"it.\n"
"    "
msgstr ""
"\n"
"\tdac_override व dac_read_search क्षमता सहसा रूट प्रोसेस्ला परमिशन "
"फ्लॅग्सवरील आधारित फाइलकरीता प्रवेश नाही असे निर्देशीत करतो.  याचा सहसा असा "
"अर्थ होतो कि ठारविक फाइलला चुकिची मालकी/परवानगी आहे.\n"
"    "

#: ../src/dac_override.py:38
msgid ""
"If you want to help identify if domain needs this access or you have a file "
"with the wrong permissions on your system"
msgstr ""

#: ../src/dac_override.py:39
msgid ""
"turn on full auditing to get path information about the offending file and "
"generate the error again."
msgstr ""
"ऑफेंडिंग फाइलविषयी माहिती प्राप्त करण्यासाठी संपूर्ण ऑडिटिंग सुरू करा व "
"त्रुटी पुनः निर्माण करा."

#: ../src/dac_override.py:40
msgid ""
"\n"
"Turn on full auditing\n"
"# auditctl -w /etc/shadow -p w\n"
"Try to recreate AVC. Then execute\n"
"# ausearch -m avc -ts recent\n"
"If you see PATH record check ownership/permissions on file, and fix it,\n"
"otherwise report as a bugzilla."
msgstr ""

#: ../src/device.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access to device "
"$TARGET_PATH.\n"
"    "
msgstr ""

#: ../src/device.py:33
msgid ""
"\n"
"\n"
"    SELinux has denied $SOURCE \"$ACCESS\" access to device $TARGET_PATH.\n"
"    $TARGET_PATH is mislabeled, this device has the default label of the /"
"dev directory, which should not\n"
"    happen.  All Character and/or Block Devices should have a label.\n"
"\n"
"    You can attempt to change the label of the file using\n"
"\n"
"    restorecon -v '$TARGET_PATH'.\n"
"\n"
"    If this device remains labeled device_t, then this is a bug in SELinux "
"policy.\n"
"\n"
"    Please file a bg report.\n"
"\n"
"    If you look at the other similar devices labels, ls -lZ /dev/SIMILAR, "
"and find a type that would work for $TARGET_PATH,\n"
"    you can use chcon -t SIMILAR_TYPE '$TARGET_PATH', If this fixes the "
"problem, you can make this permanent by executing\n"
"    semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"\n"
"    If the restorecon changes the context, this indicates that the "
"application that created the device, created it without\n"
"    using SELinux APIs.  If you can figure out which application created the "
"device, please file a bug report against this application.\n"
"\n"
"    "
msgstr ""

#: ../src/device.py:56
msgid ""
"\n"
"    Attempt restorecon -v '$TARGET_PATH' or chcon -t SIMILAR_TYPE "
"'$TARGET_PATH'\n"
"    "
msgstr ""
"\n"
"    restorecon -v '$TARGET_PATH' चा प्रयत्न करा किंवा chcon -t SIMILAR_TYPE "
"'$TARGET_PATH' करा\n"
"    "

#: ../src/device.py:60
msgid ""
"You need to change the label on $TARGET_PATH to a type of a similar device."
msgstr "समान प्रकारच्या साधनकरीता $TARGET_PATH वरील लेबलला बदलणे आवश्यक आहे."

#: ../src/device.py:61
msgid ""
"# semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"

#: ../src/disable_ipv6.py:30
msgid "\n"
"Disable IPV6 properly.\n"
"    "
msgstr "\n"
"IPV6 योग्यरित्या बंद करा.\n"
"    "

#: ../src/disable_ipv6.py:40
msgid "If you want to disable IPV6 on this machine"
msgstr ""

#: ../src/disable_ipv6.py:41
msgid ""
"you need to set /proc/sys/net/ipv6/conf/all/disable_ipv6 to 1 and do not "
"blacklist the module'"
msgstr ""
"/proc/sys/net/ipv6/conf/all/disable_ipv6 यास 1 करीता सेट करा व घटकाला "
"ब्लॅकलिस्ट करू नका"

#: ../src/disable_ipv6.py:42
msgid "Add \n"
"net.ipv6.conf.all.disable_ipv6 = 1\n"
"to /etc/sysctl.conf\n"
msgstr ""
"net.ipv6.conf.all.disable_ipv6 = 1\n"
"/etc/sysctl.conf मध्ये\n"
"समाविष्ट करा\n"

#: ../src/file.py:27
msgid ""
"\n"
"    SELinux is preventing access to files with the label, file_t.\n"
"    "
msgstr ""
"\n"
"    SELinux लेबल असलेल्या फाइलकरीता प्रवेश देण्यास नकार देत आहे, file_t.\n"
"    "

#: ../src/file.py:31
msgid ""
"\n"
"    SELinux permission checks on files labeled file_t are being\n"
"    denied.  file_t is the context the SELinux kernel gives to files\n"
"    that do not have a label. This indicates a serious labeling\n"
"    problem. No files on an SELinux box should ever be labeled file_t.\n"
"    If you have just added a disk drive to the system you can\n"
"    relabel it using the restorecon command.  For example if you saved the\n"
"home directory from a previous installation that did not use SELinux, "
"'restorecon -R -v /home' will fix the labels.  Otherwise you should\n"
"    relabel the entire file system.\n"
"    "
msgstr ""
"\n"
"    file_t चिन्हाकृत फाइल करीता SELinux परवानगी\n"
"    नकारली जाते.  विना लेबल फाइल \n"
"    करीता SELinux कर्नल file_t संदर्भ प्रदान करतो. ही एक गंभीर लेबलींग "
"त्रुटी आहे\n"
"    . SELinux बॉक्स वरील कुठलिही फाइल file_t चिन्हाकृत नसावी.\n"
"    प्रणालीशी नवीन डिस्क ड्राइव्ह जोडले असल्यास\n"
"    तुम्ही त्यांस restorecon आदेशचा वापर करून पुनःलेबल करू शकता. उदाहरणार्थ \n"
"SELinux च्या वापर विना पूर्वीच्या प्रतिष्ठापनातून होम डिरेक्ट्री साठवल्यास, "
"'restorecon -R -v /home' लेबल्स् ठरवतो.  नाहीतर पूर्ण फाइल प्रणालीला\n"
"    पुनः लेबल करा.\n"
"    "

#: ../src/file.py:42
msgid ""
"\n"
"    You can execute the following command as root to relabel your\n"
"    computer system: \"touch /.autorelabel; reboot\"\n"
"    "
msgstr ""
"\n"
"    तुम्ही खालील आदेश तुमची संगणक प्रणाली रूट म्हणून पुन्हलेबल करण्याकरीता\n"
"    कार्यान्वीत करा: \"touch /.autorelabel; reboot\"\n"
"    "

#: ../src/file.py:49
msgid "This is caused by a newly created file system."
msgstr ""

#: ../src/file.py:51
msgid "If you think this is caused by a badly mislabeled machine."
msgstr ""

#: ../src/file.py:55
msgid "you need to add labels to it."
msgstr "लेबल्स् समाविष्ट करणे आवश्यक आहे."

#: ../src/file.py:57
msgid "you need to fully relabel."
msgstr "संपूर्णतया पुनःलेबल करणे आवश्यक आहे."

#: ../src/filesystem_associate.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from creating a file with a context "
"of $SOURCE_TYPE on a filesystem.\n"
"    "
msgstr ""
"\n"
"    फाइल प्रणाली वरील $SOURCE_TYPE संदर्भ असल्यास SELinux $SOURCE_PATH ला "
"फाइल बनवण्यापासून रोखतो.\n"
"    "

#: ../src/filesystem_associate.py:31
msgid ""
"\n"
"    SELinux is preventing $SOURCE from creating a file with a context of "
"$SOURCE_TYPE on a filesystem.\n"
"    Usually this happens when you ask the cp command to maintain the context "
"of a file when\n"
"    copying between file systems, \"cp -a\" for example.  Not all file "
"contexts should be maintained\n"
"    between the file systems.  For example, a read-only file type like "
"iso9660_t should not be placed\n"
"    on a r/w system.  \"cp -p\" might be a better solution, as this will "
"adopt the default file context\n"
"    for the destination.\n"
"    "
msgstr ""

#: ../src/filesystem_associate.py:40
msgid ""
"\n"
"    Use a command like \"cp -p\" to preserve all permissions except SELinux "
"context.\n"
"    "
msgstr ""
"\n"
"    SELinux संदर्भाला वगळता सर्व परवानगी संचयीत करण्यासाठी \"cp -p\" आदेशचा "
"वापर करा.\n"
"    "

#: ../src/filesystem_associate.py:43
msgid ""
"If you believe $SOURCE_BASE_PATH should be allowed to create "
"$TARGET_BASE_PATH files"
msgstr ""

#: ../src/filesystem_associate.py:44
msgid ""
"you need to use a different command. You are not allowed to preserve the "
"SELinux context on the target file system."
msgstr ""
"तुम्हाला वेगळ्या आदेशचा वापर करावा लागेल. लक्ष्य फाइल प्रणालीवरील SELinux "
"संदर्भ साठवण्यास तुम्हाला परवानगी नाही."

#: ../src/filesystem_associate.py:46
msgid ""
"use a command like \"cp -p\" to preserve all permissions except SELinux "
"context."
msgstr ""
"SELinux संदर्भाला वगळता सर्व परवानगी संचयीत करण्यासाठी \"cp -p\" आदेशचा वापर "
"करा."

#: ../src/httpd_can_sendmail.py:28
msgid "\n"
"    SELinux is preventing the http daemon from sending mail.\n"
"    "
msgstr "\n"
"    SELinux http डीमनला मेल पाठवण्यापासून रोखत आहे.\n"
"    "

#: ../src/httpd_can_sendmail.py:32
msgid ""
"\n"
"    SELinux has denied the http daemon from sending mail. An\n"
"    httpd script is trying to connect to a mail port or execute the\n"
"    sendmail command. If you did not setup httpd to sendmail, this could\n"
"    signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/httpd_can_sendmail.py:39
msgid ""
"\n"
"    If you want httpd to send mail you need to turn on the\n"
"    $BOOLEAN boolean: \"setsebool -P\n"
"    $BOOLEAN=1\"\n"
"    "
msgstr ""
"\n"
"    httpd ने मेल पाठवण्यासाठी तुम्हाला\n"
"    $BOOLEAN बूलीयन: \"setsebool -P\n"
"    $BOOLEAN=1\" सक्रीय करावे लागेल\n"
"    "

#: ../src/httpd_can_sendmail.py:47
msgid "If you want to allow httpd to send mail"
msgstr ""

#: ../src/httpd_can_sendmail.py:48
msgid "you must setup SELinux to allow this"
msgstr "हे स्वीकारण्याकरीता तुम्ही SELinux निश्चित करायला हवे"

#: ../src/httpd_unified.py:29
msgid "\n"
"    SELinux prevented httpd $ACCESS access to http files.\n"
"    "
msgstr ""
"\n"
"    SELinux ने httpd ला http फाइल्स्करीता $ACCESS प्रतिबंधिकत केले.\n"
"    "

#: ../src/httpd_unified.py:33
msgid ""
"\n"
"    SELinux prevented httpd $ACCESS access to http files.\n"
"\n"
"    Ordinarily httpd is allowed full access to all files labeled with http "
"file\n"
"    context.  This machine has a tightened security policy with the $BOOLEAN\n"
"    turned off,  This requires explicit labeling of all files.  If a file is\n"
"    a cgi script it needs to be labeled with httpd_TYPE_script_exec_t in "
"order\n"
"    to be executed.  If it is read only content, it needs to be labeled\n"
"    httpd_TYPE_content_t, it is writable content. it needs to be labeled\n"
"    httpd_TYPE_script_rw_t or httpd_TYPE_script_ra_t. You can use the\n"
"    chcon command to change these context.  Please refer to the man page\n"
"    \"man httpd_selinux\" or\n"
"    <a href=\"http://fedora.redhat.com/docs/selinux-apache-fc3\">FAQ</a>\n"
"    \"TYPE\" refers to one of \"sys\", \"user\" or \"staff\" or potentially "
"other\n"
"    script types.\n"
"    "
msgstr ""

#: ../src/httpd_unified.py:50
msgid ""
"\n"
"    Changing the \"$BOOLEAN\" boolean to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1\"\n"
"    "
msgstr ""
"\n"
"    \"$BOOLEAN\" बूलीयनला खरे निश्चित केल्यास प्रवेश प्राप्त होईल:\n"
"    \"setsebool -P $BOOLEAN=1\"\n"
"    "

#: ../src/httpd_unified.py:57
msgid ""
"If you want to allow httpd to execute cgi scripts and to unify HTTPD "
"handling of all content files."
msgstr ""

#: ../src/httpd_unified.py:58
msgid ""
"you must tell SELinux about this by enabling the 'httpd_unified' and "
"'http_enable_cgi' booleans"
msgstr ""
"'httpd_unified' व 'http_enable_cgi' बूलियन्स् सुरू करून तुम्ही SELinux ला "
"याविषयी कळवा"

#: ../src/httpd_write_content.py:30
msgid ""
"\n"
"    SELinux prevented httpd $ACCESS access to $TARGET_PATH.\n"
"\n"
"    httpd scripts are not allowed to write to content without explicit\n"
"    labeling of all files.  If $TARGET_PATH is writable content. it needs\n"
"    to be labeled httpd_sys_rw_content_t or if all you need is append you "
"can label it httpd_sys_ra_content_t.   Please refer to 'man httpd_selinux' "
"for more information on setting up httpd and selinux.\n"
"    "
msgstr ""

#: ../src/httpd_write_content.py:40 ../src/qemu_blk_image.py:45
#: ../src/samba_share.py:45 ../src/swapfile.py:45 ../src/xen_image.py:48
msgid "You need to change the label on '$FIX_TARGET_PATH'"
msgstr "'$FIX_TARGET_PATH' वरील लेबल बदलणे आवश्यक आहे"

#: ../src/kernel_modules.py:29
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to modify "
"kernel configuration.\n"
"    "
msgstr ""
"\n"
"    तुमच्या प्रणालीला गंभीर धोका होऊ शकतो! $SOURCE_PATH ने कर्नल संरचना "
"संपादीत करण्याचा प्रयत्न केला.\n"
"    "

#: ../src/kernel_modules.py:33
msgid ""
"\n"
"    SELinux has prevented $SOURCE from modifying $TARGET.  This denial\n"
"    indicates $SOURCE was trying to modify the way the kernel runs or to\n"
"    actually insert code into the kernel. All applications that need this\n"
"    access should have already had policy written for them.  If a "
"compromised\n"
"    application tries to modify the kernel this AVC will be generated. This "
"is a\n"
"    serious issue. Your system may very well be compromised.\n"
"    "
msgstr ""

#: ../src/kernel_modules.py:44 ../src/selinuxpolicy.py:44
msgid ""
"If you do not think $SOURCE_BASE_PATH should try $ACCESS access on "
"$TARGET_BASE_PATH."
msgstr ""

#: ../src/kernel_modules.py:45 ../src/selinuxpolicy.py:45
msgid ""
"you may be under attack by a hacker, since confined applications should not "
"need this access."
msgstr ""
"मर्यादित ॲप्लिकेशन्स्ला या प्रवेशची आवश्यकता नसल्याने, तुम्हाला हॅकरतर्फे "
"धोका असू शकतो."

#: ../src/leaks.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH access to a leaked $TARGET_PATH file "
"descriptor.\n"
"    "
msgstr ""
"\n"
"    SELinux $TARGET_PATH फाइल डिस्क्रीप्टर करीता $SOURCE_PATH प्रवेश रोखत "
"आहे.\n"
"    "

#: ../src/leaks.py:31
msgid ""
"\n"
"    SELinux denied access requested by the $SOURCE command. It looks like "
"this is either a leaked descriptor or $SOURCE output was redirected to a "
"file it is not allowed to access.  Leaks usually can be ignored since "
"SELinux is just closing the leak and reporting the error.  The application "
"does not use the descriptor, so it will run properly.  If this is a "
"redirection, you will not get output in the $TARGET_PATH.  You should "
"generate a bugzilla on selinux-policy, and it will get routed to the "
"appropriate package.  You can safely ignore this avc.\n"
"    "
msgstr ""
"\n"
"    SELinux ने $SOURCE आदेश द्वारे विनंतीकृत प्रवेश नकारले. हे एकतर लिक्ड् "
"डिस्क्रीप्टर असू शकते किंवा प्रवेश नसलेल्या फाइलकरीता $SOURCE आउटपुट लिहीले "
"जाईल.  लिक्स् सहसा दुर्लक्ष केले जातात कारण SELinux नुकतेच लिक बंद करून "
"त्रुटी कळवत आहे.  ऍप्लिकेशन डिस्क्रीप्टरचा वापर करत नसल्यामुळे, योग्यप्रकारे "
"चालते.  हे रिडायरेकशन असल्यास, तुम्हाला आऊटपुट $TARGET_PATH मध्ये आढळणार "
"नाही.  तुम्ही selinux-policy वर बगजीला निर्माण केले पाहिजे, व ते योग्य "
"संकुलकडे पाठवले जाईल.  तुम्ही नक्की हे avc दुर्लक्ष करू शकता.\n"
"    "

#: ../src/leaks.py:35
msgid ""
"\n"
"    You can generate a local policy module to allow this\n"
"    access - see <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"    "
msgstr ""
"\n"
"    या प्रवेशसाठी तुम्ही स्थानीय करार घटक\n"
"    निर्माण करू शकता - <a href=\"http://docs.fedoraproject.org/selinux-faq-"
"fc5/#id2961385\">FAQ</a> पहा\n"
"    "

#: ../src/leaks.py:42
msgid ""
"If you want to ignore $SOURCE_BASE_PATH trying to $ACCESS access the "
"$TARGET_BASE_PATH $TARGET_CLASS, because you believe it should not need this "
"access."
msgstr ""

#: ../src/leaks.py:43
msgid ""
"You should report this as a bug.  \n"
"You can generate a local policy module to dontaudit this access."
msgstr ""
"यास बग म्हणून कळवा.  \n"
"प्रवेश नकारण्यासाठी तुम्ही स्थानीय करार घटक निर्माण करू शकता."

#: ../src/leaks.py:44
msgid ""
"# ausearch -x $SOURCE_PATH --raw | audit2allow -D -M my-$SOURCE\n"
"# semodule -i my-$SOURCE.pp"
msgstr ""

#: ../src/mmap_zero.py:29
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH attempted to mmap "
"low kernel memory.\n"
"    "
msgstr ""
"\n"
"    तुमच्या प्रणालीला गंभीर धोका होऊ शकतो!$SOURCE_PATH ने लो कर्नल मेमोरीशी "
"mmap करण्याचा प्रयत्न केला आहे.\n"
"    "

#: ../src/mmap_zero.py:33
msgid ""
"\n"
"    SELinux has denied the $SOURCE the ability to mmap low area of the "
"kernel \n"
"    address space.  The ability to mmap a low area of the address space is \n"
"    configured by /proc/sys/kernel/mmap_min_addr.  Preventing such mappings \n"
"    helps protect against exploiting null deref bugs in the kernel. All \n"
"    applications that need this access should have already had policy "
"written \n"
"    for them.  If a compromised application tries to modify the kernel, this "
"AVC \n"
"    would be generated. This is a serious issue. Your system may very well "
"be \n"
"    compromised.\n"
"    "
msgstr ""

#: ../src/mmap_zero.py:46
msgid ""
"If you do not think $SOURCE_PATH should need to mmap low memory in the "
"kernel."
msgstr ""

#: ../src/mmap_zero.py:47
msgid "you may be under attack by a hacker, this is a very dangerous access."
msgstr "तुम्हाला हॅकरतर्फे धोका असू शकतो, हे खूप धोकादायक आहे."

#: ../src/mounton.py:29
msgid ""
"\n"
"    SELinux prevented $SOURCE from mounting on the file or directory\n"
"    \"$TARGET_PATH\" (type \"$TARGET_TYPE\").\n"
"    "
msgstr ""
"\n"
"    SELinux ने $SOURCE ला फाइल किंवा डिरेक्ट्री\n"
"    \"$TARGET_PATH\" (type \"$TARGET_TYPE\") वर आरोहण करण्यापासून रोखले.\n"
"    "

#: ../src/mounton.py:34
msgid ""
"\n"
"    SELinux prevented $SOURCE from mounting a filesystem on the file\n"
"    or directory \"$TARGET_PATH\" of type \"$TARGET_TYPE\". By default\n"
"    SELinux limits the mounting of filesystems to only some files or\n"
"    directories (those with types that have the mountpoint attribute). The\n"
"    type \"$TARGET_TYPE\" does not have this attribute. You can change the\n"
"    label of the file or directory.\n"
"    "
msgstr ""

#: ../src/mounton.py:43
msgid ""
"\n"
"    Changing the file_context to mnt_t will allow mount to mount the file "
"system:\n"
"    \"chcon -t mnt_t '$TARGET_PATH'.\"\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"mnt_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    file_context ला mnt_t असे बदल केल्यास फाइल प्रणालीस आरोहण करीता परवानगी "
"प्राप्त होईल:\n"
"    \"chcon -t mnt_t '$TARGET_PATH'.\"\n"
"    पूर्णतया पुन्हलेबल करीता तुम्ही प्रणालीवरील पूर्वनिर्धारीत फाइल संदर्भ "
"oसुध्दा बदलविले पाहिजे  \"semanage fcontext -a -t mnt_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/mounton.py:48
msgid "If you want to allow $SOURCE_BASE_PATH to mount on $TARGET_BASE_PATH."
msgstr ""

#: ../src/mounton.py:49
msgid "you must change the labeling on $TARGET_PATH."
msgstr "$TARGET_PATH वरील लेबल बदलणे आवश्यक आहे."

#: ../src/mozplugger.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not expected that this "
"access is required by $SOURCE and this access may signal an intrusion "
"attempt. It is also possible that the specific version or configuration of "
"the application is causing it to require additional access.  mozplugger and "
"spice-xpi run applications within mozilla-plugins that require access to the "
"desktop, that the mozilla_plugin lockdown will not allow, so either you need "
"to turn off the mozilla_plugin lockdown or not use these packages.\n"
"    "
msgstr ""

#: ../src/mozplugger.py:35
msgid ""
"\n"
"Either remove the mozplugger or spice-xpi package by executing 'yum remove "
"mozplugger spice-xpi' or turn off enforcement of SELinux over the Firefox "
"plugins. setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "
msgstr ""

#: ../src/mozplugger.py:43
msgid "you must turn off SELinux controls on the Firefox plugins."
msgstr "फायरफॉक्स् प्लगइन्सवरील SELinux कंट्रोल्स् बंद करणे आवश्यक."

#: ../src/mozplugger_remove.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not\n"
"    expected that this access is required by $SOURCE and this access\n"
"    may signal an intrusion attempt. It is also possible that the specific\n"
"    version or configuration of the application is causing it to require\n"
"    additional access.\n"
"    "
msgstr ""
"\n"
"    SELinux ने $SOURCE करीता विनंती नकारली. या प्रवेश\n"
"    करीता $SOURCE ची आवश्यकता आहे असे अपेक्षीत नाही व या प्रवेश\n"
"    घुसखोरीचा प्रयत्न म्हणून पाहिला जाऊ शकतो. ठराविक आवृत्ती किंवा ॲप्लिकेशन "
"संयोजनामुळे\n"
"    अगाऊ प्रवेशकरीता आवश्यकता वाढते.\n"
"    "

#: ../src/mozplugger_remove.py:39
msgid ""
"\n"
"Either remove the mozplluger package by executing 'yum remove mozplugger'\n"
"Or turn off enforcement of SELinux over the Firefox plugins.\n"
"setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "
msgstr ""
"\n"
"'yum remove mozplugger' चालवून एकतर mozplluger संकुल काढून टाका\n"
"किंवा फायरफॉक्स् प्लगइन्स् वरील SELinux जबरनरित्या चालवणे बंद करा.\n"
"setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "

#: ../src/mozplugger_remove.py:44
msgid ""
"If you want to to continue using SELinux Firefox plugin containment rather "
"then using mozplugger package"
msgstr ""

#: ../src/mozplugger_remove.py:45
msgid "you must remove the mozplugger package."
msgstr "mozplugger संकुल काढून टाकणे आवश्यक."

#: ../src/openvpn.py:35
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled. openvpn is allowed to read content in home directory if "
"it\n"
"    is labeled correctly.\n"
"    "
msgstr ""

#: ../src/openvpn.py:41
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  \n"
"    # restorecon -R /root/.ssh\n"
"    "
msgstr ""

#: ../src/openvpn.py:49
msgid ""
"If you want to mv $TARGET_BASE_PATH to standard location so that "
"$SOURCE_BASE_PATH can have $ACCESS access"
msgstr ""

#: ../src/openvpn.py:51
msgid ""
"If you want to modify the label on $TARGET_BASE_PATH so that "
"$SOURCE_BASE_PATH can have $ACCESS access on it"
msgstr ""

#: ../src/openvpn.py:55
msgid "you must move the cert file to the ~/.cert directory"
msgstr "cert फाइलला ~/.cert डिरेक्ट्रिकरीता स्थानांतरीत करा"

#: ../src/openvpn.py:57 ../src/sshd_root.py:48
msgid "you must fix the labels."
msgstr "लेबल्स् ठरवणे आवश्यक आहे."

#: ../src/public_content.py:31
msgid ""
"\n"
"    SELinux denied access to $TARGET_PATH requested by $SOURCE.\n"
"    $TARGET_PATH has a context used for sharing by a different program. If "
"you\n"
"    would like to share $TARGET_PATH from $SOURCE also, you need to\n"
"    change its file context to public_content_t.  If you did not intend to\n"
"    allow this access, this could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux ने $SOURCE द्वारे विनंतीकृत $TARGET_PATH करीता प्रवेश नकारले.\n"
"    $TARGET_PATH कडे विविध कार्यक्रमांद्वारे शेअरींगसाठी संदर्भ समाविष्टीत "
"आहे. तुम्हाला \n"
"    $SOURCE पासूनचे $TARGET_PATH वापरणीसाठी उपलब्ध करायचे असल्यास, \n"
"    त्याचे फाइल संदर्भ public_content_t याप्रमाणे बदलावे लागेल.  प्रवेश\n"
"    प्राप्त करायचे नसल्यास, हे अवैध प्रवेश प्रयत्न ठरेल.\n"
"    "

#: ../src/public_content.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -t public_content_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"public_content_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -t public_content_t '$TARGET_PATH' चालवून तुम्ही फाइल संदर्भ बदलवू "
"शकता\n"
"    पूर्णतया पुनःलेबल झाल्यावरही तुम्ही प्रणालीवरील पूर्वनिर्धारीत फाइल्स् "
"फाइल संदर्भ बदलवले पाहिजेत.  \"semanage fcontext -a -t public_content_t "
"'$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/public_content.py:50
msgid "If you want to treat $TARGET_BASE_PATH as public content"
msgstr ""

#: ../src/public_content.py:51
msgid ""
"You need to change the label on $TARGET_BASE_PATH to public_content_t or "
"public_content_rw_t."
msgstr ""
"$TARGET_BASE_PATH वरील लेबलला public_content_t किंवा public_content_rw_t "
"करीता बदलणे आवश्यक आहे.."

#: ../src/qemu_blk_image.py:31
msgid ""
"\n"
"    SELinux denied qemu access to the block device $TARGET_PATH.\n"
"    If this is a virtualization image, it needs to be labeled with a "
"virtualization file context (virt_image_t). You can relabel $TARGET_PATH to "
"be virt_image_t using chcon.  You also need to execute semanage fcontext -a -"
"t virt_image_t '$FIX_TARGET_PATH' to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a qemu\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux ने ब्लॉक साधन $TARGET_PATH करीता qemu प्रवेश नकारला.\n"
"    ही आभासीकरण प्रतिमा असल्यास, त्याचे फाइल संदर्भ लेबल (virt_image_t) "
"असायला हवे. chcon चा वापर करून $TARGET_PATH यांस virt_image_t या प्रमाणे "
"पुनःलेबल करू शकता.  प्रणाली पूर्वनिर्धारीतांमध्ये नवीन मार्ग जोडण्याकरीता "
"तुम्हाला semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"    समाविष्ट करावे लागेल. $TARGET_PATH ला qemu\n"
"प्रतिमा म्हणून वापरायचे नसल्यास यांस बग किंवा अवैध प्रवेश प्रयत्न म्हणून "
"ओळखले जाईल.\n"
"    "

#: ../src/qemu_blk_image.py:38 ../src/qemu_file_image.py:41
msgid ""
"\n"
"    You can alter the file context by executing chcon -t virt_image_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"virt_image_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -t virt_image_t '$TARGET_PATH' वापरून तुम्ही फाइल संदर्भ बदलवू "
"शकता\n"
"    संपूर्णतया पुनःलेबल केल्यावरही सुरक्षीत करण्यासाठी प्रणालीवरील "
"पूर्वनिर्धारीत फाइल संदर्भ फाइल्स् देखील बदलणे आवश्यक आहे.  \"semanage "
"fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/qemu_blk_image.py:46
msgid ""
"# semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"

#: ../src/qemu_file_image.py:31
msgid ""
"\n"
"    SELinux denied qemu access to $TARGET_PATH.\n"
"    If this is a virtualization image, it has to have a file context label "
"of\n"
"    virt_image_t. The system is setup to label image files in directory./var/"
"lib/libvirt/images\n"
"    correctly.  We recommend that you copy your image file to /var/lib/"
"libvirt/images.\n"
"    If you really want to have your qemu image files in the current "
"directory, you can relabel $TARGET_PATH to be virt_image_t using chcon.  You "
"also need to execute semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH' "
"to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a qemu\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux ने $TARGET_PATH करीता qemu प्रवेश नकारला .\n"
"    ही आभासीकरण प्रतिमा असल्यास, त्याचे फाइल संदर्भ लेबलvirt_image_t असायला "
"हवे.\n"
"    डिरेक्ट्री ./var/lib/libvirt/imagesअंतर्गत प्रतिमा फाइलचे लेबल करण्यास "
"प्रणाली सज्ज आहे.\n"
"    प्रतिमा फाइलची प्रतिकृती /var/lib/libvirt/images येथे असावी असे सूचविले "
"जाते.\n"
"    qemu प्रतिमा फाइल वर्तमान डिरेक्ट्रीत आढळल्यास, तुम्ही chcon चा वापर "
"करून $TARGET_PATH यांस virt_image_t असे पुनः लेबल करू शकता.  नवीन मार्ग "
"प्रणाली पूर्वनिर्धारीतांमध्ये समाविष्ट करण्यासाठी तुम्हाला semanage fcontext "
"-a -t virt_image_t '$FIX_TARGET_PATH' समाविष्ट करावे लागेल.\n"
"    $TARGET_PATH ला qemu प्रतिमा म्हणून वापरायचे नसल्यास\n"
"    यांस बग किंवा अवैध प्रवेश प्रयत्न म्हणून ठरवले जाईल.\n"
"    "

#: ../src/qemu_file_image.py:48
msgid "If $TARGET_BASE_PATH is a virtualization target"
msgstr ""

#: ../src/restorecon.py:57
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon '$TARGET_PATH', if this file is a "
"directory,\n"
"    you can recursively restore using restorecon -R '$TARGET_PATH'.\n"
"    "
msgstr ""
"\n"
"    तुम्ही यास फाइल करीता पूर्वनिर्धारीत प्रणाली संदर्भ restorecon आदेश "
"चालवून\n"
"    पुन्हस्थापीत करू शकता.  restorecon '$TARGET_PATH', फाइल डिरेक्ट्री "
"असल्यास,\n"
"    तुम्ही वारंवार restorecon -R '$TARGET_PATH' वापरू पुन्हा स्थापीत करू "
"शकता.\n"
"    "

#: ../src/restorecon.py:64
#, python-format
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled.  $TARGET_PATH default SELinux type is\n"
"    <B>%s</B>, but its current type is <B>$TARGET_TYPE</B>. Changing\n"
"    this file back to the default type may fix your problem.\n"
"    <p>\n"
"    File contexts can be assigned to a file in the following ways.\n"
"    <ul>\n"
"        <li>Files created in a directory receive the file context of the "
"parent directory by default.\n"
"        <li>The SELinux policy might override the default label inherited "
"from the parent directory by\n"
"            specifying a process running in context A which creates a file "
"in a directory labeled B\n"
"            will instead create the file with label C. An example of this "
"would be the dhcp client running\n"
"            with the dhclient_t type and creating a file in the directory /"
"etc. This file would normally\n"
"            receive the etc_t type due to parental inheritance but instead "
"the file\n"
"            is labeled with the net_conf_t type because the SELinux policy "
"specifies this.\n"
"        <li>Users can change the file context on a file using tools such as "
"chcon, or restorecon.\n"
"    </ul>\n"
"    This file could have been mislabeled either by user error, or if an "
"normally confined application\n"
"    was run under the wrong domain.\n"
"    <p>\n"
"    However, this might also indicate a bug in SELinux because the file "
"should not have been labeled\n"
"    with this type.\n"
"    <p>\n"
"    If you believe this is a bug, please file a bug report against this "
"package.\n"
"    "
msgstr ""

#: ../src/restorecon.py:90
#, python-format
msgid ""
"If you want to fix the label. \n"
"$TARGET_PATH default label should be %s."
msgstr ""

#: ../src/restorecon.py:96
msgid ""
"you can run restorecon. The access attempt may have been stopped due to "
"insufficient permissions to access a parent directory in which case try to "
"change the following command accordingly."
msgstr ""

#: ../src/restorecon.py:105 ../src/restorecon_source.py:73
msgid "Restore\n"
"Context"
msgstr "संदर्भ\n"
"पूर्वस्थितीत आणा"

#: ../src/restorecon_source.py:39
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon '$SOURCE_PATH'.\n"
"    "
msgstr ""
"\n"
"    restorecon आदेश चालवून तुम्ही पूर्वनिर्धारीत\n"
"    प्रणालीचा संदर्भ पूर्ववत् करू शकता.  restorecon '$SOURCE_PATH'.\n"
"    "

#: ../src/restorecon_source.py:45
#, python-format
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $SOURCE_PATH may\n"
"    be mislabeled.  $SOURCE_PATH default SELinux type is\n"
"    <B>%s</B>, but its current type is <B>$SOURCE_TYPE</B>. Changing\n"
"    this file back to the default type may fix your problem.\n"
"    <p>\n"
"    This file could have been mislabeled either by user error, or if an "
"normally confined application\n"
"    was run under the wrong domain.\n"
"    <p>\n"
"    However, this might also indicate a bug in SELinux because the file "
"should not have been labeled\n"
"    with this type.\n"
"    <p>\n"
"    If you believe this is a bug, please file a bug report against this "
"package.\n"
"    "
msgstr ""

#: ../src/restorecon_source.py:60
#, python-format
msgid ""
"If you want to fix the label. \n"
"$SOURCE_PATH default label should be %s."
msgstr ""

#: ../src/restorecon_source.py:65
msgid "you can run restorecon."
msgstr "तुम्ही restorecon चालवू शकता."

#: ../src/rsync_data.py:31
msgid ""
"\n"
"    SELinux denied RSYNC access to $TARGET_PATH.\n"
"    If this is an RSYNC repository, it has to have a file context label of\n"
"    rsync_data_t. If you did not intend to use $TARGET_PATH as an RSYNC "
"repository,\n"
"    this message could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/rsync_data.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t rsync_data_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"rsync_data_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    तुम्ही फाइल संदर्भ chcon -R -t rsync_data_t '$TARGET_PATH' कार्यान्वीत "
"करून बदलवू शकता\n"
"    तुम्ही पूर्णतया पुन्हलेबल संचयीत करण्याकरीता प्रणालीवरील पूर्वनिर्धारीत "
"फाइल सदंर्भ फाइल देखील बदलवू शकता.  \"semanage fcontext -a -t rsync_data_t "
"'$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/rsync_data.py:45
msgid "If $TARGET_BASE_PATH should be shared via the RSYNC daemon"
msgstr ""

#: ../src/rsync_data.py:46
msgid "You need to change the label on $TARGET_BASE_PATH"
msgstr "$TARGET_BASE_PATH वरील लेबल बदलणे आवश्यक आहे"

#: ../src/samba_share.py:27
msgid ""
"\n"
"    SELinux is preventing Samba ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux Samba ($SOURCE_TYPE) \"$ACCESS\" ला $TARGET_PATH करीता प्रवेश "
"करण्यापासून रोखत आहे. \n"
"    "

#: ../src/samba_share.py:31
msgid ""
"\n"
"    SELinux denied samba access to $TARGET_PATH.\n"
"    If you want to share this directory with samba it has to have a file "
"context label of\n"
"    samba_share_t. If you did not intend to use $TARGET_PATH as a samba "
"repository,\n"
"    this message could indicate either a bug or an intrusion attempt.\n"
"    Please refer to 'man samba_selinux' for more information on setting up "
"Samba and SELinux.\n"
"    "
msgstr ""

#: ../src/samba_share.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t samba_share_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"samba_share_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    तुम्ही chcon -R -t samba_share_t '$TARGET_PATH' चालवून फाइल संदर्भ बदलवू "
"शकता\n"
"     संपूर्णतया पुनःलेबल केल्यावरही संग्रहीत करण्यासाठी तुम्ही प्रणालीवरील "
"पूर्वनिर्धारीत फाइल संदर्भ फाइल्स् बदलवू शकता.  \"semanage fcontext -a -t "
"samba_share_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/samba_share.py:53
#, python-format
msgid ""
"# semanage fcontext -a -t samba_share_t '$FIX_TARGET_PATH%s'\n"
"# restorecon %s -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t samba_share_t '$FIX_TARGET_PATH%s'\n"
"# restorecon %s -v '$FIX_TARGET_PATH'"

#: ../src/sandbox_connect.py:33
msgid ""
"\n"
"    SELinux has denied $SOURCE from connecting to a network port "
"$PORT_NUMBER within a sandbox.\n"
"    If $SOURCE should be allowed to connect on $PORT_NUMBER, you need to use "
"a different sandbox type like sandbox_web_t or sandbox_net_t.  \n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to connect to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/sandbox_connect.py:41
msgid ""
"\n"
"    If you want to allow $SOURCE to connect to $PORT_NUMBER, you can execute "
"\n"
"\n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    "
msgstr ""
"\n"
"    $SOURCEला $PORT_NUMBERसह जोडणी करण्यासाठी परवानगी द्यायची असल्यास, खालील "
"चालवा \n"
"\n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    "

#: ../src/sandbox_connect.py:49
msgid ""
"you need to modify the sandbox type. sandbox_web_t or sandbox_net_t.\n"
"For example:\n"
"sandbox -X -t sandbox_net_t $SOURCE_PATH\n"
"Please read 'sandbox' man page for more details.\n"
msgstr ""

#: ../src/selinuxpolicy.py:29
msgid "\n"
"    Your system may be seriously compromised!\n"
"    "
msgstr "\n"
"    तुमच्या प्रणालीला गंभीर धोका होऊ शकतो!\n"
"    "

#: ../src/selinuxpolicy.py:33
msgid ""
"\n"
"    SELinux has prevented $SOURCE from modifying $TARGET.  This denial\n"
"    indicates $SOURCE was trying to modify the selinux policy configuration.\n"
"    All applications that need this access should have already had policy\n"
"    written for them.  If a compromised application tries to modify the "
"SELinux\n"
"    policy this AVC will be generated. This is a serious issue. Your system\n"
"    may very well be compromised.\n"
"    "
msgstr ""

#: ../src/setenforce.py:27
msgid "If you did not directly cause this AVC through testing."
msgstr ""

#: ../src/setenforce.py:28
msgid "if you think that you might have been hacked"
msgstr "तुम्ही हॅक झाले आहात असे तुम्हाला वाटते"

#: ../src/setenforce.py:32
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to modify "
"SELinux enforcement.\n"
"    "
msgstr ""
"\n"
"    तुमच्या प्रणालीला गंभीर धोका होऊ शकतो! $SOURCE_PATH ने SELinux "
"enforcement संपादीत करण्याचा प्रयत्न केला.\n"
"    "

#: ../src/setenforce.py:36
msgid ""
"\n"
"    SELinux has prevented $SOURCE from writing to a file under /sys/fs/"
"selinux.\n"
"    Files under /sys/fs/selinux control the way SELinux is configured.\n"
"    All programs that need to write to files under /sys/fs/selinux should "
"have already had policy\n"
"    written for them. If a compromised application tries to turn off SELinux\n"
"    this AVC will be generated. This is a serious issue. Your system may "
"very\n"
"    well be compromised.\n"
"    "
msgstr ""

#: ../src/setenforce.py:48
msgid "If you believe $SOURCE_PATH tried to disable SELinux."
msgstr ""

#: ../src/setenforce.py:49
msgid ""
"you may be under attack by a hacker, since confined applications should "
"never need this access."
msgstr ""
"मर्यादित ॲप्लिकेशन्स्ला या प्रवेशची आवश्यकता नसल्याने, तुम्हाला हॅकरतर्फे "
"धोका असू शकतो."

#: ../src/sshd_root.py:36
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be mislabeled. sshd is allowed to read content in /root/.ssh directory "
"if it\n"
"    is labeled correctly.\n"
"    "
msgstr ""

#: ../src/sshd_root.py:42
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.\n"
"    # restorecon -R /root/.ssh\n"
"    "
msgstr ""

#: ../src/sshd_root.py:55
msgid "Restore Context"
msgstr "संदर्भ पूर्वस्थितीत आणा"

#: ../src/swapfile.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" to $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux $SOURCE_PATH \"$ACCESS\" ला $TARGET_PATH करीता प्रवेश पासून रोखत "
"आहे.\n"
"    "

#: ../src/swapfile.py:31
msgid ""
"\n"
"    SELinux denied $SOURCE access to $TARGET_PATH.\n"
"    If this is a swapfile, it has to have a file context label of\n"
"    swapfile_t. If you did not intend to use\n"
"    $TARGET_PATH as a swapfile, this message could indicate either a bug or "
"an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/swapfile.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -t swapfile_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"swapfile_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -t swapfile_t '$TARGET_PATH' चालवून तुम्ही फाइल संदर्भ बदलवू शकता\n"
"    पूर्णतया पुनः लेबल केल्यावरही संग्रहीत करण्यासाठी तुम्ही प्रणालीवरील "
"पूर्वनिर्धारीत फाइल संदर्भ फाइल्स् बदलू शकता.  \"semanage fcontext -a -t "
"swapfile_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/sys_module.py:28
msgid ""
"If you do not believe your $SOURCE_PATH should be modifying the kernel, by "
"loading kernel modules"
msgstr ""

#: ../src/sys_module.py:29
msgid "You might have been hacked."
msgstr "तुम्ही हॅक्ड् झाले असाल."

#: ../src/sys_module.py:33
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to load a "
"kernel module.\n"
"    "
msgstr ""
"\n"
"    तुमच्या प्रणालीला गंभीर धोका होऊ शकतो! $SOURCE_PATH ने कर्नल घटक लोड "
"करण्याचा प्रयत्न केला.\n"
"    "

#: ../src/sys_module.py:37
msgid ""
"\n"
"    SELinux has prevented $SOURCE from loading a kernel module.\n"
"    All confined programs that need to load kernel modules should have "
"already had policy\n"
"    written for them. If a compromised application\n"
"    tries to modify the kernel this AVC will be generated. This is a serious\n"
"    issue. Your system may very well be compromised.\n"
"    "
msgstr ""

#: ../src/sys_module.py:46
msgid ""
"If you do not believe that $SOURCE_PATH should be attempting to modify the "
"kernel by loading a kernel module."
msgstr ""

#: ../src/sys_module.py:47
msgid "A process might be attempting to hack into your system."
msgstr "प्रोसेस तुम्हच्या प्रणालीत हॅक करण्याचा प्रयत्न करत असेल."

#: ../src/sys_resource.py:28
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH the \"sys_resource\" capability.\n"
"    "
msgstr ""

#: ../src/sys_resource.py:32
msgid ""
"\n"
"    Confined domains should not require \"sys_resource\". This usually means "
"that     your system is running out some system resource like disk space, "
"memory, quota etc. Please clear up the disk and this\n"
"    AVC message should go away. If this AVC continues after you clear up the "
"disk space, please report this as a bug.\n"
"    "
msgstr ""

#: ../src/sys_resource.py:39
msgid ""
"If you do not want processes to require capabilities to use up all the "
"system resources on your system;"
msgstr ""

#: ../src/sys_resource.py:40
msgid ""
"you need to diagnose why your system is running out of system resources and "
"fix the problem.\n"
"\n"
"According to /usr/include/linux/capability.h, sys_resource is required to:\n"
"\n"
"/* Override resource limits. Set resource limits. */\n"
"/* Override quota limits. */\n"
"/* Override reserved space on ext2 filesystem */\n"
"/* Modify data journaling mode on ext3 filesystem (uses journaling\n"
"   resources) */\n"
"/* NOTE: ext2 honors fsuid when checking for resource overrides, so\n"
"   you can override using fsuid too */\n"
"/* Override size restrictions on IPC message queues */\n"
"/* Allow more than 64hz interrupts from the real-time clock */\n"
"/* Override max number of consoles on console allocation */\n"
"/* Override max number of keymaps */\n"
msgstr ""

#: ../src/vbetool.py:30
msgid ""
"\n"
"    SELinux has prevented vbetool from performing an unsafe memory operation."
"\n"
"    "
msgstr ""
"\n"
"    SELinux ने vbetool यास असुरक्षीत स्मृती कार्य करण्यापासून रोखले.\n"
"    "

#: ../src/vbetool.py:34
msgid ""
"\n"
"SELinux denied an operation requested by $SOURCE, a program used\n"
"to alter video hardware state.  This program is known to use\n"
"an unsafe operation on system memory but so are a number of\n"
"malware/exploit programs which masquerade as vbetool.  This tool is used to\n"
"reset video state when a machine resumes from a suspend.  If your machine\n"
"is not resuming properly your only choice is to allow this\n"
"operation and reduce your system security against such malware.\n"
"\n"
"    "
msgstr ""

#: ../src/vbetool.py:45 ../src/wine.py:56
msgid ""
"\n"
"If you decide to continue to run the program in question you will need\n"
"to allow this operation.  This can be done on the command line by\n"
"executing:\n"
"\n"
"# setsebool -P mmap_low_allowed 1\n"
msgstr ""
"\n"
"ठराविक कार्यक्रम चालवायचे असल्यास तुम्हाला हे कार्य स्वीकारावे लागेल.\n"
"  हे आदेश ओळ पासून\n"
"खालील चालवून शक्य आहे:\n"
"\n"
"# setsebool -P mmap_low_allowed 1\n"

#: ../src/vbetool.py:55
msgid ""
"If you want to ignore this AVC because it is dangerous and your machine "
"seems to be working correctly."
msgstr ""

#: ../src/vbetool.py:56
msgid ""
"you must tell SELinux about this by enabling the vbetool_mmap_zero_ignore "
"boolean."
msgstr "vbetool_mmap_zero_ignore बूलियन सुरू करून SELinux ला याविषयी कळवा."

#: ../src/vbetool.py:62 ../src/wine.py:73
msgid "Turn off memory protection"
msgstr "स्मृती सुरक्षा बंद करा"

#: ../src/wine.py:31
msgid ""
"\n"
"    SELinux has prevented wine from performing an unsafe memory operation.\n"
"    "
msgstr ""
"\n"
"    SELinux ने wine यांस असुरक्षीत स्मृती कार्य करण्यापासून रोखले.\n"
"    "

#: ../src/wine.py:35
msgid ""
"\n"
"SELinux denied an operation requested by wine-preloader, a program used\n"
"to run Windows applications under Linux.  This program is known to use\n"
"an unsafe operation on system memory but so are a number of\n"
"malware/exploit programs which masquerade as wine.  If you were\n"
"attempting to run a Windows program your only choices are to allow this\n"
"operation and reduce your system security against such malware or to\n"
"refrain from running Windows applications under Linux.  If you were not\n"
"attempting to run a Windows application this indicates you are likely\n"
"being attacked by some for of malware or program trying to exploit your\n"
"system for nefarious purposes.\n"
"\n"
"Please refer to\n"
"\n"
"http://wiki.winehq.org/PreloaderPageZeroProblem\n"
"\n"
"Which outlines the other problems wine encounters due to its unsafe use\n"
"of memory and solutions to those problems.\n"
"\n"
"    "
msgstr ""

#: ../src/wine.py:66
msgid ""
"If you want to ignore this AVC because it is dangerous and your wine "
"applications are working correctly."
msgstr ""

#: ../src/wine.py:67
msgid ""
"you must tell SELinux about this by enabling the wine_mmap_zero_ignore "
"boolean."
msgstr ""
"wine_mmap_zero_ignore बूलियन सुरू करून तुम्ही SELinux ला याविषयी कळवा."

#: ../src/xen_image.py:27
msgid ""
"\n"
"    SELinux is preventing xen ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux xen ($SOURCE_TYPE) \"$ACCESS\" ला $TARGET_PATH करीता प्रवेश "
"करण्यापासून रोखत आहे. \n"
"    "

#: ../src/xen_image.py:31
msgid ""
"\n"
"    SELinux denied xen access to $TARGET_PATH.\n"
"    If this is a XEN image, it has to have a file context label of\n"
"    xen_image_t. The system is setup to label image files in directory /var/"
"lib/xen/images\n"
"    correctly.  We recommend that you copy your image file to /var/lib/xen/"
"images.\n"
"    If you really want to have your xen image files in the current "
"directory, you can relabel $TARGET_PATH to be xen_image_t using chcon.  You "
"also need to execute semanage fcontext -a -t xen_image_t '$FIX_TARGET_PATH' "
"to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a xen\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux ने $TARGET_PATH करीता xen प्रवेश नकारला.\n"
"    ही XEN प्रतिमा असल्यास, त्याचे फाइल संदर्भ लेबल \n"
"    xen_image_t असे असायला हवे. प्रणाली प्रतिमा फाइल्स्चे /var/lib/xen/"
"images\n"
"    येथे साठवते.  प्रतिमा फाइलचे प्रत /var/lib/xen/images येथे असावे असे "
"सूचवले जाते.\n"
"    सध्याच्या डिरेकट्रीत xen प्रतिमा फाइल हवे असल्यास, तुम्ही chcon चा वापर "
"करून $TARGET_PATH यांस xen_image_t असे पुनःलेबल करू शकता. नवीन मार्ग प्रणाली "
"पूर्वनिर्धारीतमध्ये समाविष्ट करण्यासाठी तुम्हाला semanage fcontext -a -t "
"xen_image_t '$FIX_TARGET_PATH'\n"
"    चालवावे लागेल. $TARGET_PATH ला xen\n"
"    प्रतिमा म्हणून वापरायचे नसल्यास, यांस बग किंवा अवैध प्रवेश प्रयत्न "
"म्हणून ओळखले जाईल\n"
"    "

#: ../src/xen_image.py:41
msgid ""
"\n"
"    You can alter the file context by executing chcon -t xen_image_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"xen_image_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    तुम्ही chcon -t xen_image_t '$TARGET_PATH' वापरून फाइल संदर्भ बदलवू शकता\n"
"    पूर्ण पुन्हलेबल संग्रहीत करण्याकरीता तुम्ही पूर्वनिर्धारीत संदर्भ फाइल "
"मध्ये सुध्दा बदल केला पाहिजे.  \"semanage fcontext -a -t xen_image_t "
"'$FIX_TARGET_PATH'\"\n"
"    "
